### ISSUE TITLE
Remove 2.2 after 23rd of December 2019

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#1000]
According to https://dotnet.microsoft.com/platform/support/policy/dotnet-core .NET Core 2.2 is going to reach the end of support at 23rd of December 2019

Since we have a LOT of CI legs and there is a lot of `#if` in the code I believe that it would be good to remove all 2.2 stuff **after** it becomes

- [ ]  snap a branch with the existing state
- [ ]  update `.yml` file and build matrix page
- [ ]  update all `#if NETCOREAPP2_2` usages
- [ ]  update all docs that mention 2.2

**Comment by billwert** [comment]
I've added snapping a branch to the list - in the event we ever need to run 2.2 tests for some reason I'd like to have an easy way to do that.

**Comment by adamsitnik** [comment]
> I've added snapping a branch to the list 

good idea!
