### ISSUE TITLE
Seed Randoms

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/performance#1032]
I see there are several unseeded `Random`s in the benchmarks. I'm guessing that seeding these would do no harm, and possibly increase stability based on the details of the algorithms they are testing.

```c#

C:\git\performance\src\benchmarks\micro\coreclr\SIMD\RayTracer\Raytracer.cs:
   72:         private Random _rand = new Random();

C:\git\performance\src\benchmarks\micro\coreclr\V8\Crypto\Crypto.cs:
 1750:             Random rnd = new Random();

C:\git\performance\src\benchmarks\micro\corefx\System.Numerics.Vectors\Util.cs:
   11:         private static Random s_random = new Random();

C:\git\performance\src\benchmarks\micro\corefx\System.Runtime.Extensions\Perf.Random.cs:
   17:         public Random ctor() => new Random();

C:\git\performance\src\benchmarks\other\dmlib\RandomStream.cs:
   35:         private Random generator = new Random();

C:\git\performance\src\benchmarks\other\dmlib\TempFileStream.cs:
   19:         private static Random random = new Random();

C:\git\performance\src\benchmarks\other\docker\Util.cs:
  225:         private static Random Generator = new Random();

```

**Comment by adamsitnik** [comment]
https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/coreclr/SIMD/RayTracer/Raytracer.cs#L72

This should most probably have a const seed :+1: 

---
https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/coreclr/V8/Crypto/Crypto.cs#L1749-L1750

This is a dead code (the `#USE_RANDOM_SEED` is not set)

https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/coreclr/V8/Crypto/Crypto.cs#L37
---
https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/corefx/System.Numerics.Vectors/Util.cs#L11

This is used by `ctor` benchmarks where we only care about vector length:

https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/corefx/System.Numerics.Vectors/GenericVectorConstructorTests.cs#L66

---
https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/corefx/System.Runtime.Extensions/Perf.Random.cs#L16-L17

This is a benchmark that tests the parameter less ctor so we do it on purpose.

The other mentioned code samples are not used for benchmarking anymore (`dmlib` and `docker` stuff)
