### ISSUE TITLE
Documentation needs to be updated for dotnet/runtime

### ISSUE THREAD

**Issue by ts2do** [dotnet/performance#1113]
The repo documentation needs to be updated to reflect the workflow for running benchmarks against private dotnet/runtime builds.

I have been trying to benchmark a private build without much luck. I've been executing the following commands, but it doesn't create the hard links that I was getting when I built corefx using CoreCLROverridePath.
```powershell
./coreclr.cmd -c Release
./libraries.cmd -c Release
```

**Comment by gfoidl** [comment]
https://github.com/dotnet/performance/issues/990 should cover this too.

**Comment by ts2do** [comment]
I'm closing this as a duplicate.
