### ISSUE TITLE
Benchmarking selected frameworks, common.props file

### ISSUE THREAD

**Issue by HoundThe** [dotnet/performance#1184]
Hey there!

I was trying to make a script that runs clones and runs the micro benchmarks, but I've found an issue. I want to use the .NET packages that are on my system, so I don't want to use the python script because that downloads the framework from the internet. So I want to use the dotnet CLI but not for every framework version, and I found this in the docs how to use selected runtimes

<https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md#using-net-cli>
> If you don't want to install all of them and just run the benchmarks for selected runtime(s), you need to manually edit the common.props file.

the common.props is a link to non existing file on github and I didn't find it anywhere in the repository, so maybe the docs about this aren't up-to date? Should I just edit the 
``` <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">netcoreapp2.1;netcoreapp3.0;netcoreapp3.1;netcoreapp5.0</TargetFrameworks>```

in the MicroBenchmark.csproj file?

**Comment by adamsitnik** [comment]
Hi @HoundThe 

> Should I just edit th in the MicroBenchmark.csproj file?

Yes.

I've updated the docs in #1185. The alternative is to set `PERFLAB_TARGET_FRAMEWORKS` environment variable to selected Target Framework Moniker. This is what our python script does.

**Comment by HoundThe** [comment]
Thanks a lot for the quick response!
