### ISSUE TITLE
Expand the Perf test coverage for the System.Numerics.Vector types

### ISSUE THREAD

**Issue by tannergooding** [dotnet/performance#1222]
The current perf test coverage for the System.Numerics.Vector types is fairly limited (this extends to types such as Matrix4x4, Quaternion, and Plane as well).

Given that these are meant to be fairly core high-performance types (used in things such as Multimedia-based applications), it is important that we have a high amount of perf-test coverage over the current implementations.

**Comment by adamsitnik** [comment]
> should this be moved to dotnet/performance?

@tannergooding good idea! #done
