### ISSUE TITLE
Using PerfView/perfcollect with Linux traces

### ISSUE THREAD

**Issue by tmds** [dotnet/performance#1238]
I got a basic introduction to PerfView from @adamsitnik and I've been using it to look at ASP.NET Linux `perfcollect` traces.

I want to share some observations.

- One thing that shows up is `[unknown] (/ (deleted))` and `[unknown] ([unknown])`.
Something could not be resolved here. I'm not sure what is the root cause.

`[unknown]` also shows up for .NET assemblies, for example (from `perf.data.txt`):
```
7fb9cca7adff [unknown] (/tmp/benchmarks-agent/benchmarks-server-6/y2nugpcp.ex4/shared/Microsoft.NETCore.App/5.0.0-alpha.1.20103.10/System.Collections.Concurrent.dll
```

And the epoll_wait system call here doesn't show up under any managed code:

![epoll_wait_callers](https://user-images.githubusercontent.com/1025424/76622139-31b57580-6531-11ea-8320-791bd5a99716.PNG)

- A lot of traces have spikes of `kernel.kallsyms!ret_from_intr`. I guess these are activities that are triggered by interrupts from the kernel that are unrelated to what I'm profiling. I've been adding it to `ExcPats` to get rid of the spikes.

- I wonder if I can reduce the depth that is shown for systemcalls in the flamegraph. If I want to see `kernel.kallsyms!__x64_sys_*`, but not their children. Is there a way to do that?

cc @adamsitnik @brianrob @noahfalk

**Comment by billwert** [comment]
Hello! I think this issue probably belongs in microsoft/perfview. It looks like the JIT maps didn't properly get collected, which would be a bug in perfcollect.

I can't transfer the issue as it is across orgs, so I'll copy it and open it there.
