### ISSUE TITLE
'py . setup' fails if lscpu has 'unknown size' for caches

### ISSUE THREAD

**Issue by eanger** [dotnet/performance#1250]
Some systems may not have properly configured lscpu output, where the reported value for things like L1d/L1i/L2/L3 cache size is 'unknown size'. Consider changing line: 
https://github.com/dotnet/performance/blob/bce72f868c37f6af15dc788e1162c52751f01521/src/benchmarks/gc/src/commonlib/host_info.py#L133
to `return map_option(get_opt(name), lambda s: int(remove_str_end(s, "K")) if s != 'unknown size' else None)`

**Comment by billwert** [comment]
cc: @ivdiazsa
