### ISSUE TITLE
Option to run benchmarks in a folder

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/performance#1277]
I am interested in running benchmarks inside [runtime folder](https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/runtime) but looks like there is no unified namespace that I can use to filter. Is there a way to specify folder or should we add namespace based on folders?

**Comment by billwert** [comment]
Does the `Runtime` category not suffice? Is it too big?

In general categories are the solution to this. If we need to add more categories that's the approach I would take.

**Comment by kunalspathak** [comment]
I was not aware of `category` filter, but looking at it, there are benchmarks outside the runtime folder that are tagged as `Runtime` . Even the [AnyCategories](https://github.com/dotnet/BenchmarkDotNet/blob/e8bf99272bc410601863bda338b57d0c46baad70/src/BenchmarkDotNet/Filters/AnyCategoriesFilter.cs#L15) and [AllCategories](https://github.com/dotnet/BenchmarkDotNet/blob/e8bf99272bc410601863bda338b57d0c46baad70/src/BenchmarkDotNet/Filters/AllCategoriesFilter.cs#L15) doesn't filter benchmarks who just has a particular category.  E.g. [Json_Net](https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/Serializers/Json_FromStream.cs#L89) . 
I can certainly add a new category and tag all the 100+ methods with it or easier to update the namespace to begin with folder name so I can just use that something like  `--filter "folder.*"`.

**Comment by billwert** [comment]
@adamsitnik 

Unfortunately folders get lost by the time we build the benchmarks, because benchmarks are built into a single DLL and the names are pulled out of metadata at runtime. I think the best we can do here will require a BDN feature, which would either let you have negative search on `--filter` or `--category`. I don't know how that would stack on their priority list.

**Comment by adamsitnik** [comment]
> I think the best we can do here will require a BDN feature, which would either let you have negative search

I agree that it would be great to have a negative search feature. Could you please create an issue with some examples in the BDN repo?

Another thing that could possibly work without any BDN changes would be passing some magic regex expression to `--filter` which is internally using .NET Regex to find the matches:

https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Filters/GlobFilter.cs

**Comment by kunalspathak** [comment]
> Another thing that could possibly work without any BDN changes would be passing some magic regex expression to --filter which is internally using .NET Regex to find the matches:

I tried with some simple regex, but apparently it didn't work. 
`dotnet artifacts\MicroBenchmarks.dll --filter "BenchStone.BenchF.*|BenchStone.BenchI.*" --list tree`

**Comment by billwert** [comment]
Closing this one as we have an issue in the right place now.
