### ISSUE TITLE
Accessing static variables inside benchmark code

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/performance#1292]
Many benchmark code access static variables inside benchmark code. The access produces call to helpers. Sometimes running the helper function is more expensive than the benchmark code. Consider revisiting them to see if we can use non-static variables. Ofcourse, testing the access of static variables is important, but we can restrict it to certain benchmarks instead of all benchmarks.

**Comment by kunalspathak** [comment]
[PerfLabTests.CastingPerf2.CastingPerf.ObjrefValueTypeObj](https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/runtime/perflab/CastingPerf2.cs#L220) 

```asm
        AA0003EF          mov     x15, x0
        97FF6528          bl      CORINFO_HELP_CHECKED_ASSIGN_REF ; <-- helper call
        11000673          add     w19, w19, #1
        5290D400          movz    w0, #0x86a0
        72A00020          movk    w0, #1 LSL #16
```

![image](https://user-images.githubusercontent.com/12488060/79921385-ef603d80-83e6-11ea-9d4c-588a35224f30.png)

**Comment by BruceForstall** [comment]
I'm a little surprised the JIT can't just determine the entire expression is loop invariant and eliminate the loop entirely.

In this case, presumably the access to static `InnerIterationCount200000` is also more expensive than a local?

**Comment by kunalspathak** [comment]
> I'm a little surprised the JIT can't just determine the entire expression is loop invariant and eliminate the loop entirely.

Yes, I will open an issue to track this. This is general optimization not related to arm64.

> In this case, presumably the access to static InnerIterationCount200000 is also more expensive than a local?

```asm
G_M64166_IG05:
        D295320D          movz    x13, #0xa990
        F2BD242D          movk    x13, #0xe921 LSL #16
        F2C04CED          movk    x13, #615 LSL #32
        F94001AD          ldr     x13, [x13]
        910021AE          add     x14, x13, #8
        9100228D          add     x13, x20, #8
        97E5BA4D          bl      CORINFO_HELP_ASSIGN_BYREF
        97E5BA4C          bl      CORINFO_HELP_ASSIGN_BYREF
        11000673          add     w19, w19, #1
; this is loading the value of InnerIterationCount200000 
        D2964600          movz    x0, #0xb230
        F2B65D00          movk    x0, #0xb2e8 LSL #16
        F2CFFEE0          movk    x0, #0x7ff7 LSL #32
        B9400000          ldr     w0, [x0]
        6B00027F          cmp     w19, w0
        54FFFC6B          blt     G_M64166_IG03
```

**Comment by kunalspathak** [comment]
https://github.com/dotnet/runtime/issues/35279

**Comment by adamsitnik** [comment]
If this is a problem, we should rewrite these benchmarks to not use any [loops](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#Loops).

In this case, the benchmark could be just:

```cs
public object ObjrefValueTypeObj() => orvt = (FooORVT)o;
```

But we would have to make sure that the JIT is not applying any kind of constant folding to such simplified benchmark. So things like:

```cs
public boll IsOperatorBenchmark() => o is FooORVT;
```

Are not optimized to:

```cs
public boll IsOperatorBenchmark() => true;
```

**Comment by billwert** [comment]
@kunalspathak is this still relevant? Maybe @BruceForstall made the jit smarter? :)

**Comment by kunalspathak** [comment]
Perhaps because we haven't still yet eliminated `static` variables.
