### ISSUE TITLE
Comparison tool needs to show test names more fully

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#1325]
In #1322 it's been pointed out that the comparison tool doesn't show the full name.

I think we should smartly truncate long names something like this:
```
....Serialization.Tests.ReadMissingAndCaseInsensitive<Location>
```
The beginning of the namespace is almost always never interesting, IMO.

Thoughts?

cc: @adamsitnik @ooooolivia @DrewScoggins

**Comment by adamsitnik** [comment]
Good point. We could take the last 80 chars, not the first 80 chars and even make the magic `80` number configurable via console line argument.

**Comment by billwert** [comment]
#1768 is a good fix for this.
