### ISSUE TITLE
profiling instructions for visual studio

### ISSUE THREAD

**Issue by mrj001** [dotnet/performance#1337]
I'm using the x64 Native Tools Command Prompt for VS2019 Preview.
The version of VS is Version 16.7.0 Preview 1.0 (Community Edition)
Following the instructions in blob/master/docs/profiling-workflow-dotnet-runtime.md, I use the following commands:
```
git clean -xdf
git pull upstream master
build -c Release
dir artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
```
This shows:

> 
>  Volume in drive C is Windows
>  Volume Serial Number is 4276-5595
> 
>  Directory of C:\Users\mrj00\source\repos\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
> 
> 2020-05-27  12:03 PM    <DIR>          .
> 2020-05-27  12:03 PM    <DIR>          ..
> 2020-04-03  07:26 AM           143,232 dotnet.exe
> 2020-05-27  12:03 PM    <DIR>          host
> 2020-05-27  11:57 AM    <DIR>          shared
>                1 File(s)        143,232 bytes
>                4 Dir(s)  1,857,612,795,904 bytes free
```
dir artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\5.0.0
```
shows a large number of DLLs, plus CoreRun.exe and another copy of dotnet.exe.

Note that I had to change "netcoreapp5.0" from the directions to net5.0 to match the paths created.
```
SET DOTNET_ROOT=C:\Users\mrj00\source\repos\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64
dir %DOTNET_ROOT%
SET DOTNET_MULTILEVEL_LOOKUP=0
SET PATH=%DOTNET_ROOT%;%PATH%
devenv
```
The line "dir %DOTNET_ROOT%" was just to confirm that I got the path correct.

In the opening dialog of Visual Studio, I selected a project.  This project failed to open.  When I right-clicked it in Solution Explorer and chose Reload Project, I got this error:
![image](https://user-images.githubusercontent.com/62225294/83071110-d2440d80-a029-11ea-9822-ca8a5a911d3d.png)

Other than netcoreapp5.0 to net5.0, I'm not sure what to change to get this working.

**Comment by rzikm** [comment]
I am facing the same problem, I will add that setting env vars accordingly leads to following `dotnet --info` output:

```
❯ .\dotnet.exe --info

Host (useful for support):
  Version: 5.0.0-preview.4.20202.18
  Commit:  0375524a91

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.0 [D:\dotnet-runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App]

```

I am sure that the issue is in the `No SDKs were found` part, but I don't know how to solve it.

**Comment by adamsitnik** [comment]
The instructions got updated in #1718
