### ISSUE TITLE
Port mono benchmarks to this repo

### ISSUE THREAD

**Issue by marek-safar** [dotnet/performance#1359]
Port https://github.com/mono/mono/tree/master/sdks/wasm/standalone-benchmarks to this repo. The most useful probably will be the high-level benchmarks.

/cc @lewing

**Comment by kg** [comment]
Is there any good documentation in-repo or existing examples on how we'd want to integrate wasm into what we have here? The use of BenchmarkDotNet etc poses some new problems that we were able to ignore when doing this in the mono/ repo.

**Comment by marek-safar** [comment]
BenchmarkDotNet has built-in support for WASM https://github.com/dotnet/BenchmarkDotNet/blob/master/docs/articles/configs/toolchains.md#wasm

It uses our testing setup which we might actually help them to clean up

**Comment by billwert** [comment]
@marek-safar @lewing @kg Now that we've been running the normal benchmarks on Mono (and WASM) for quite some time, do we need this as well? Is there a set of benchmarks in there that's highly valuable? Or should we close this issue?

**Comment by kg** [comment]
The benchmarks ported over were merged, there are some additional ones for some of the bindings work but those can't land yet. So you can close this
