### ISSUE TITLE
Update Blazorwasm PowerBi 

### ISSUE THREAD

**Issue by ooooolivia** [dotnet/performance#1392]
This issue is for gathering feedbacks and tracking to-do items for [Blazorwasm PowerBi dashboard](aka.ms/dotnetperfstatus). Feel free to comment below to suggest other improvements on the dashboard. 
- [x] validation for automatic data refresh
- [x] trim part of the path to fit in the graph (not able to due to aggregation problem, but 'file name' added in the tooltip )
- [ ] add link to linker dump
- [ ] link graphs and remove the build time filters (abandoned due to power bi limit)
- [x] make trend graphs not dynamic based for easier detection of anomalies/noise
- [x] clarify master branch
- [x] add preview 8 branch
- [x] individual graph for each binary
- [ ] select latest build in treemap (abandoned due to power bi limit)
- [x] show installer version 
- [x] fill in missing data between 7/12 - 7/17
- [x] update baseline to include .br files
------------------------- from 8/3/2020 sync-up --------------------------------
- [x] add commit hash next to build time list
- [x] add support for dynamic start & end points of graph range
- [x] add a drop-down menu for the list of files
- [ ] extend preview branches as static baseline 
- [x] mark unit of the axis (crossgen report)

**Comment by danmosemsft** [comment]
does it make sense to have separate "square diagrams" for uncompressed, gzip and brotli? the size of the whole is not significant - we care about them separately. I don't feel strongly either way

**Comment by ooooolivia** [comment]
@danmosemsft  Do you mean a treemap showing the size of individual files of type "uncompressed", "gzip" and "brotli"? If you scroll down the dashboard page, we do have this in the second graph.

![image](https://user-images.githubusercontent.com/51934529/87182790-ac04c500-c299-11ea-874a-7a1c746dec5f.png)

**Comment by danmosemsft** [comment]
Ah - thanks

**Comment by marek-safar** [comment]
I disagree with enhancement classification. The dashboard as-is today does not work at all. The last update is from 3 weeks ago and data included as pointed our by @eerhardt are wrong (3.2 data used for master). Please work on fixing the fundamentals problems first.

**Comment by ooooolivia** [comment]
@marek-safar  Since when did blazorwasm transition from 3.2 to 5.0? We do notice that in preview 6 there's still 3.2 template, and that's what our data reflect. We are actively fixing the data transfer pipeline for blazor since it's just set up.

**Comment by marek-safar** [comment]
> Since when did blazorwasm transition from 3.2 to 5.0

It was in .NET5 P7 but I'm not sure if that matters. We need to be able to track master changes at least daily (ideally even more than that).

**Comment by ooooolivia** [comment]
@marek-safar  by "master" do you mean blazor master? If SDK master still carries blazor3.2 version as it's unsynced, we are happy to remove the data that still shows blazor3.2 but from SDK 5.0. In our graph, the "master" means the installer's master branch.

**Comment by marek-safar** [comment]
> by "master" do you mean blazor master?

Yes.

**Comment by ooooolivia** [comment]
There's an issue in the installer repo that the latest asset produced stays at 7/12/2020 https://github.com/dotnet/installer/issues/8011 , will keep tracking this issue.

**Comment by lewing** [comment]
The data and graphs are getting much better day by day, thank you so much for working on this.  One thing that is consistently confusing is the lack of 0 lower bound, would it be possible to include a small lower bound to force power bi to scale graphs in absolute terms?

**Comment by ooooolivia** [comment]
@lewing  Thanks for the feedback! Yes the trend graph has just been updated with fixed start and end values. Changes in smaller files may be too trivial to identify now. Please let me know if you'd prefer separate graphs for large values and small values. 

![image](https://user-images.githubusercontent.com/51934529/87977131-14fef080-ca83-11ea-9c92-40a80ca38508.png)
![image](https://user-images.githubusercontent.com/51934529/87977183-2b0cb100-ca83-11ea-8eef-aead2f3bc321.png)

**Comment by lewing** [comment]
The data from today has a file size for icudt.dat that doesn't match what I'm seeing.

**Comment by lewing** [comment]
@ooooolivia very helpfully walked me through where the package versions come from and I'll wait for the installer to catch up.

**Comment by ooooolivia** [comment]
There's missing data between 8/7 - 8/10 because there's problem with inserting new SDK into installer. https://github.com/dotnet/installer/pull/8129

**Comment by eerhardt** [comment]
@billwert - can we remove the old files from the list on the left?

![image](https://user-images.githubusercontent.com/8291187/108543257-73ef4700-72aa-11eb-92f5-37cb9b42368e.png)

These files haven't been part of the output since September, but they still show up in the dashboard. It is pretty confusing.

**Comment by billwert** [comment]
Interesting. I'll take a look. I suspect this is happening because they are still in the trends for older builds.

Thanks,
-Bill

**Comment by billwert** [comment]
> These files haven't been part of the output since September, but they still show up in the dashboard. It is pretty confusing.

This is fixed in the update I just pushed. The issue was that by default nothing was selected in the build table, so nothing was filtering the file list. Now it's a slicer which will always select "latest", which is dynamically updated. Let me know what you think.

**Comment by danmoseley** [comment]
For the graphs showing the break down by component files
![image](https://user-images.githubusercontent.com/6385855/112390029-e6d94c80-8cb2-11eb-8457-2e91f75f406e.png)
you might consider having a second set that use a logarithmic y axis (just a PowerBI setting)

As it is, dotnet.wasm and the next couple of large files dominate the chart so it's not possible to see any changes in the smaller files. You have to click on each square in turn.

**Comment by danmoseley** [comment]
Incidentally I don't think I understand the difference bewteen these two charts.

**Comment by radical** [comment]
Is this still the place to give feedback about the Blazorwasm powerbi pages?
The individual file trend chart shows data from mid-2020 to now, which makes it less than useful. It would be useful to have controls for the date range.

cc @lewing @DrewScoggins
