### ISSUE TITLE
Change netcoreapp5.0 to net5.0

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/performance#1458]
It's my understanding that the correct moniker to use for 5.0 is `net5.0`. I am not sure if that could be causing unexpected issues.
This change would have to be done in csproj and md files.

**Comment by adamsitnik** [comment]
Hi @carlossanlop !

We know that we should switch to new moniker, but there are always more important and urgent things to implement ;p

I am going to close this issue as it's tracked by https://github.com/dotnet/performance/issues/1426

Thanks!
