### ISSUE TITLE
Make path to mono corerun in prof file move with version updates

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1472]
We currently have to manually update the runtime version string in the proj files checked into arcade. We should look into what would need to be done to have this be automatic.

**Comment by adamsitnik** [comment]
Do you mean the change from `5.0.0` to `6.0.0` in https://github.com/dotnet/runtime/pull/41132?

Most probably there is some magic MSBuild property that comes from Arcade / directory.build.props file that contains this version number and could be used like this:

```diff
-<CoreRunArgument>--corerun %HELIX_CORRELATION_PAYLOAD%\dotnet-mono\shared\Microsoft.NETCore.App\6.0.0\corerun.exe</CoreRunArgument>
+<CoreRunArgument>--corerun %HELIX_CORRELATION_PAYLOAD%\dotnet-mono\shared\Microsoft.NETCore.App\$(MagicVariable)\corerun.exe</CoreRunArgument>
```

@safern or @ViktorHofer should know best

**Comment by safern** [comment]
That would be repo specific. But there is MajorVersion, MinorVersion and BuildVersion.

In this case since this is not a runtime repo, we would need to set it here directly.
