### ISSUE TITLE
Runtime perf runs in public pipelines

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1476]
Currently, we do not have live PR support, but we do still run batched commit on the public queues in runtime. Since we are not collecting any performance data from these we should turn them off. Likely, we will want to just wrap all of the jobs in conditionals so they do not fire on public pipelines.

Also part of this we should see if we can re-enable per PR runs but only on demand. That way when we are making infra changes we can still run them to make sure we are correct, but not have them running on every PR.

Thoughts @adamsitnik?

**Comment by adamsitnik** [comment]
@DrewScoggins I like the idea of having it on-demand to verify that some big infra changes are not breaking the perf runs. For me so far the most common problem was the removal of corerun from the test host folder.

@ViktorHofer @safern what are your thoughts on this?

**Comment by safern** [comment]
So CI runs are the only protection we have. If we turn those off and we make an infra change and forget to run them on demand we could break the perf runs?

**Comment by adamsitnik** [comment]
An alternative solution could be to run a single benchmark for every PR (not all benchmarks once, but just one benchmark once). It should be enough to detect infra changes?

**Comment by safern** [comment]
Where do infra changes happen are those in dotnet/runtime? Can we make the pipeline path based?

**Comment by DrewScoggins** [comment]
Infra changes can happen in dotnet/runtime, or they can happen in dotnet/performance. There are also some components that live in Arcade, but they are normally changed in the runtime repo as well so I am not worried about those. The biggest stuff that happens is changes to the pipeline or the arcade changes, which if we had a single test running that should give us the coverage we need, at a low machine cost. The changes in the dotnet/performance repo will need to be guarded there, and we plan to add some runs in that repo that are similar to the runtime repo to make sure we catch changes on that side.
