### ISSUE TITLE
Failure in Drawing test when running on Alpine

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/performance#1480]
Here's how I was able to successfully run on Alpine (in WSL in my case)

1. Installed Alpine WSL from the Windows store
1. Open cmd prompt
1. `wsl.exe --distribution Alpine --user root`
1.` passwd` # set root pwd
1. `apk add sudo`
1. un-commenting a line in the`/etc/sudoers` file to allow anyone use sudo who is in the sudo group `sudo ALL=(ALL) ALL`
1. `addgroup sudo`
1. `usermod -aG sudo <username>`    # adds your user as a sudoer
1. `passwd <username>`

At this point I simply continued as root, but you could instead log in as yourself and sudo as needed

`apk add git python3 bash wget`     # generally useful

`apk add libstdc++ libgcc lttng-usg`    # required by dotnet

`apk add icu-libs` # or maybe icu; required by dotnet

`apk add libgdiplus --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/` # for System.Drawing in perf tests

`apk add giflib-dev` # this is supposed to fix the error in the Sytem.Drawing tests ("missing codec") but doesn't seem to do it for me

https://github.com/danmosemsft/performance/commit/9b9b401ac7c8951afe09ee8a3e8d2b96cf2beb94` # apply this change to actually fix the Drawing tests

(assumes this is merged to fix copy tests: https://github.com/dotnet/performance/pull/1479 )

Now you can actually run perf tests, eg.

`python3 ../performance/scripts/benchmarks_ci.py -f netcoreapp3.1 netcoreapp5.0 --filter '*'`

Unless we can figure out the right `apk add` magic, we should consider removing Gif from the perf test matrix at least for Alpine - this line here https://github.com/danmosemsft/performance/commit/9b9b401ac7c8951afe09ee8a3e8d2b96cf2beb94

**Comment by danmosemsft** [comment]
cc @billwert @DrewScoggins @adamsitnik 

I did this because I was curiuos how we looked on a MUSL distribution and whether we should consider running Alpine regularly.

**Comment by danmosemsft** [comment]
cc @safern

**Comment by danmosemsft** [comment]
With the help of @akoeplinger I was able to do commands like
```
apk update --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
apk upgrade  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
apk add libgdiplus --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
```
and finally get `libgdiplus-6.0.4-r1 x86_64` installed.

I can confirm this fixes the problem. In short: if we want to run tests on Alpine, we need to ensure `libgdiplus-6.0.4-r1 x86_64` (as well as other stuff above) is on the images.

@billwert feel free to close, or to leave open to enable Alpine runs at some point in the future.

**Comment by billwert** [comment]
@danmosemsft We should probably have a chat about Alpine at some point and how we want to handle other distros. I'm going to close this one for now and we can reopen it if needed.
