### ISSUE TITLE
Add Tool Chain for Net 5.0 Mono AOT

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#1481]
This existing tool chain doesn't work for AOT in Net 5.0, so we need to create a new one. I think this can be done in the performance repo instead of BenchmarkDotnet, although maybe we want to put it there instead?

**Comment by naricc** [comment]
If some one could please assign me to this issue :)

**Comment by adamsitnik** [comment]
>  I think this can be done in the performance repo instead of BenchmarkDotnet, although maybe we want to put it there instead?


You might need to change something in BDN itself to make it work (the same way you did with `WasmToolchain`).

You can start by adding it here and over time we can move it to BenchmarkDotnet repository.

**Comment by SamMonoRT** [comment]
https://github.com/dotnet/BenchmarkDotNet/pull/1662 should  address this
