### ISSUE TITLE
can mono runtime use this for profiler?

### ISSUE THREAD

**Issue by srxqds** [dotnet/performance#1493]
I found the profiler document at https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md.
could I use it with mono runtime?
if not, how can I propfiler with mono runtime?

**Comment by adamsitnik** [comment]
> could I use it with mono runtime?

I am afraid not, these instructions are specific to .NET Core. 

> how can I propfiler with mono runtime?

@brianrob @SamMonoRT @akoeplinger do we have any docs that describe how to profile Mono?

**Comment by akoeplinger** [comment]
>  do we have any docs that describe how to profile Mono?

Yes we have some docs here: https://www.mono-project.com/docs/debug+profile/profile/profiler/.

@SamMonoRT can probably comment on what plans we have to integrate into the dotnet profiling tools.

**Comment by srxqds** [comment]
but the mono profiler can not be built on Windows?

**Comment by akoeplinger** [comment]
hmm I think it should be built on Windows too but I'm not that familiar with it.
