### ISSUE TITLE
net6.0 moniker

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#1540]
The new moniker for .NET 6.0 (`net6.0`) is soon coming to the SDK. 

I was told by @ViktorHofer that once https://github.com/dotnet/runtime/pull/42709 gets merged it should be a matter of +- 2 weeks until it's recognized by .NET SDK.

Currently, when I am using `benchmarks_ci.py -f netcoreapp5.0` it downloads .NET 6.0 bits from the master channel. It's fine as long as I don't want the actual .NET 5.0 (my current use case). I know that it's possible to specify the channel in an explicit way like the CI does.

@billwert @ooooolivia would it be OK if I send a PR that adds support of `net6.0` to the python scripts? It would internally map to the master channel installers and existing `net5.0` moniker. I would change the `net5.0` mapping to use the .NET 5 channel. And when the SDK starts to recognize `net6.0`, I would send a new PR with the removal of artificial mapping to older tfm for 6.0

I am not sure if my description explains it correctly, but basically what I would like to do is:

```diff
 channel_map = {
    'master': {
-        'tfm': 'netcoreapp5.0',
        'branch': 'master'
    },
  channel_map = {
    'master': {
+        'tfm': 'net6.0',
        'branch': 'master'
    },

```

**Comment by billwert** [comment]
@adamsitnik this sounds like a totally reasonable plan. Thanks for doing this!

Will this work properly with our current version of BDN? I think so but I wanted to ask.

**Comment by billwert** [comment]
#1569 is moving the repo to master. BDN doesn't yet support `--runtimes net6.0`, but it turns out we don't really need that flag right now in this repo so #1569 elides it. I'm also pulling in your fixes from #1541.

**Comment by adamsitnik** [comment]
@billwert thanks for the heads up! 

In case BDN does not work well with .NET 6.0 you can upgrade it to `0.12.1.1418` which has the "official" support: https://github.com/dotnet/BenchmarkDotNet/pull/1523

**Comment by billwert** [comment]
Seems to be working fine so I'll decouple upgrading from this to reduce moving variables.

**Comment by billwert** [comment]
turns out I did need to upgrade, but past `1418`. I was wrong about "working fine". :) I suspect it was [this](https://github.com/dotnet/BenchmarkDotNet/pull/1560) in `0.12.1.1448` that is the magic.

**Comment by adamsitnik** [comment]
I've synced my fork with the upstream and tested the #1569 changes.

Everything works like a charm! @billwert thank you!

```cmd
py .\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter Burgers
```

![obraz](https://user-images.githubusercontent.com/6011991/97701928-74bb5d80-1aae-11eb-86e1-1e3f7fe47352.png)



```cmd
py .\scripts\benchmarks_ci.py -f net6.0 --filter Burgers
```

![obraz](https://user-images.githubusercontent.com/6011991/97701889-640ae780-1aae-11eb-9f22-c56809455fd9.png)
