### ISSUE TITLE
.NET 5 TargetFramework usage

### ISSUE THREAD

**Issue by sfoslund** [dotnet/performance#1545]
With .NET 5 we are introducing a new style of target framework that includes target platform information (for example, net5.0-windows). This repo contains logic that will break with these new target frameworks, specifically, see this line: https://github.com/dotnet/performance/blob/master/src/benchmarks/real-world/JitBench/Store/CreateStore/bugfix_sdk_1682/Microsoft.NET.ComposeStore.targets#L431. 
The `TargetFrameworkMoniker` cannot be used in place of the `TargetFramework` as the target framework moniker does not contain required platform information and will likely fail with new .NET 5 target frameworks like net5.0-windows. Please test and ensure that this target does not break .NET 5 scenarios, thanks!

**Comment by adamsitnik** [comment]
Hi @sfoslund 

Thank you for the heads-up!

The benchmarks from this [particular folder](https://github.com/dotnet/performance/tree/master/src/benchmarks/real-world/JitBench) are not used anymore so we should be fine.

@billwert should we consider removing these benchmarks as this is not the first time when they cause confusion (https://github.com/dotnet/performance/issues/497)?

FWIW the harness that we use for micro-benchmarking (BenchmarkDotNet) is going to support the platform specific TMS with the next release: https://github.com/dotnet/BenchmarkDotNet/pull/1560

**Comment by billwert** [comment]
Great idea @adamsitnik. thanks @sfoslund!
