### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by kg** [dotnet/performance#1552]
https://github.com/dotnet/performance/blob/master/docs/basic-scenarios.md links to https://github.com/dotnet/performance/blob/master/docs/scenarios-workflow#step-1-initialize-environment, which does not exist. It might be sufficient to link to a specific revision of the repo so the link still works, but doing that in general would mean you get bounced to outdated content...

**Comment by adamsitnik** [comment]
Hi @kg 

thank you for the bug report. It got fixed by #1551 which I've just merged so the links should work now
