### ISSUE TITLE
Unable to find package Microsoft.DotNet.Arcade.Sdk

### ISSUE THREAD

**Issue by eanger** [dotnet/performance#157]
Trying to build the micro benchmarks using the CLI (via `dotnet build -c Release`) fails with the following error:

> dotnet-performance/Directory.Build.props(7,3): error : Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): api.nuget.org, benchmarkdotnet-ci-feed, dotnet-core
dotnet-performance/Directory.Build.props(7,3): error : Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): api.nuget.org, benchmarkdotnet-ci-feed, dotnet-core

This builds just fine before #155. Do I need to change my settings somehow to find the package?

**Comment by adamsitnik** [comment]
Hello @eanger !

We already have a fix for that waiting for review in #156. Until it gets merged, please apply the fix manually or revert the arcade commit

**Comment by adamsitnik** [comment]
Fixed with #160
