### ISSUE TITLE
Nightly perf reports for Crossgen have Crossgen2 results mixed in

### ISSUE THREAD

**Issue by nattress** [dotnet/performance#1609]
The nightly [crossgen perf report](https://pvscmdupload.blob.core.windows.net/reports/12_01_2020/Crossgen/report_Daily_ca=x64_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_tf=Crossgen_cc=CompliationMode=tiered-RunKind=crossgen_scenarios_2020-12-01.html) for Crossgen throughput / size has Crossgen2 results in it too. Perhaps we're substring matching and now we have Crossgen2 perf metrics they're getting included unintentionally.

The [crossgen2 perf report](https://pvscmdupload.blob.core.windows.net/reports/12_01_2020/Crossgen2/report_Daily_ca=x64_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_tf=Crossgen2_cc=CompliationMode=tiered-RunKind=crossgen_scenarios_2020-12-01.html) only has Crossgen2 entries as I'd expect.

**Comment by nattress** [comment]
@DrewScoggins Is the report generation on Github somewhere?

**Comment by DrewScoggins** [comment]
You are correct. We just use a call to Contains to decide if the filter matches. It is not hosted on Github, but you can find it here, https://nettel.visualstudio.com/_git/perflab.

I had noticed this and have been thinking about a solution, but had not had any great ideas so far.
