### ISSUE TITLE
New Random tests don't work with runtime LKG

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#1642]
We currently use the runtime LKG package to build tests in the runtime repo. It hasn't been updated to include 6.0 APIs yet. We can fix this for our runs by using runtime packs (as we did for Blazor runs.) Until we do so, turning these tests back off so they aren't causing failures in our microbenchmark runs.

**Comment by billwert** [comment]
fyi @danmosemsft - we'll get this fixed ASAP.

**Comment by danmosemsft** [comment]
Oh thanks @billwert ...

**Comment by danmoseley** [comment]
Note to fixer: please uncomment code marked with `https://github.com/dotnet/performance/issues/1642`.

**Comment by danmoseley** [comment]
Hmm, I see we have priority queue tests now -- https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Collections/PriorityQueue/Perf_PriorityQueue.cs
