### ISSUE TITLE
ResultsComparer fails to find package MarkdownLog.NS20 (via NuGet) after change: Fixup feeds (#1654)

### ISSUE THREAD

**Issue by L2** [dotnet/performance#1667]
Hello, thanks for the great project.

Steps to reproduce:
(1) Visual Studio -> tools -> NuGet Package Manager -> Package Manager Settings -> Clear All NuGet Cache(s)
(2) clone this repo -> checkout commit be6a4cc541614 (Fixup feeds (#1654))
(3) dotnet run --base "foo" --diff "bar" --threshold 1%

```
Error:
error NU1101: Unable to find package MarkdownLog.NS20. No packages exist with this id in source(s): benchmark-dotnet-prerelease, dotnet-eng, dotnet-public, dotnet-tools, dotnet3.1, dotnet3.1-transport, dotnet5, dotnet5-transport, dotnet6
The build failed. Fix the build errors and run again.
```

(4) Clear NuGet cache again
(5) using the prior commit -> checkout commit ba87c1a40bfe (Add AzDo feed for BDN (#1660))
(6) dotnet run --base "foo" --diff "bar" --threshold 1%

No error

---------

Looks like some issue when `<add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />` was removed and maybe `<add key="dotnet-public" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" />` doesn't have MarkdownLog.NS20?

Thanks for the help.

**Comment by billwert** [comment]
@dotnet/dnceng @mmitche Can we add `MarkdownLog.NS20` please?

Thanks @L2 for the report!

**Comment by MattGal** [comment]
> @dotnet/dnceng @mmitche Can we add `MarkdownLog.NS20` please?
> 
> Thanks @L2 for the report!

On it, thanks for the heads up.

**Comment by mmitche** [comment]
Done

**Comment by billwert** [comment]
Verified fixed.
