### ISSUE TITLE
Better alerting for performance lab

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#1674]
Work items:

- [x] Add Azure blob container (failedresults) and table (failedruninfo) for storing failed run information
- [ ] Script in performance repo uploads JSON with failed run information
- [x] Code in perflab enters failed run information into failedruninfo table
- [ ] Email alert sent when entries are added to failedruninfo table

**Comment by Tohron** [comment]
PRs:
https://github.com/dotnet/performance/pull/1703
https://nettel.visualstudio.com/perflab/_git/perflab/pullrequest/267

**Comment by Tohron** [comment]
Both PRs are merged, and email alerting is now configured properly.
