### ISSUE TITLE
Alpine bringup

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#1676]

**Comment by danmoseley** [comment]
@DrewScoggins what is the effect of this -- does this mean that we now run all our existing Linux perf tests (not just dotnet/runtime tests) on Alpine as often as on Ubuntu, and therefore we'll get an issue opened for any Alpine specific regressions now?

**Comment by DrewScoggins** [comment]
Yes, we have been getting runs at the same rate as all others in the runtime repo since Feb 17. Starting with our triage meeting tomorrow, we will have auto-filing and issues moved into runtime as we find them on that platform.

**Comment by billwert** [comment]
> does this mean that we now run all our existing Linux perf tests (not just dotnet/runtime tests)

@danmoseley can you elaborate on what you mean here?

**Comment by danmoseley** [comment]
I meant - do we run all the same tests (out of dotnet/performance) for Alpine as we do currently on Ubuntu? (I was just confused because the PR linked above was in dotnet/runtime)

**Comment by danmoseley** [comment]
But I think @DrewScoggins answered my question -- thanks!
