### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by reegeek** [dotnet/performance#1695]
Hi all,

I would like to contribute to this repo.
What are the contribution guidelines ?
Should i start with an issue then a PR ?

Regards,

**Comment by billwert** [comment]
Hello @reegeek! Starting with an issue is a great way to go. It's also worth reading [this document](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md) for some guidelines on how we think about benchmarks in the repo generally.
