### ISSUE TITLE
Foreach on list

### ISSUE THREAD

**Issue by reegeek** [dotnet/performance#1696]
Hi,
In my part time I am working on [StructLinq](https://github.com/reegeek/StructLinq) which try to improve linq performance.
I think some part could be integrate in dotnet/Runtime.

Foreach on list should be as fast as a foreach on an array but it is not the case.
Here result of a [benchmark](https://github.com/reegeek/StructLinq/blob/master/Documents/BenchmarksResults/ForEachOnList.md) from [StructLinq](https://github.com/reegeek/StructLinq):
``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-8750H CPU 2.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.101
  [Host]     : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X64 RyuJIT
  DefaultJob : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X64 RyuJIT


```
|     Method |      Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------- |----------:|----------:|----------:|------:|------:|------:|------:|----------:|
|    Default | 19.996 μs | 0.0651 μs | 0.0577 μs |  1.00 |     - |     - |     - |         - |
| StructLinq |  3.781 μs | 0.0132 μs | 0.0117 μs |  0.19 |     - |     - |     - |         - |

I would like to add microbenchmark on foreach on list in this repo before open an issue (and submit a PR) in dotnet/runtime. 

Regards,

**Comment by danmoseley** [comment]
Hello. Can you show your benchmark? 
Are you using unsafe code inside your own library?

**Comment by reegeek** [comment]
Benchmark is available [here](https://github.com/reegeek/StructLinq/blob/master/src/StructLinq.Benchmark/ForEachOnList.cs)
I don't use unsafe code, I am just using a layout to have access to underlying array (which is not necessary in Runtime repo).
I am using the same enumerator between a list and an array.
[ListEnumerable](https://github.com/reegeek/StructLinq/blob/master/src/StructLinq.BCL/List/ListEnumerable.cs).
[ArrayEnumerator](https://github.com/reegeek/StructLinq/blob/master/src/StructLinq/Array/ArrayStructEnumerator.cs)
In fact I discover after writing it that is the same enumerator than [ImmutableArray](https://source.dot.net/#System.Collections.Immutable/System/Collections/Immutable/ImmutableArray_1.Enumerator.cs,570249d040af2b99).
I made some iterations/tests and I think is the best enumerator for an array.
