### ISSUE TITLE
Profiling workflow instructions are missing a step

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/performance#1715]
In the [Prerequisites](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#prerequisites) section, we have incomplete information.

Summarized, these are the steps described there:

1) Build dotnet/runtime in Release.
2) Create a new console app and add a `for` loop with the code you want to profile.
3) Modify your console app's *.csproj file so that it targets net6.0, debugtype=pdbonly, debugsymbols=true and tieredcompilation=false.
4) Create a *.cmd script that forces the consumption of the `dotnet.exe` runtime we generated in our build, by pointing the `DOTNET_ROOT` env. variable to the `runtime\artifacts\bin\testhost\net6.0-windows-Release-x64\` folder, and specifically avoid looking for other .NET SDKs in other folders by setting `DOTNET_MULTILEVEL_LOOKUP` to `0`.
5) Run the script so that devenv runs our solution with the specific env. variable context.

The problem of forcing DOTNET_ROOT to point to the built `testhost` folder is that we only have a _runtime_ there, not a full _SDK_. Visual Studio needs an SDK to be able to load the *.csproj and to build it. Right now, VS fails to load the *.csproj with this error message:

```
D:\testing\ConsoleCore\MyProject.csproj : error  :
The project file cannot be opened. Unable to locate the .NET SDK.
Check that it is installed and that the version specified in global.json
(if any) matches the installed version.
```

@safern gave me a workaround to address this. We have to add a new step in the instructions, between 4 and 5:

> Go to `%repos%\runtime\.dotnet` and copy the folders `sdks` and `packs`, then go to `runtime\artifacts\bin\testhost\net6.0-windows-Release-x64\` and paste those two folders there.

This ensures VS consumes a full SDK. I can now re-run the script, and Visual Studio is able to load the *.csproj successfully and build the app without problems.

Please keep in mind this is just a workaround. If you know of a better way to address this, without having to copy-paste those two folders, please let me know. Otherwise, I can update the *.md file with these new instructions.

cc @adamsitnik

**Comment by adamsitnik** [comment]
> If you know of a better way to address this, without having to copy-paste those two folders, please let me know.

I don't. @stephentoub do you have a better idea?

> Otherwise, I can update the *.md file with these new instructions.

This would be awesome! Thanks for solving the problem and sharing the solution!
