### ISSUE TITLE
Hang running System.Net.Security.Tests.SslStreamTests.DefaultHandshakePipeAsync

### ISSUE THREAD

**Issue by danmoseley** [dotnet/performance#1732]
I got a hang on one of my Windows machines about 10 hours in. I have dump, logs, etc in `\\danmose3\public\foradam\hang`	

It's waiting for this benchmark to complete
`[2021/03/16 20:07:39][INFO] // Execute: dotnet "c8f219de-c08c-44da-8d8e-cb6168618ed0.dll" --benchmarkName "System.Net.Security.Tests.SslStreamTests.DefaultHandshakePipeAsync" --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=.NET 5.0, Arguments=/p:DebugType=portable, Toolchain=net5.0, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1" --benchmarkId 2100 in C:\git\performance\artifacts\bin\MicroBenchmarks\Release\net5.0\c8f219de-c08c-44da-8d8e-cb6168618ed0\bin\Release\net5.0`

https://github.com/dotnet/performance/blob/e285e027fe59826d8e60eda270f4615c6baf93c1/src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.cs#L108-L126

just one managed thread, which I guess is waiting on the async test method
```
000000FE78F7D7F8 00007ff90ede29d4 [HelperMethodFrame_1OBJ: 000000fe78f7d7f8] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
000000FE78F7D920 00007ff8d67b6cd3 System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
000000FE78F7D9C0 00007ff8d67ca939 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
000000FE78F7DA30 00007ff8d67ca7e7 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
000000FE78F7DAB0 00007ff8d683c484 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
000000FE78F7DAE0 00007ff8d683c42c System.Runtime.CompilerServices.TaskAwaiter.GetResult()
000000FE78F7DB10 00007ff87763bc24 BenchmarkDotNet.Autogenerated.Runnable_2100.<.ctor>b__3_2()
000000FE78F7DB50 00007ff87763bbc2 BenchmarkDotNet.Autogenerated.Runnable_2100.WorkloadActionNoUnroll(Int64)
000000FE78F7DB90 00007ff87763a07e BenchmarkDotNet.Engines.Engine.RunIteration(BenchmarkDotNet.Engines.IterationData)
000000FE78F7DCD0 00007ff877639acc BenchmarkDotNet.Engines.EngineFactory.Jit(BenchmarkDotNet.Engines.Engine, Int32, Int32, Int32)
```
!dumpasync gives me
```
         Address               MT     Size      State Description
00000210857b5c58 00007ff877722040      208          3 System.Net.Security.SslStream+<ForceAuthenticationAsync>d__171`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security]]
00000210857b5dd0 00007ff87776a148      184          0 System.Net.Security.Tests.SslStreamTests+<DefaultHandshake>d__24
```

I can then dump those objects, but I'm really not sure how to proceed. @wfurt can you figure anything more out from this dump? This is your test and I think you know this code best.

cc @adamsitnik

**Comment by wfurt** [comment]
We used to have functional  HTTP tests similar to this and disabled them on Windows as unstable. I suspect this may be be underlying IO issue. 

Depending on the side and state, the ForceAuthenticationAsync is trying to read TLS frame from underlying IO and than it is given to PAL for processing. AFAIK, there is really no other synchronization. 

Perhaps the fix/workaround would be to pass real `CancellationToken` with timeout instead of `default`. So at least when something goes wrong the test does not hang. @adamsitnik may have idea how to indicate that the test run is actually invalid.

**Comment by danmoseley** [comment]
It looks like an unhandled exception would be fine.
