### ISSUE TITLE
Benchmarks failed with UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 223: character maps to <undefined>

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/performance#1742]
I tried running perf benchmarks and ended up with this error: 

```
Traceback (most recent call last):
  File "D:\src\repos\performance\scripts\benchmarks_ci.py", line 247, in <module>
    __main(sys.argv[1:])
  File "D:\src\repos\performance\scripts\benchmarks_ci.py", line 225, in __main
    micro_benchmarks.run(
  File "D:\src\repos\performance\scripts\micro_benchmarks.py", line 309, in run
    BENCHMARKS_CSPROJ.run(
  File "D:\src\repos\performance\scripts\dotnet.py", line 457, in run
    RunCommand(cmdline, verbose=verbose).run(
  File "D:\src\repos\performance\scripts\performance\common.py", line 187, in run
    (returncode, quoted_cmdline) = self.__runinternal(working_directory)
  File "D:\src\repos\performance\scripts\performance\common.py", line 176, in __runinternal
    for line in iter(proc.stdout.readline, ''):
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 223: character maps to <undefined>
```

@danmoseley had sent out an (internal) email suggesting those with a access to non-standard machines give this a try to help out .NET 6.0 perf efforts and I have a homebrew Ryzen 9 3900X box with lots of RAM which I thought would be a good machine to run this on. Too bad this failed  partway through (it didn't produce any net6.0 logs at all). If someone could help puzzle out what went wrong and fix this, I'll be happy to try again in a week. 

Are there additional logs I can share here (or offline) that could be of more help, for e.g.? 

/cc @adamsitnik

**Comment by danmoseley** [comment]
Hi @vatsan-madhavan, the ` BenchmarkRun-*.log` in `performance\artifacts\bin\MicroBenchmarks\Release\net5.0\BenchmarkDotNet.Artifacts` or `performance\artifacts\bin\MicroBenchmarks\Release\net6.0\BenchmarkDotNet.Artifacts` (whichever one it died on) would be helpful. Also any of the console output leading up to the failure, in case it didn't make it to the log.

Thanks for trying this! We have already fixed some glitches, as well as gathered a bunch of data.

**Comment by vatsan-madhavan** [comment]
[net5.0.zip](https://github.com/dotnet/performance/files/6179385/net5.0.zip)

Nothing at all was generated for net6.0 (it doesn't have `BenchmarkDotNet.Artifacts` folder). The attached zip has net5.0 logs. I also included a log file in the zip generated by copy-pasting from the console spew.

**Comment by billwert** [comment]
@vatsan-madhavan can you share the command line you ran the script with? I assume it did not include the verbose option.

**Comment by vatsan-madhavan** [comment]
It was `.\performance\scripts\benchmarks_ci.py -f net5.0 net6.0 --filter *` - I think it launched python implicitly.

**Comment by danmoseley** [comment]
The logs say the OS was `Windows 10.0.21337` which is the latest dev channel build (assuming it's from the same VBL) -- if so it's possibly some OS change. Although, I did'nt have this issue running on 21332.1010.
