### ISSUE TITLE
Missing Minimum Blazor template publish (and AOT) and Pizza App-Publish AOT in wire size file breaddown

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/performance#1815]
It would be great to add the Test App selection for Minimum template in the file breakdown section in the https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0 charts. 

![image](https://user-images.githubusercontent.com/46026722/118859135-e4a50000-b8a7-11eb-8917-a1793cce96d4.png)

**Comment by SamMonoRT** [comment]
cc @DrewScoggins

**Comment by DrewScoggins** [comment]
Sorry, I missed this last week. I am taking a look now.
