### ISSUE TITLE
Missing size data on Blazor size dashboard

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/performance#1820]
@DrewScoggins is already looking into it logging here for visibility : The Blazor Size Reduction dashboard (https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0) is missing all visual representation of the data after 5/19/2021.
The data seems to be updating correctly in the backend, auto filled issues opened, but not updating the PowerBI here.

![image](https://user-images.githubusercontent.com/46026722/119500866-43e69280-bd36-11eb-9d93-ea828fae92ab.png)

**Comment by DrewScoggins** [comment]
I have made a manual update for now to get more recent data, and am in the process of splitting the datasets, because the issue is that we take more than two hours to update, and fail the auto-update.

**Comment by DrewScoggins** [comment]
I forgot to update this issue. This has been resolved for the runtime side of the graphs. I am still investigating why data from the installer branch runs are not getting loaded properly despite the data existing in the Azure table, and the data refresh completing successfully in the PowerBI.
