### ISSUE TITLE
Enable markdown lint

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#1822]
As suggested in #1821.

**Comment by danmoseley** [comment]
@bouchraRekhadda any interest in picking this up? Even if you're not familiar with yaml and Github actions, it should be fairly easy to just duplicate what was done in the dotnet/runtime repo: just copy https://github.com/dotnet/runtime/pull/40887

**Comment by bouchraRekhadda** [comment]
>@bouchraRekhadda any interest in picking this up?

More than happy to. I'll give it a try

**Comment by danmoseley** [comment]
Thanks, assigned. It will likely need some tuning to exclude low-value rules (eg perhaps trailing spaces) and retain useful ones (eg broken links)

**Comment by billwert** [comment]
@bouchraRekhadda any luck? :)

**Comment by bouchraRekhadda** [comment]
Thanks for the reminder @billwert 😅; I was busy with work in the past few months and it totally slipped my mind.
I'll take a look today
