### ISSUE TITLE
Regain Intune Accesss for Personal and Work Computer

### ISSUE THREAD

**Issue by Tohron** [dotnet/performance#1829]
Since the evening of Thursday, 5/27, I lost access to Intune-requiring apps on my personal computer (presumably due to needing to upgrade from Windows 10 Home - I'd been delaying the update to wait for my move to finish, but it seems I waited too long).  To resolve the issue, I took my computer in to work on Friday, intending to contact people from my work computer, but that computer wasn't able to access the resources either (from contacting support, it seems that might be due to it being turned off for over 6 months, and thus missing several updates.  At this point, it also has an issue with being unable to update).

So I now have no way to access Teams, my corporate email, or the helpdesk (or any other aka.ms links).  I'm hoping someone can schedule an in-person meeting with a technician in my old office (room 1450 of Building 18) to work out the issues with my personal and work computers.  Until then I'm completely blocked.

@Lxiamail @billwert @DrewScoggins I've also sent you an email from my personal Hotmail account (if you don't see them, check your junk folder).  Please reply either to that or this issue with any responses.  Also FYI, I need to be away from the computer for most of the morning for house-purchase activities, so I'll be able to respond by early afternoon.

**Comment by Tohron** [comment]
Also, just FYI, on Friday I tried getting support via phone - after getting redirected about 5 times from the public support number I started with, I got someone from helpdesk who was able to determine that the issues with my work computer might be due to it being behind on updates, but there were connection issues, so he said he'd hang up and call back, but for whatever reason, that didn't happen.  Thus, I'd prefer in-person support if at all possible.

**Comment by danmoseley** [comment]
@Tohron note that Github project boards can contain "notes" which aren't actually issues. That's what we use when something isn't product related but we want to track it on the board. They aren't visible to anyone not using the board which I'm guessing is what you want.
