### ISSUE TITLE
Is there a way to run a specific case for a single benchmark using the python script?

### ISSUE THREAD

**Issue by L2** [dotnet/performance#1846]
Say I wanted to run the following benchmark only:
`System.IO.Tests.Perf_FileStream.Write_NoBuffering(fileSize: 1048576, userBufferSize: 16384, options: None)`

currently I would just run it like this, but it includes all of the NoBuffering cases:
`py .\scripts\benchmarks_ci.py -c Release -f net6.0 --filter "System.IO.Tests.Perf_FileStream.Write_NoBuffering*"`

Is there a way to include the `(fileSize: 1048576, userBufferSize: 16384, options: None)` part as well to only run that specific one?

Thanks

**Comment by adamsitnik** [comment]
Hi @L2 

No, BenchmarkDotNet does not allow to filter by using argument or param names or values. Please feel free to open an issue in https://github.com/dotnet/BenchmarkDotNet/issues
