### ISSUE TITLE
Microbenchmark build failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/performance#1857]
Sometimes, after doing various microbenchmark runs, I start getting this error:

`C:\Program Files\dotnet\sdk\6.0.100-preview.6.21315.23\Microsoft.Common.CurrentVersion.targets(4501,5): error MSB3021: Unable to copy file "C:\gh\performance\artifacts\obj\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll" to "C:\gh\performance\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll". Access to the path 'C:\gh\performance\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0\BenchmarkDotNet.Extensions.dll' is denied. [C:\gh\performance\src\harness\BenchmarkDotNet.Extensions\BenchmarkDotNet.Extensions.csproj]`

The only thing that seems to fix this is removing the `artifacts` folder and trying again. Killing any still-running dotnet.exe processes doesn't work, neither does deleting just the `C:\gh\performance\artifacts\bin\BenchmarkDotNet.Extensions\Release\netstandard2.0` directory (which does exist).

The command I was running:
`C:\gh\performance\src\benchmarks\micro>dotnet run -c Release -f net6.0 -- --filter *BenchI.Array2* *BenchI.MulMatrix* *BenchF.InProd* ByteMark.BenchLUDecomp ByteMark.BenchAssignJagged --coreRun C:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\CoreRun.exe C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\CoreRun.exe -e GitHub`

**Comment by billwert** [comment]
I suspect this is due to compiler servers. Instead of just killing `dotnet`, try `dotnet build-server shutdown`. If that doesn't work let us know.
