### ISSUE TITLE
Span<ReferenceType>.CopyTo is 10% slower than Array<ReferenceType>.CopyTo

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#188]
```cmd
dotnet run -c Release -f netcoreapp2.1 --filter *CopyTo*.Array *CopyTo*.Span --join --runtimes netcoreapp2.1 netcoreapp3.0
```

``` ini

BenchmarkDotNet=v0.11.3.889-nightly, OS=Windows 10.0.17763.134 (1809/October2018Update/Redstone5)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview-009812
  [Host]     : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT
  Job-BWFXKU : .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05), 64bit RyuJIT
  Job-LTTJWT : .NET Core 3.0.0-preview-27122-01 (CoreCLR 4.6.27121.03, CoreFX 4.7.18.57103), 64bit RyuJIT

Runtime=Core  IterationTime=250.0000 ms  MaxIterationCount=20  
MinIterationCount=15  WarmupCount=1  

```
|           Type | Method |     Toolchain | Size |     Mean |     Error |    StdDev |   Median |      Min |      Max |
|--------------- |------- |-------------- |----- |---------:|----------:|----------:|---------:|---------:|---------:|
|  CopyTo&lt;Int32&gt; |  Array | netcoreapp2.1 | 2048 | 232.8 ns |  7.830 ns |  8.041 ns | 229.6 ns | 225.9 ns | 258.4 ns |  1.00 |    0.00 |
|  CopyTo&lt;Int32&gt; |  Array | netcoreapp3.0 | 2048 | 200.9 ns |  8.277 ns |  9.199 ns | 196.2 ns | 192.5 ns | 220.5 ns |  0.86 |    0.03 |
|                |        |               |      |          |           |           |          |          |          |       |         |             |
|  CopyTo&lt;Int32&gt; |   Span | netcoreapp2.1 | 2048 | 228.9 ns |  4.407 ns |  4.328 ns | 226.7 ns | 225.5 ns | 239.8 ns |  1.00 |    0.00 |
|  CopyTo&lt;Int32&gt; |   Span | netcoreapp3.0 | 2048 | 189.7 ns |  1.403 ns |  1.172 ns | 189.8 ns | 188.1 ns | 191.7 ns |  0.83 |    0.01 |
|                |        |               |      |          |           |           |          |          |          |       |         |             |
| CopyTo&lt;String&gt; |  Array | netcoreapp2.1 | 2048 | 571.2 ns | 43.467 ns | 50.057 ns | 544.1 ns | 528.3 ns | 706.0 ns |  1.00 |    0.00 |
| CopyTo&lt;String&gt; |  Array | netcoreapp3.0 | 2048 | 550.2 ns | 12.294 ns | 10.898 ns | 546.6 ns | 540.0 ns | 577.5 ns |  0.95 |    0.09 |
|                |        |               |      |          |           |           |          |          |          |       |         |             |
| CopyTo&lt;String&gt; |   Span | netcoreapp2.1 | 2048 | 615.4 ns |  9.290 ns |  7.757 ns | 616.2 ns | 605.8 ns | 635.0 ns |  1.00 |    0.00 |
| CopyTo&lt;String&gt; |   Span | netcoreapp3.0 | 2048 | 610.7 ns |  9.951 ns |  8.310 ns | 607.0 ns | 602.9 ns | 633.2 ns |  0.99 |    0.02 |

**Comment by danmosemsft** [comment]
I assumed perf regressions (unless test issues) would still get logged in the same repo as the implementation. What is your guys thinking about this?

**Comment by adamsitnik** [comment]
@danmosemsft  Good point. We need to talk about this with @billwert and @brianrob in January and agree on the process.

Also, with the new "Transfer this issue" feature from GitHub we should be able to easily move it.

**Comment by danmosemsft** [comment]
If the plan is to open the issue in the same repo as the implementation, we'll want to consider how you'll connect that regression back to the issue when it comes up again or we want to check on progress. I'm not sure the best way to do that. One way that's a bit wacky could be to have a rolling issue here for eg., CoreFX regressions, regularly editing the top post to add links to new ones and remove links to closed ones. There's probably better ideas.

**Comment by gfoidl** [comment]
> regularly editing the top post to add links to new ones and remove links to closed ones

Hm, I don't believe this will work safely. Rather it will get stale and outdated.

Maybe just open new issues here and tag them with labels, so via search one can filter all open issues?

**Comment by billwert** [comment]
Code defects causing performance problems should be tracked by issues in the repo where the code lives (or, in the case it is split across both, where we guess the majority of the fix will go.) I agree with @danmosemsft - Issues in this repo should cover test issues and infrastructure issues.

**Comment by adamsitnik** [comment]
I created a new issue in CoreFX: https://github.com/dotnet/corefx/issues/36417
