### ISSUE TITLE
Make work item name more meaningful than *partation*

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#1882]
some of the work item names are *partation. It would be more helpful to name them in meaning way, like test catagory.

**Comment by billwert** [comment]
@Lxiamail The challenge is that with our current scheme we don't break them out by test category. It's more or less random based on how many tests we end up running.

I've long had a dream to do a better job here, so here's a couple thoughts:

1. Redo how we split tests by adding a mode which writes out the list of categories after invoking it in the pipeline. Dispatch each class of tests as its own work item.
2. Simply get the number of tests and dispatch each test ID (a concept we'd make up) as a single work item.

What I've long wanted is the ability to "prebuild" tests and this sort of progress has always stalled on the fact that the idea of prebuilding is very orthogonal to how Benchmark.NET works.

**Comment by billwert** [comment]
Closing for now. If we have a better proposal for this we can revisit.
