### ISSUE TITLE
Loop-unrolling

### ISSUE THREAD

**Issue by EgorBo** [dotnet/performance#189]
Lots of benchmarks under micro/coreclr use inner loops (e.g. https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/coreclr/Bytemark/ByteMark.cs#L445-L455) - are they really needed there?
The problem is - when I run them using new mono-llvm (inprocess) - LLVM unrolls those loops 🙂 and probably .NET Core will also be able to unroll them soon

**Comment by adamsitnik** [comment]
I ported these benchmarks 1:1 to make sure the results we report to BenchView don't change.

I think that we should keep it for the existing ones but avoid when adding new benchmarks to the repo.

@billwert @brianrob what do you guys think?

**Comment by jorive** [comment]
@adamsitnik I thought we already removed those inner loops for some of the benchmarks.

**Comment by adamsitnik** [comment]
@jorive for some yes, but not for all

**Comment by billwert** [comment]
@adamsitnik If the benchmarks are left unmodified do they return the same results as they did using xunit.performance? If so I think it is correct to leave them as they are. If they are returning different results they aren't comparable and I think it is reasonable to make changes that have them looking like we want.

If we are leaving them perhaps we should drop a comment in the ones that aren't unrolled to explain why?

**Comment by adamsitnik** [comment]
> If the benchmarks are left unmodified do they return the same results as they did using xunit.performance?

yes

> If so I think it is correct to leave them as they are.

I agree. We should keep the old ones "as is" unless they cause some troubles or don't make sense, but don't add any inner loops for the new benchmarks.

> If we are leaving them perhaps we should drop a comment in the ones that aren't unrolled to explain why?

I tried to leave the comments where I could, example:

https://github.com/dotnet/performance/blob/3941f11e000edd7a404599fc2e401129c25bc4ad/src/benchmarks/micro/coreclr/perflab/CastingPerf.cs#L95

**Comment by danmosemsft** [comment]
Can we close this then?
