### ISSUE TITLE
wasm interpreter microbenchmark run is broken

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#1904]
- [x] fix benchmarkdotnet to make wasm interpreter run to be consistent with wasm aot (Nathan)
- [ ] PR https://github.com/dotnet/runtime/pull/55353 contains the fix to pass in bdn parameters consistently as wasm aot. Still need to verify once bdn fix is available (Alicia)

**Comment by naricc** [comment]
It looks like this is still broken. A simple run of the microbenchmarks fails:

```
dotnet run --framework net6.0 --runtimes wasm --runtimeSrcDir=$HOME/workspace/runtime-clean
The provided WasmMainJs "" does NOT exist. It MUST be provided.```

I don't understand why yet; the command line validation works correctly in BDN, but some how not when used by dotnet perfromance.

**Comment by naricc** [comment]
@Lxiamail This is fixed now, right?

**Comment by Lxiamail** [comment]
Yes, we are good.
