### ISSUE TITLE
Make our dotnet/performance release branches roll forward properly on Arcade (and any other supporting deps.)

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#1906]
Currently we have Maestro support for moving packages (like the Arcade SDK) into our main branch in dotnet/performance, but not our release branches (like release/3.1.4xx.) We should fix this so we get updates to those packages, making it mirror the main branch.

**Comment by LoopedBard3** [comment]
Do we want to pull the packages using the version specific subscriptions or do we want specifically the same packages as the main branch? (Do we want to pull from arcade release 3.x or main?)

**Comment by LoopedBard3** [comment]
Are there any places that versioning is currently behind where updates should be made before adding the subscription, or do we want maestro to update branches not actively in pipeline use (ex. release/3.1.1xx)? I think that adding maestro updates to all release branches, even if not being actively used in testing, just creates a higher probability of a breaking change not being found.

**Comment by billwert** [comment]
Agreed. I only want to be maintaining branches we're running. When we've stopped running a branch it usually means the product has gone out of our servicing SLA anyway. If we had to bring back a branch we'd have to do housekeeping anyway, so setting up these kinds of subscriptions could happen then.

**Comment by LoopedBard3** [comment]
Bill added a comment to the onenote about a gap in what we are doing here. I will setup the maestro for the current setup and then close this task.

**Comment by LoopedBard3** [comment]
Updated both the 5.0.1xx and 3.1.4xx branches to have maestro auto update the arcade SDK. It will not currently auto-marge. We could change the merge policy to not ignore the license/cla when that is the only check to run or add tests that run. @billwert do you have any specific thoughts? Otherwise we can manually merge that updates in when they need to be merged for the time being.
