### ISSUE TITLE
2.1 vs 2.2 comparison using performance repo

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#193]
In this issue, I am going to post 2.1 vs 2.2 results for the benchmarks we have here using ResultsComparer from #165 

Sample command:

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
.\scripts\benchmarks_ci.py --frameworks netcoreapp2.1 netcoreapp2.2 --architecture x64 --filter *
dotnet run -p .\src\tools\ResultsComparer\ResultsComparer.csproj 
   --base ".\src\benchmarks\micro\bin\Release\netcoreapp2.1\BenchmarkDotNet.Artifacts\results\" 
   --diff ".\src\benchmarks\micro\bin\Release\netcoreapp2.2\BenchmarkDotNet.Artifacts\results\"
   --threshold 10% --noise 1ns
```

**Comment by adamsitnik** [comment]
## Ubuntu 18.04 x64 PC

ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz
BenchmarkDotNet 0.11.3.886-nightly
base: .NET Core 2.1.6 (CoreCLR 4.6.27019.06, CoreFX 4.6.27019.05)
diff: .NET Core 2.2.0 (CoreCLR 4.6.27110.04, CoreFX 4.6.27110.04)

| Slower                                                                                               | diff/base | Base Median (ns) | Diff Median (ns) | Modality              |
| ---------------------------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| ---------------------- |
| System.Collections.CopyTo<Int32>.ImmutableArray(Size: 2048)                                          |      3.48 |            87.45 |           304.64 |                       |
| System.Collections.Concurrent.IsEmpty<String>.Dictionary(Size: 512)                                  |      2.00 |          7233.77 |         14473.46 |                       |
| Functions.MathTests.CosDoubleBenchmark                                                               |      1.52 |         60352.71 |         92024.60 |                       |
| System.Collections.CtorDefaultSize<String>.ImmutableArray                                            |      1.39 |             6.53 |             9.09 |                       |
| System.Collections.IndexerSet<Int32>.Dictionary(Size: 512)                                           |      1.37 |          4700.67 |          6440.06 |                       |
| System.Tests.Perf_String.LastIndexOf(options: CurrentCultureIgnoreCase)                              |      1.34 |        559206.77 |        749641.69 |                       |
| System.Collections.CopyTo<Int32>.Array(Size: 2048)                                                   |      1.29 |           167.15 |           215.02 |                       |
| SeekUnroll.Test(boxedIndex: 3)                                                                       |      1.29 |    1768306956.00 |    2274037732.50 |                       |
| System.Collections.CopyTo<Int32>.ReadOnlySpan(Size: 2048)                                            |      1.27 |           171.11 |           217.70 |                       |
| System.Collections.CopyTo<Int32>.Span(Size: 2048)                                                    |      1.26 |           172.62 |           217.96 |                       |
| System.Collections.ContainsFalse<Int32>.Stack(Size: 512)                                             |      1.26 |        108653.72 |        136997.03 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.IFooObjIsIFoo                                                  |      1.26 |        680309.87 |        855663.61 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.IFooObjIsDescendantOfIFoo                                      |      1.25 |        682509.91 |        855778.84 |                       |
| PerfLabTests.LowLevelPerf.TypeReflectionArrayGetType                                                 |      1.25 |        201338.13 |        251762.33 |                       |
| System.Collections.CopyTo<Int32>.ReadOnlyMemory(Size: 2048)                                          |      1.23 |           187.92 |           232.04 |                       |
| CscBench.CompileTest                                                                                 |      1.23 |     436566092.00 |     538142593.00 | can have several modes|
| PerfLabTests.CastingPerf.ObjFooIsObj2                                                                |      1.23 |        205002.43 |        251748.75 |                       |
| System.Collections.ContainsTrue<Int32>.Stack(Size: 512)                                              |      1.23 |         59170.73 |         72596.56 |                       |
| PerfLabTests.CastingPerf.FooObjIsNull                                                                |      1.23 |        205230.22 |        251721.50 |                       |
| PerfLabTests.CastingPerf.ObjScalarValueType                                                          |      1.22 |        205579.12 |        251758.72 |                       |
| PerfLabTests.CastingPerf.ObjFooIsObj                                                                 |      1.22 |        205548.32 |        251715.12 |                       |
| PerfLabTests.CastingPerf.IFooFooIsIFoo                                                               |      1.22 |        205651.69 |        251741.76 |                       |
| PerfLabTests.CastingPerf.ObjObjrefValueType                                                          |      1.22 |        205694.57 |        251738.97 |                       |
| PerfLabTests.CastingPerf.ObjInt                                                                      |      1.22 |        205869.19 |        251748.03 |                       |
| System.Reflection.Attributes.GetCustomAttributesMethodOverrideMissInherit                            |      1.21 |          2277.36 |          2760.67 |                       |
| System.Globalization.Tests.Perf_CompareInfo.IsSuffix(culture: ja-JP, source: "ABCDE", suffix: "E", o |      1.20 |          3815.34 |          4586.28 |                       |
| System.Collections.CopyTo<Int32>.Memory(Size: 2048)                                                  |      1.20 |           197.20 |           236.86 |                       |
| System.Collections.IterateForEach<Int32>.ImmutableStack(Size: 512)                                   |      1.20 |          3547.73 |          4260.24 | bimodal               |
| MicroBenchmarks.Serializers.Json_ToString<LoginViewModel>.Jil_                                       |      1.17 |          2868.50 |          3350.00 | can have several modes|
| PerfLabTests.DelegatePerf.MulticastDelegateInvoke(length: 1000)                                      |      1.16 |      30355751.56 |      35335613.36 |                       |
| System.Collections.IterateFor<Int32>.ImmutableSortedSet(Size: 512)                                   |      1.16 |          8965.52 |         10393.59 |                       |
| System.Tests.Perf_String.IndexerCheckPathLength                                                      |      1.16 |           112.89 |           130.76 |                       |
| System.Tests.Perf_Array.ArrayRetrieve1D                                                              |      1.15 |       2983349.88 |       3432347.94 |                       |
| System.Collections.Concurrent.AddRemoveFromSameThreads<String>.ConcurrentBag(Size: 2000000)          |      1.15 |     306800366.20 |     352483392.65 |                       |
| System.Tests.Perf_Environment.GetFolderPath(folder: System, option: None)                            |      1.15 |           615.26 |           704.61 |                       |
| System.Collections.Concurrent.AddRemoveFromSameThreads<String>.ConcurrentStack(Size: 2000000)        |      1.14 |     227790276.40 |     258564017.95 |                       |
| System.Globalization.Tests.Perf_CompareInfo.IndexOf(culture: , source: "More Test's", value: "Tests" |      1.13 |          4375.81 |          4944.37 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.IFooFooIsIFoo                                                  |      1.13 |        403783.59 |        455042.52 |                       |
| MicroBenchmarks.Serializers.Binary_FromStream<LoginViewModel>.BinaryFormatter_                       |      1.13 |          3230.10 |          3637.15 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.ObjFooIsObj                                                    |      1.12 |        403254.42 |        453563.90 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.FooObjIsNull                                                   |      1.12 |        403893.38 |        453546.82 |                       |
| MicroBenchmarks.Serializers.Binary_FromStream<CollectionsOfPrimitives>.BinaryFormatter_              |      1.12 |       1596551.94 |       1790917.54 |                       |
| System.Collections.CtorDefaultSizeNonGeneric.SortedList                                              |      1.12 |            40.60 |            45.53 |                       |
| System.Memory.Constructors<String>.MemoryFromArray                                                   |      1.11 |            12.80 |            14.25 |                       |

| Faster                                                                                               | base/diff | Base Median (ns) | Diff Median (ns) | Modality              |
| ---------------------------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| ---------------------- |
| System.Numerics.Tests.Constructor.SpanCastBenchmark_SByte                                            |     16.20 |             8.84 |             0.55 |                       |
| System.Collections.Concurrent.Count<String>.Dictionary(Size: 512)                                    |      3.98 |         15303.11 |          3848.54 |                       |
| System.Memory.MemoryMarshal<Byte>.Read                                                               |      3.79 |             7.59 |             2.00 |                       |
| Benchstone.BenchF.Trap.Test                                                                          |      1.57 |     371708036.00 |     236563752.50 |                       |
| LinqBenchmarks.Where01LinqQueryX                                                                     |      1.52 |     846559723.00 |     556294327.00 |                       |
| System.Collections.CtorDefaultSize<String>.ImmutableSortedSet                                        |      1.47 |             8.17 |             5.57 |                       |
| System.Tests.Perf_Array.ArrayCopy3D                                                                  |      1.36 |           329.56 |           243.05 |                       |
| System.Numerics.Tests.Perf_Vector2.NormalizeBenchmark                                                |      1.31 |             5.12 |             3.90 |                       |
| System.IO.Tests.Perf_FileStream.ReadAsync(BufferSize: 200000, TotalSize: 200000)                     |      1.31 |         42684.09 |         32646.96 | can have several modes|
| SeekUnroll.Test(boxedIndex: 1)                                                                       |      1.28 |    2273664575.00 |    1770272642.50 |                       |
| Functions.MathTests.TanhDoubleBenchmark                                                              |      1.23 |         82115.73 |         66559.42 |                       |
| System.Globalization.Tests.Perf_DateTimeCultureInfo.Parse(culturestring: ja)                         |      1.21 |          5257.00 |          4333.50 | can have several modes|
| MicroBenchmarks.Serializers.Xml_ToStream<XmlElement>.DataContractSerializer_                         |      1.21 |           597.47 |           492.63 |                       |
| System.Memory.Span<Char>.LastIndexOfValue(Size: 512)                                                 |      1.20 |            23.15 |            19.24 |                       |
| MicroBenchmarks.Serializers.Binary_FromStream<CollectionsOfPrimitives>.MessagePack_                  |      1.20 |        103737.11 |         86319.97 |                       |
| System.Collections.Clear<String>.Array(Size: 512)                                                    |      1.17 |           217.56 |           185.24 |                       |
| System.Tests.Perf_String.ToLower(s: "TEST")                                                          |      1.17 |            40.97 |            35.00 |                       |
| System.Memory.Span<Byte>.LastIndexOfValue(Size: 512)                                                 |      1.17 |            17.77 |            15.22 |                       |
| System.Tests.Perf_String.Concat_str_str(size: 100)                                                   |      1.16 |            49.04 |            42.13 |                       |
| System.Globalization.Tests.Perf_CompareInfo.LastIndexOf(culture: , source: "?", value: "?", options: |      1.16 |          4858.72 |          4192.81 |                       |
| System.Collections.CtorDefaultSize<String>.HashSet                                                   |      1.15 |            20.28 |            17.57 |                       |
| PerfLabTests.BlockCopyPerf.CallBlockCopy(numElements: 1000)                                          |      1.15 |            18.43 |            16.00 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.FooObjIsDescendant                                             |      1.15 |        608606.18 |        528896.74 |                       |
| System.Collections.IterateForEach<String>.HashSet(Size: 512)                                         |      1.15 |          2767.20 |          2406.88 |                       |
| System.Memory.Span<Char>.Clear(Size: 512)                                                            |      1.14 |            11.11 |             9.74 |                       |
| System.Collections.IterateForEach<Int32>.ImmutableQueue(Size: 512)                                   |      1.14 |          4151.92 |          3642.74 |                       |
| MicroBenchmarks.Serializers.Xml_ToStream<XmlElement>.XmlSerializer_                                  |      1.14 |          1731.26 |          1520.11 |                       |
| Benchstone.BenchI.Ackermann.Test                                                                     |      1.14 |          3982.75 |          3502.19 |                       |
| System.Memory.Span<Int32>.Clear(Size: 512)                                                           |      1.14 |            21.10 |            18.56 |                       |
| System.Memory.Span<Byte>.ToArray(Size: 512)                                                          |      1.13 |            51.04 |            45.23 |                       |
| System.Memory.ReadOnlySpan.IndexOfString(input: "foobardzsdzs", value: "rddzs", comparisonType: Inva |      1.13 |            80.54 |            71.50 |                       |
| PerfLabTests.LowLevelPerf.TypeReflectionObjectGetType                                                |      1.13 |        226536.28 |        201337.69 |                       |
| System.Tests.Perf_String.ToUpper(s: "TEST")                                                          |      1.12 |            30.35 |            27.05 |                       |
| System.Tests.Perf_Int64.Parse(value: "12345")                                                        |      1.12 |            85.60 |            76.32 |                       |
| System.Collections.CtorFromCollection<String>.ConcurrentDictionary(Size: 512)                        |      1.12 |        158699.77 |        141632.99 |                       |
| System.Text.Tests.Perf_Encoding.GetEncoder(size: 512, encName: "ascii")                              |      1.12 |            10.87 |             9.71 |                       |
| System.Text.Tests.Perf_Encoding.GetEncoder(size: 512, encName: "utf-8")                              |      1.12 |            10.93 |             9.77 |                       |
| System.Collections.TryAddGiventSize<String>.ConcurrentDictionary(Count: 512)                         |      1.12 |         93533.00 |         83600.69 |                       |
| XmlDocumentTests.XmlNodeListTests.Perf_XmlNodeList.GetCount                                          |      1.11 |            16.00 |            14.37 |                       |
| System.IO.Tests.Perf_Path.GetFileName                                                                |      1.11 |            68.62 |            61.72 |                       |

**Comment by adamsitnik** [comment]
## macOS 10.13.6 x64 MacBook Pro

macOS High Sierra 10.13.6 (17G65) [Darwin 17.7.0]
Intel Core i7-5557U CPU 3.10GHz (Broadwell)
BenchmarkDotNet 0.11.3.886-nightly
base: .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02)
diff: .NET Core 2.2.0 (CoreCLR 4.6.27110.04, CoreFX 4.6.27110.04)

| Slower                                                                                               | diff/base | Base Median (ns) | Diff Median (ns) | Modality|
| ---------------------------------------------------------------------------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| PerfLabTests.BlockCopyPerf.CallBlockCopy(numElements: 100)                                           |      1.60 |             9.22 |            14.76 |         |
| System.Tests.Perf_String.Trim_CharArr(s: "Test", c: [' ', ' '])                                      |      1.41 |             6.18 |             8.72 |         |
| System.Collections.AddGivenSize<String>.HashSet(Size: 512)                                           |      1.34 |         26884.73 |         36023.49 |         |
| System.Tests.Perf_String.TrimStart_CharArr(s: "Test", c: [' ', ' '])                                 |      1.31 |             5.26 |             6.86 |         |
| System.Collections.Remove<Int32>.LinkedList(Size: 512)                                               |      1.26 |          6627.86 |          8361.80 |         |
| System.Collections.ContainsTrue<String>.Array(Size: 512)                                             |      1.25 |        457193.13 |        569259.01 |         |
| System.Collections.AddDefaultSize<String>.HashSet(Count: 512)                                        |      1.23 |         34303.63 |         42303.68 |         |
| System.Tests.Perf_String.PadLeft(n: 18)                                                              |      1.23 |            19.24 |            23.60 |         |
| System.Collections.ContainsFalse<String>.Array(Size: 512)                                            |      1.22 |        903160.89 |       1105794.22 |         |
| System.Tests.Perf_String.TrimEnd_CharArr(s: "Test", c: [' ', ' '])                                   |      1.21 |             5.49 |             6.63 |         |
| System.Collections.IterateForEach<Int32>.LinkedList(Size: 512)                                       |      1.21 |          2147.11 |          2593.48 |         |
| System.Collections.IterateForEach<Int32>.ImmutableStack(Size: 512)                                   |      1.19 |          4148.35 |          4916.46 |         |
| System.Tests.Perf_String.IndexerCheckPathLength                                                      |      1.16 |           131.95 |           152.62 |         |
| System.Collections.IterateFor<Int32>.ImmutableSortedSet(Size: 512)                                   |      1.15 |         10538.73 |         12150.65 |         |
| System.Tests.Perf_String.Split(s: "ABCDEFGHIJKLMNOPQRSTUVWXYZ", arr: [' '], options: RemoveEmptyEntr |      1.15 |            53.04 |            60.81 |         |
| System.Tests.Perf_String.Trim_CharArr(s: " Te st  ", c: [' ', ' '])                                  |      1.14 |            19.79 |            22.58 |         |
| System.Collections.Remove<Int32>.ConcurrentBag(Size: 512)                                            |      1.14 |         14150.20 |         16130.23 |         |
| MicroBenchmarks.Serializers.Json_ToString<LoginViewModel>.JsonNet_                                   |      1.13 |          1024.52 |          1162.35 |         |
| PerfLabTests.LowLevelPerf.TypeReflectionArrayGetType                                                 |      1.13 |        235416.45 |        264849.59 |         |
| System.Tests.Perf_Int32.Parse(value: "-2147483648")                                                  |      1.12 |           110.69 |           124.16 |         |

| Faster                                                                                     | base/diff | Base Median (ns) | Diff Median (ns) | Modality              |
| ------------------------------------------------------------------------------------------ | ---------:| ----------------:| ----------------:| ---------------------- |
| System.Collections.Clear<String>.List(Size: 512)                                           |      1.50 |           475.61 |           317.54 | can have several modes|
| System.Memory.Span<Char>.EndsWith(Size: 512)                                               |      1.40 |            23.89 |            17.03 |                       |
| System.Collections.IterateForEach<String>.ConcurrentDictionary(Size: 512)                  |      1.31 |         32192.90 |         24573.18 |                       |
| System.Tests.Perf_Array.ArrayCopy3D                                                        |      1.31 |           372.71 |           284.73 |                       |
| System.Tests.Perf_String.TrimEnd(s: "Test")                                                |      1.29 |             6.19 |             4.79 |                       |
| System.IO.MemoryMappedFiles.Tests.Perf_MemoryMappedFile.CreateFromFile(capacity: 10000000) |      1.24 |        176815.16 |        142338.71 |                       |
| System.Memory.Span<Char>.LastIndexOfValue(Size: 512)                                       |      1.21 |            27.22 |            22.50 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.IFooObjIsIFoo                                        |      1.20 |       1030250.82 |        859290.01 |                       |
| SeekUnroll.Test(boxedIndex: 3)                                                             |      1.20 |    2657032251.00 |    2220589998.00 |                       |
| PerfLabTests.CastingPerf2.CastingPerf.IFooObjIsDescendantOfIFoo                            |      1.20 |       1029828.35 |        860882.13 |                       |
| SeekUnroll.Test(boxedIndex: 1)                                                             |      1.19 |    2657148998.50 |    2223774490.00 |                       |
| SeekUnroll.Test(boxedIndex: 11)                                                            |      1.19 |    2453818595.00 |    2064674343.00 |                       |
| System.Collections.ContainsFalse<Int32>.HashSet(Size: 512)                                 |      1.18 |          7320.35 |          6179.89 |                       |
| Functions.MathTests.SinhSingleBenchmark                                                    |      1.18 |         32890.05 |         27855.95 |                       |
| System.Collections.ContainsKeyFalse<Int32, Int32>.Dictionary(Size: 512)                    |      1.18 |          4388.64 |          3722.53 |                       |
| System.Memory.Span<Byte>.LastIndexOfValue(Size: 512)                                       |      1.18 |            20.81 |            17.68 |                       |
| System.Threading.Tasks.ValueTaskPerfTest.Copy_PassAsArgumentAndReturn_FromResult           |      1.17 |            25.39 |            21.66 |                       |
| System.Threading.Tasks.ValueTaskPerfTest.Copy_PassAsArgumentAndReturn_FromTask             |      1.16 |            27.15 |            23.44 |                       |
| PerfLabTests.BlockCopyPerf.CallBlockCopy(numElements: 10)                                  |      1.16 |             7.68 |             6.65 |                       |
| System.Collections.Remove<String>.LinkedList(Size: 512)                                    |      1.15 |         15836.06 |         13726.43 |                       |
| Benchstone.BenchI.Permutate.Test                                                           |      1.15 |     862684807.50 |     747822615.00 |                       |
| System.Perf_Convert.GetTypeCode                                                            |      1.15 |            10.31 |             8.95 |                       |
| System.Globalization.Tests.Perf_CultureInfo.GetCurrentCulture                              |      1.14 |             9.03 |             7.89 |                       |
| Benchstone.BenchI.Ackermann.Test                                                           |      1.14 |          4687.92 |          4104.95 |                       |
| System.Collections.AddGivenSize<Int32>.Dictionary(Size: 512)                               |      1.13 |          9049.80 |          7990.51 |                       |
| System.IO.Tests.Perf_FileStream.ReadByte(BufferSize: 512, TotalSize: 200000)               |      1.13 |       1126631.26 |        998725.58 |                       |
| PerfLabTests.LowLevelPerf.TypeReflectionObjectGetType                                      |      1.12 |        264830.39 |        235413.78 |                       |
| Benchstone.BenchF.Simpsn.Test                                                              |      1.12 |     166082870.00 |     148617704.50 |                       |
| System.IO.Tests.Perf_FileStream.ReadByte(BufferSize: 200000, TotalSize: 200000)            |      1.12 |       1118211.45 |       1001192.44 |                       |
| System.Collections.AddDefaultSize<String>.SortedList(Count: 512)                           |      1.11 |        764247.23 |        686386.12 |                       |

**Comment by danmosemsft** [comment]
`System.Collections.ContainsKeyFalse<Int32, Int32>.Dictionary(Size: 512)` (eg) appears in both faster and slower. Can you clarify ?

**Comment by adamsitnik** [comment]
> System.Collections.ContainsKeyFalse<Int32, Int32>.Dictionary(Size: 512) (eg) appears in both faster and slower. Can you clarify ?

@danmosemsft this benchmark is not stable. I guess that it's dependent on array or loop alignment. I need to to a research about the alignment issues.

**Comment by danmosemsft** [comment]
@adamsitnik I guess most of these must be either noise, alignment or tiered jitting, given there were of course very few changes made in 2.2 corefx/coreclr that were not serviced into 2.1. Would it be interesting to repeat the 2.1->2.2 analysis with tiered jitting disabled? Then if the system is working well, I would expect just about zero regressions/improvements.

The 2.2->3.0 report will be much more interesting...

**Comment by danmosemsft** [comment]
Another thing that might be interesting is to see what it looks like with the OS aggregated. I did a crude comparison of the regressions above by sort and diff and found only a very few of the rows appear in all the OS. In general most (?) times we regress something, it regresses for all OS. So it could be useful interesting check.

**Comment by adamsitnik** [comment]
I am closing this issue since we did not find any significant regressions. There was some noise, but having 20-30 noisy benchmarks in a portfolio of 2000 benchmarks is quite a good result ;)

@danmosemsft let's talk about the other comparisons we need during our next 1:1
