### ISSUE TITLE
How does the Performance Lab work?

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/performance#1971]
The Performance Lab (https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/TestHistoryIndexIndex.html)
Looks super interesting and useful, but I can't seem to make out how it works. Seems like the scripts in this repo do the collection and uploading of data, but it seems like the backing infrastructure (a queue + blob storage? What handles the messages?) is private.

I'd love to have a performance lab of my/our own like this.

(cc @AndyAyersMS)

**Comment by AndyAyersMS** [comment]
cc @DrewScoggins @Lxiamail

**Comment by billwert** [comment]
Hello @HurricanKai!

Indeed a lot of the infrastructure that runs this isn't public right now. It's a bunch of Azure services (table storage, queues, functions, blob storage, and batch) that back it. We simply haven't prioritized moving the code from our internal repos to GitHub yet. We plan to do so, but it's lower on our priority list. As we move into vNext we will re-evaluate this.

That said, a large part of why we have the system we have is scale. We run several thousand benchmarks across several OSes/architectures many times a day. Unless you're trying to do something similar, I would recommend using Benchmark.NET and pulling its output files into something like PowerBI or Excel. What we've got is a lot of overkill. :)

If you just wanted to use our graph format etc, if you look at the source of the HTML you linked you'll see we bake all the data right into the file. There's no server side of the renderer. You could imagine just generating that file directly from the BDN results as well.

Thanks!
-Bill

**Comment by billwert** [comment]
That makes a lot of sense. We've had one other ask for this in the past. I'll see how we can get something like this into our planning for the future. Thanks for asking!
