### ISSUE TITLE
Combine requested scenarios into one table?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/performance#200]
If I request more than one scenario eg with a pattern, then I get one JSON (or MD, etc) file per scenario. If they were in a single file, it would be easier to share data.

For example if I was working with the implementation of Dictionary, I might run `-f System.Collections.*.Dictionary* ` which runs about 30 tests and creates 30 markdown files. If I want to share the data then I have to manually create a single table, or paste all the tables into one place.

(Another scenario, in the absence of https://github.com/dotnet/performance/issues/199, if I want to eyeball diffs, this means I have to eyeball diffs of 30 files)

There could well be a way to create a single table, that I'm not seeing.

Opening in this repo as how we organize this repo may be relevant?

@adamsitnik

**Comment by adamsitnik** [comment]
To print a single summary table and export results to one file you need to use:

```cmd
--join
```

It's mentioned in [docs](https://github.com/dotnet/performance/tree/master/src/benchmarks/micro#filtering):

> Note: To print a single summary for all of the benchmarks, use --join. Example: dotnet run -c Release -f netcoreapp2.1 -- --join -f BenchmarksGame* - will run all of the benchmarks from BenchmarksGame namespace and print a single summary.

**Comment by danmosemsft** [comment]
Thank you...missed that in the docs.
