### ISSUE TITLE
dotnet-performance release/3.1.4xx pipeline fails for cannot snap-exec: cannot exec "/snap/dotnet-sdk/137/snap/command-chain/snapcraft-runner": permission denied

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#2003]
dotnet-performance job [ubuntu 1804 x64 scenarios release/3.1.4xx](https://dev.azure.com/dnceng/internal/_build/results?buildId=1354829&view=logs&j=af9039db-3a09-5652-d42f-cc95d30eed70)  fails for cannot snap-exec: [cannot exec "/snap/dotnet-sdk/137/snap/command-chain/snapcraft-runner": permission denied](https://dev.azure.com/dnceng/internal/_build/results?buildId=1354829&view=logs&j=af9039db-3a09-5652-d42f-cc95d30eed70&t=6c7bba33-6b7e-5a1e-47e8-024cc8538e18&l=63). Looks like helix environment issue. Followed up with first responders, [here](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1631306358620?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1631306358620&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1631306358620) is their feedback in Teams. Capture the feedback below as well:

I think the problem is that you really want to constrain your helix work item to live in paths under HELIX_WORKITEM_ROOT.  The path it's erroring on (cannot snap-exec: cannot exec "/snap/dotnet-sdk/137/snap/command-chain/snapcraft-runner": permission denied)  is likely touched by all sorts of work items. 

- Constraining yourself to using files under $HELIX_WORKITEM_ROOT may be a bit of work, but it's then cleaned up every work item, and these perf machines don't get cleaned up much.
- The user these work items runs as  can password-less sudo anything it needs; so if you're already ignoring the above rule, any sort of permission problems can be overcome directly in your scripts.

**Comment by billwert** [comment]
This issue is due to bad machine state. We should do these things:
1) Get PERFTIGER190 cleaned up (pending FR confirming they don't depend on the dotnet install in the snap cache. I suspect they do not.) 
2) Change our scripts to _prepend_ our path to the path variable instead of _append_. I've opened #2011 to track this fix.

**Comment by billwert** [comment]
PERFTIGER190 has been repaired so this should stop happening. We'll get to the other issue at some point but in the mean time I'm closing this.
