### ISSUE TITLE
Change scripts to prepend dotnet location to path instead of append

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#2011]
A transient lab failure was being caused by a badly configured machine having an ambient dotnet SDK installed. While that shouldn't happen, we can defend against this generally by ensuring we always prepend dotnet to the path when we add it from our payload instead of append it to the end. I don't have the full list of scripts we do this in, but it should just be either our python or yml files.

Reminder that we need to fix this in all the main and release branches across dotnet/performance and dotnet/runtime probably.

**Comment by Tohron** [comment]
I'm currently not seeing anywhere in the performance repo where the dotnet path is still appended.  If this problem crops up again, it can be looked into, but for now, closing...
