### ISSUE TITLE
How to access latest Alpine results?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#2015]
While working on the last manual perf run for .NET 6 I wanted to use the historical results for Alpine to verify one potential regression.

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/TestHistoryIndexIndex.html points to https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_alpine%203.12/AllTestindex.html

When I open any of the benchmarks, there are no new results since March:

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_alpine%203.12%2fBurgers.Test0.html

![image](https://user-images.githubusercontent.com/6011991/133411549-3ef54c6c-b20c-470c-86c4-1ecbc1cf8b75.png)

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_alpine%203.12%2fSystem.IO.Tests.Perf_FileStream.LockUnlock(fileSize%3a%201024%2c%20options%3a%20Asynchronous).html

![image](https://user-images.githubusercontent.com/6011991/133411611-f8fd6763-4a5f-4328-9da6-01dd4efacecd.png)

@DrewScoggins @billwert @Lxiamail Am I using wrong links?

**Comment by DrewScoggins** [comment]
We also discovered this yesterday in the triage meeting. You are not using the wrong links, and we have all of the data, but somehow the job for updating that page never made it in to our regular rotation. I have corrected this and starting today going forward this will be updated as normal.

**Comment by adamsitnik** [comment]
Charts are now up-to-date, thank you @DrewScoggins !
