### ISSUE TITLE
dotnet-performance ubuntu 1804 x64 sdk_scenarios release/5.0.1xx sporadically failed for timeout 

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/performance#2022]
Failure example: https://dev.azure.com/dnceng/public/_build/results?buildId=1365336&view=logs&j=af1f0234-87a7-53ba-84a4-00c026bb26d9&t=9acd9a6d-e373-5e8b-ded6-7a4171c2600a&l=68. Maybe increasing timeout?

**Comment by LoopedBard3** [comment]
Log has been purged, sdk_scenarios are mostly working on main and release/6.0, and release/5.0 is no longer supported.
