### ISSUE TITLE
How to run micro benchmarks

### ISSUE THREAD

**Issue by sandreenko** [dotnet/performance#205]
Hello, I have tried to follow the readme but hit some issues:
`PS C:\Projects\performance\src\benchmarks> dotnet run -c Release -f netcoreapp2.0` showed me:
`Couldn't find a project to run. Ensure a project exists in F:\git\performance\src\benchmarks, or pass the path to the project using --project.`

so I moved to `micro` and then I got:
```
F:\git\performance\src\benchmarks\micro> dotnet run -c Release -f netcoreapp2.0
C:\Program Files\dotnet\sdk\2.2.100-preview2-009404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [F:\git\performance\src\benchmarks\micro\MicroBenchmarks.csproj]

The build failed. Please fix the build errors and run again.
```

the same result for `-f netcoreapp2.2, 3.0 etc`,

I have 2.1, 2.2 .Net Core runtimes installed, this happens on Windows x64.

Could somebody please show how to fix that and update readme?

**Comment by adamsitnik** [comment]
@sandreenko sure!

This [document](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow.md#build) describes how to build the micro benchmarks.

Please let me know if the doc is enough to get it running or not.

**Comment by sandreenko** [comment]
Thank you, now it works.

**Comment by adamsitnik** [comment]
@sandreenko thanks! please let me know if you run into any other issues
