### ISSUE TITLE
Unoptimal code in Benchstone.BenchF.InProd.Test

### ISSUE THREAD

**Issue by alexcovington** [dotnet/performance#2063]
I've found a function in `Benchstone.BenchF.InProd.Test` that is slow because of how it was written, not necessarily because of an issue in the runtime. Wasn't sure if this was intentional or not, opening this issue just in case.

In `Benchstone.BenchF.InProd.Test`, the function `InProd.InnerProduct` uses an out parameter as an accumulator within a loop, which is slow:

```c#
private static void InnerProduct(out double result, double[][] a, double[][] b, int row, int col)
{
    result = 0.0;
    for (int i = 1; i < RowSize; i++)
    {
        accumulator = accumulator + a[row][i] * b[i][col];
    }
}
```

When I rewrite the benchmark to use a local variable as the accumulator instead, I see a performance increase:

```c#
private static void InnerProduct(out double result, double[][] a, double[][] b, int row, int col)
{
    double accumulator = 0.0;
    for (int i = 1; i < RowSize; i++)
    {
        accumulator = accumulator + a[row][i] * b[i][col];
    }
    result = accumulator;
}
```

```
PS C:\Users\acovingt\source\repos\performance\src\tools\ResultsComparer> dotnet run -- --base C:\Users\acovingt\Documents\inprod-before\ --diff C:\Users\acovingt\Documents\inprod-after\ --threshold 1%
summary:
better: 1, geomean: 1.637
total diff: 1

No Slower results for the provided threshold = 1% and noise filter = 0.3ns.

| Faster                        | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| ----------------------------- | ---------:| ----------------:| ----------------:| --------:|
| Benchstone.BenchF.InProd.Test |      1.64 |    1559538150.00 |     952688800.00 |         |
```

Would it be possible to update the benchmark to use a local accumulator instead of the out parameter? I understand this changes the benchmark's baseline, so I wanted to ask before submitting a PR.

**Comment by adamsitnik** [comment]
> I understand this changes the benchmark's baseline

We usually don't do that, as as you wrote it would affect the baseline:

https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md#Benchmarks-are-Immutable

The only exception are benchmarks that are used to compare .NET vs other frameworks like https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html 

@AndyAyersMS Is `Benchstone.BenchF.InProd` used to compare .NET against other platforms? AFAIR it's not and we should not update it?
