### ISSUE TITLE
Upload failures don't fail pipeline

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2089]
Upload failures in the performance and runtime perf pipelines did not cause the pipelines to register as failed. These failures should register a failure so we don't miss uploading data without knowing it isn't being uploaded.

**Comment by Tohron** [comment]
@LoopedBard3 could you link to some of the pipeline runs where this occurred?

**Comment by LoopedBard3** [comment]
@Tohron DM'd you some specific instances, but any runs around October 17-19th that upload data should demonstrate the same problem, at least in the runtime perf.

**Comment by Tohron** [comment]
https://github.com/dotnet/performance/pull/2117 merged
