### ISSUE TITLE
[Main] Blazor Scenarios are failing due to 'MSBUILD : error : Only item types may be referenced when removing with MatchOnMetadata.'

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2107]
Blazor Scenarios are failing due to 'MSBUILD : error : Only item types may be referenced when removing with MatchOnMetadata.' There is already an issue tracking this at dotnet/msbuild#6985. The specific scenarios failing at the moment are SOD min publish, SOD min publish AOT, and SOD blazor publish AOT.

**Comment by DrewScoggins** [comment]
Closing this due to https://github.com/dotnet/msbuild/pull/6995
