### ISSUE TITLE
Add .NET7 version/label and .NET6 baseline to WASM SOD scenarios

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/performance#2135]
In https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0, we need to add a new .NET7.0 label/version which is tracking mainline builds, and add a baseline with last .NET6 GA run results for all the scenarios/combinations. (very similar to what we did for .NET 5 to .NET6 switch

cc @DrewScoggins

**Comment by Tohron** [comment]
Updates have now been published:
https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/reports/092689d6-ee54-4bca-b231-1fa7babbf52f/ReportSection360fa7af341c1831b001

A potential issue with the results for SOD Pizza App Publish is being investigated in https://github.com/dotnet/performance/issues/2211

**Comment by SamMonoRT** [comment]
@Tohron @DrewScoggins  -- thanks for adding the .NET7 labels. For clarity and easy reading, I suggest the following two changes : 
1. Display only the 7.0 and .NET6.0 baseline as Defaults (as opposed to 3.1 and 5.0 done today), and keep all others optional behind a checkbox.
2. We also need to update the https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/dashboards/9cbc4a67-3950-4eda-b0cb-9c2daac3e48d dashboard to display the same changes.

I'll re-open this issue to track this

**Comment by SamMonoRT** [comment]
@Tohron @DrewScoggins - interestingly I can't seem to reopen the issue on my end - one of you please do the needful to open this issue again

**Comment by Tohron** [comment]
The https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/dashboards/9cbc4a67-3950-4eda-b0cb-9c2daac3e48d dashboard has now been updated properly.
