### ISSUE TITLE
"Is Missing" for all the daily runs

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#2165]
When I look at the daily runs here: https://pvscmdupload.blob.core.windows.net/index/index/index.html# for every category I see "<whatever category> is missing". I am not sure if this is related to some existing issue or not.

**Comment by naricc** [comment]
@DrewScoggins Any idea what is up with this?

**Comment by LoopedBard3** [comment]
@naricc Looking into this as @DrewScoggins if OOF. So far, it looks like the error is:
```
Error:
  An assembly specified in the application dependencies manifest (perfcommandcore.deps.json) was not found:
    package: 'LibGit2Sharp.NativeBinaries', version: '2.0.306'
    path: 'runtimes/win-x64/native/git2-106a5f2.pdb'
```

I will make sure to ping with any updates I have.

**Comment by LoopedBard3** [comment]
Minor update @naricc, I have spent a bit of time trying to debug this, but building and running locally does not produce any errors. Unfortunately, I am not sure where to continue debugging as there have not been any recent changes to the index generator. Drew is OOF at the moment but mentioned he may check-in a few times and will hopefully be able to provide insight for me.

**Comment by LoopedBard3** [comment]
@naricc Issue is fixed and data is showing up in the index. Let me know if you see anything missing.
