### ISSUE TITLE
Update docs to net7.0

### ISSUE THREAD

**Issue by danmoseley** [dotnet/performance#2247]
Our markdowns in this repo generally refer to net6.0 and to comparing net5.0 to net6.0.

Presumably we should update all these now to net7.0 and net6.0 to net7.0. @adamsitnik do you know any reason why not to? If so I will do it.

**Comment by adamsitnik** [comment]
> do you know any reason why not to?

I don't. It would be a very welcomed improvement ;)

**Comment by danmoseley** [comment]
#2251
