### ISSUE TITLE
Maui Install Broken

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2292]
With the recent bump of the Maui version to using dotnet sdk 6.0.300 from 6.0.200, the maui install step of the dotnet-runtime-perf pipeline has been broken. Part of the issue is that not all dependencies have been updated to the new SDK and the installer doesn't play well with that. An issue pertaining to this is being tracked: https://github.com/dotnet/sdk/issues/23402.

The end fix should be to just update the SDK we use to 6.0.300, but that will only work once all dependencies have builds for that.

**Comment by naricc** [comment]
This is also currently blocking timing/size for the dotnet-podcast app.

**Comment by LoopedBard3** [comment]
Mitigated: https://github.com/dotnet/maui/pull/5112
