### ISSUE TITLE
ResultsComparer: Unable to find package Sharp Compress with version (>= 0.31.0)

### ISSUE THREAD

**Issue by L2** [dotnet/performance#2396]
I believe it's related to the recent update with resultsComparer (https://github.com/dotnet/performance/pull/2372)

```
error NU1102: Unable to find package SharpCompress with version (>= 0.31.0)
error NU1102:   - Found 63 version(s) in dotnet-public [ Nearest version: 0.30.0 ]
error NU1102:   - Found 0 version(s) in benchmark-dotnet-prerelease
...etc
```

Tried clearing the .nuget cache folder as well, but still see the same error (Win10 x64). If I change the SharpCompress version to 0.30.0 in `ResultsComparer.csproj`, things work fine.

Thanks!

**Comment by LoopedBard3** [comment]
Thank you for submitting this issue! SharpCompress version 0.31.0 should now be found in the feeds so I am going to close the issue. If you are still experiencing this problem feel free to comment or open another issue.
