### ISSUE TITLE
Python 3.6 Deprecation warning

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2403]
We are getting the warning: 
```
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
```

We should get ahead of this.

**Comment by LoopedBard3** [comment]
This warning came from job wasmaot.x64.micro.net7.0.Partition1

**Comment by Funnear** [comment]
`/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.utils import int_from_bytes
`

**Comment by LoopedBard3** [comment]
Issue appears to be gone due to python version update, closing.
