### ISSUE TITLE
[Question] Cancel dotnet-dump command in Input/Output RedirectedMode

### ISSUE THREAD

**Issue by En3Tho** [dotnet/performance#2440]
Hey, I did not find a discussion section here so I'm posting this as an issue.

I've written a small viewer for dotnet-dump for powershell: https://github.com/En3Tho/PoshDotnetDumpAnalyzeViewer because I needed something to investigate our linux dumps. WinDbg did not seem to like it, DotMemory is cool but it processed our 5gb dump for 40 minutes... And vanilla dotnet-dump is not too comfortable to work with (for me at least).

I want to make cancellation support. What sequence should I pass to dotnet-dump process to make it cancel current command exectuion? Is it possible at all?

Sorry if I missed it somewhere in the code.

@mikem8361 if you still remember the code of dotnet-dump then please help :)

**Comment by mikem8361** [comment]
The only thing I can think of is to send an CTRL-C to stdin during a command.  That should cancel most commands.  There is no way to cancel the actual load of a large dump currently.  You could just kill the dotnet-dump process for that case and relaunch. 

dotnet-dump analyze wasn't really meant to be scriptable. May be someday.  You could just host the SOS infrastructure your self like dotnet-dump or SOS.Extensions does under lldb/windbg instead of text output scraping.  But the interfaces and code can change at any time; the interfaces are really public yet.

**Comment by En3Tho** [comment]
@mikem8361, Thanks. I've tried to send it but seems I falied to do so. But at least now I know i'm on the right path. I hope it will work. :)

As for wrapping dotnet-dump: I specifically did it to make things simpler, not bundle sos for every os out there and so on. Also, I'm not even trying to support all of dotnet-dump capabilities, simply a more convinient output for analyze.

Making this an uber full fledged app will most probably require build my own WinDbg and this is sorta impossible goal.

**Comment by En3Tho** [comment]
Seems like it doesn't work. :(
Thank you anyway!

**Comment by mikem8361** [comment]
I just realized why it isn't work: the console repl code (in Microsoft.Diagnostics.Repl) doesn't handle ctrl-c/ctrl-break when the input has been redirected.  See:

https://github.com/dotnet/diagnostics/blob/b02bc8470a1797fbff2acf137efe42e513ececba/src/Microsoft.Diagnostics.Repl/ConsoleService.cs#L91

and

https://github.com/dotnet/diagnostics/blob/b02bc8470a1797fbff2acf137efe42e513ececba/src/Microsoft.Diagnostics.Repl/ConsoleService.cs#L238

**Comment by mikem8361** [comment]
Not sure what we can do about that.

**Comment by En3Tho** [comment]
Yeah. I saw that code and couldn't find a way. This is why I've created this issue/question. Well, this is not that important I guess. Just a smallish feature I would like to implement in some or the other way. Thank you for making those tools, they are awesome.
