### ISSUE TITLE
GC benchmarks setup fails on Windows 11

### ISSUE THREAD

**Issue by L2** [dotnet/performance#2444]
On Windows 11, the following gc benchmarks setup step seems to fail (doesn't fail on Windows 10):

```
cd path\to\performance\src\benchmarks\gc
python . setup
```

The root cause looks to be a call to `performance\src\benchmarks\gc\src\exec\env\out\Release\get_host_info.exe` which gives a different sort of output only on Windows 11:
```
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
Invalid relationship 7
numa_nodes:
  -
    numa_node_number: 0
    cpu_group_number: 0
    ranges:
      - { lo: 0, hi: 15 }
n_physical_processors: 8
n_logical_processors: 16
caches:
  l1: { n_caches: 16, total_bytes: 655360 }
  l2: { n_caches: 8, total_bytes: 4194304 }
  l3: { n_caches: 1, total_bytes: 16777216 }
```

Note the "**Invalid relationship 7**" text that's only produced on Windows 11 (those extra lines don't get printed out on Win10). This extra text seems to make the yaml parser fail later on.

That "**7**" refers to LOGICAL_PROCESSOR_RELATIONSHIP enum value of 7, which is **RelationProcessorModule** and looks to be undocumented (https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-logical_processor_relationship). The benchmark doesn't have a specific case to handle this relationship (falls into the default case) in get_host_info.cpp and prints these "Invalid relationship" lines as a result.

Wondering if the GC team has also run into this issue on Win11 and if there's a recommended way to correct this issue.

Thanks

**Comment by L2** [comment]
Friendly ping to see if there's any updates on this. Any chance you can take a look @Maoni0 @cshung ? Much appreciated.

**Comment by Maoni0** [comment]
@cshung can you please take a look?

**Comment by L2** [comment]
Friendly ping. Any word on the GC benchmarks working on Win11 on your end @Maoni0 @cshung ? Thanks!

**Comment by Maoni0** [comment]
hi @L2 so sorry it took so long, could you please check if the fix @mrsharm did allows the setup to continue for you? thanks!

**Comment by L2** [comment]
Thanks @Maoni0 and @mrsharm , much appreciated.

GC benchmarks setup now completes on Win11, however this change breaks the setup on Win10:
`case RelationProcessorModule:` : this enum value doesn't seem to exist on Windows 10 and so it fails to build `get_host_info.cpp`. Commenting that case out fixes it for now on Win10.

All GC benchmarks seem to be working on Win11 and Win10 except for low_memory_container. It crashes with an "Out of memory" exception (I'm using a runtime built from the latest `dotnet/runtime` changes as of today). I'll post a separate issue about this.

Thanks

**Comment by mrsharm** [comment]
Thanks for checking, @L2. I am going to work on a solution that's for both Windows 10 and 11 and should have a PR out for that soon as the solution is simply to gracefully break if ``info.Relationship == 7`` without casting it to a ``LOGICAL_PROCESSOR_RELATIONSHIP``. 

Additionally, will be assigning the OOM case for the low_memory_container to myself since I'll be now working on the GC infrastructure side of things. Please let me know if you run into any further issues. 

Thanks!
