### ISSUE TITLE
[Tracking] Consider using only "help wanted" instead of "up-for-grabs"

### ISSUE THREAD

**Issue by mairaw** [dotnet/performance#2577]
Using the **help wanted** label is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496
Your repo has the two: help wanted and up-for-grabs. Consider converting all the up-for-grabs issues into help wanted. Some people added up for grabs in the label description in other repos in case folks are looking for that label instead.

You should also consider adding the project to https://up-for-grabs.net/
See an example PR at https://github.com/up-for-grabs/up-for-grabs.net/pull/3329

/cc @danmoseley

**Comment by danmoseley** [comment]
@LoopedBard3 any objection to just renaming the label -- or is there tooling around it?

**Comment by danmoseley** [comment]
actually it looks like we already have it, so if you relable up-for-grabs stuff with help wanted, then delete up-for-grabs, you can close this.. https://github.com/dotnet/performance/labels

**Comment by LoopedBard3** [comment]
I don't have anything specific for an objection. Let me double check with @sblom

**Comment by sblom** [comment]
Yeah--that's fine.

**Comment by LoopedBard3** [comment]
All issues were updated (there were no PR's with up-for-grabs). Closing this issue.
