### ISSUE TITLE
Wrong number of regressions in the title of perf-autofiling-issues

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#2645]
Number of regressions in the title and in the comments don't match on [perf-autofiling-issues](https://github.com/dotnet/perf-autofiling-issues) repository. 

For example, https://github.com/dotnet/perf-autofiling-issues/issues/8715 has 14 regressions, but only 2 reported in the title.

**Comment by DrewScoggins** [comment]
This was part of an experiment. I tried combining issues across configurations, but had not gotten around to fixing the issue titles. We have since decided to pursue other options. Going forward this should no longer be an issue.
