### ISSUE TITLE
Autofiled issues generated with both MonoAOT=True and MonoAOT=False labels

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#2647]
I am seeing some autofiled issues like this one: https://github.com/dotnet/perf-autofiling-issues/issues/8834 show up with both MonoAOT=true and MonoAOT=false. I think the correct label is MonoAOT=false, in this case at least. But it makes it pretty confusing when trying to triage issue.

**Comment by LoopedBard3** [comment]
This is likely due to the same testing that caused https://github.com/dotnet/performance/issues/2645. This should be watched for a few more auto file runs then closed if it doesn't pop back up. As of right now it has not occurred for 14 days (based on label filterin)

**Comment by LoopedBard3** [comment]
This hasn't popped up in 23 days, closing this issue as it seems to have been caused by the same reason as #2645
