### ISSUE TITLE
No nuget.org entry in Nuget.config

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/performance#2673]
Is there any specific reason why we don't have an entry of `nuget.org` in `Nuget.Config`?

I was thinking of adding this as part of https://github.com/dotnet/performance/pull/2672.

<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />

@sblom @LoopedBard3 @adamsitnik @DrewScoggins

**Comment by LoopedBard3** [comment]
We currently exclude nuget.org to avoid the substitution attack risk that comes from using a mix of public and private feeds. However, if adding it in would be beneficial, we can look further into potential solutions.

**Comment by caaavik-msft** [comment]
The process for adding new nuget packages is to ask the first responders to add your exact package version to the one of the feeds that is in the nuget.config

**Comment by kunalspathak** [comment]
> to avoid the substitution attack risk

That's what I thought.

>  to ask the first responders

Will check. Thanks!

**Comment by LoopedBard3** [comment]
Closing this as answered. Feel free to reopen or make a new issue if there are any other questions. Thank you!
