### ISSUE TITLE
Redirect job send to runtime queues (.rt queues) to general use queue

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/performance#2684]
Hi team,

I am from dnceng (dotnet engineering services) team, and we realize that the dotnet/performance team is sending jobs to a runtime queue, the runtime queues are all the queues that ends with ".rt". This is the yaml in where this job in being send incorrect: https://github.com/dotnet/performance/blob/main/azure-pipelines.yml#L274

That queue is only for runtime use, the best thing to do is to send that job a non-runtime queue, in this case the best match would be **centos.7.amd64.open** (removing the .rt part) 

I would really appreciate if you can do this change.

Let me know if you have any question.

Thanks @LoopedBard3 for redirecting to the right place to report this.

**Comment by LoopedBard3** [comment]
cc: @caaavik-msft @sblom @cincuranet Future general guidance on not using .rt pipelines when we go at add them in the future. I will fix this quickly.
