### ISSUE TITLE
[Question] Why Helix SDK version did not get auto-updated by Maestro?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#269]
in #265 it turned out that we had an old version of Helix that had some bugs and did not allow us to push linux jobs to Helix

https://github.com/dotnet/arcade/issues/1274#issuecomment-462664482

@adiaaida do you know why Maestro did not auto-update the Helix SDK version? 

I have pushed a PR with the update #268 but I would like to understand why it happened. Is it by design? If so, why?

**Comment by adiaaida** [comment]
We need to add the Helix dependency to Versions.Details.xml. I'll get a PR out for that shortly.

**Comment by adamsitnik** [comment]
thanks!
