### ISSUE TITLE
Improve mono-dotnet creation versioning

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2733]
Currently, when using artifacts from the mono-dotnet task for micro_mono runs we have to manually change the product version in these lines to match the current product version being generated. An example PR: https://github.com/dotnet/runtime/pull/78413. It would be beneficial to change this so that the product version is automatically tied to the product version in eng/Version.props.
Branches that need this update:
- [x] main, https://github.com/dotnet/runtime/pull/78787
- [x] Release/7.0, https://github.com/dotnet/runtime/pull/78413
- [x] Release/6.0, https://github.com/dotnet/runtime/pull/78411

**Comment by cincuranet** [comment]
Maybe we can create a "dummy" `proj` file that will extract these values and puts them into variables, i.e. using _vso[task.setvariable_ or maybe even directly environment variables (not sure how these are handled between steps when dynamically created). In YAML we can then use these.

**Comment by LoopedBard3** [comment]
Found a potential solution using sed for bash systems to just grab the value from the props file, will have a test PR shortly.

**Comment by LoopedBard3** [comment]
Potential solution PR ^

**Comment by LoopedBard3** [comment]
Reopening for release/7.0 and release/6.0

**Comment by LoopedBard3** [comment]
Branches merged, closing.
