### ISSUE TITLE
Make repro recipes correct for Mono scenarios

### ISSUE THREAD

**Issue by sblom** [dotnet/performance#2734]
Example of incorrect repro recipe from https://github.com/dotnet/perf-autofiling-issues/issues/8714

![Image](https://user-images.githubusercontent.com/31878/201194427-1ead4d2c-eb71-4b72-a2d6-520548f756bf.png)

Stakeholders: @naricc

**Comment by naricc** [comment]
@radical @radekdoulik @kotlarmilos   If any one else has suggestions for how the repro directions can be improved, this is the place to discuss it.

**Comment by kotlarmilos** [comment]
Benchmark links in the tables don't work. Also, it could be beneficial to include different configurations for Mono (Interpreter & AOT) in the script.

**Comment by fanyang-mono** [comment]
I created a script to help me run microbenchmarks locally and folks on mono team have been using it for a while. We could start from there. There are multiple values hard-coded in the script. Improvement is needed to make it more robust. (https://github.com/fanyang-mono/myScripts/blob/main/buildMicrobenchmarks.sh)

**Comment by LoopedBard3** [comment]
The first version of this has been merged, feel free to reopen this or open new issues for improvements.
