### ISSUE TITLE
blazor-wasm size benchmarks reports displaying incorrectly

### ISSUE THREAD

**Issue by sblom** [dotnet/performance#2749]
Tracking issue for the blazor-wasm benchmark reporting issue that Sam reported.

/cc @SamMonoRT

**Comment by SamMonoRT** [comment]
Essentially, the last run shows an incorrect measurement in https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0?experience=power-bi   IT keeps moving day to day, and then previous run results show the correct value.

**Comment by LoopedBard3** [comment]
This should be fixed now. There during the update to include labeling for .NET 8, one of the cases was missed resulting in a data point from release/6.0 showing up as the latest in the .NET 8 data.
