### ISSUE TITLE
Real-world auto-filing issue missing benchmark report HTML/link

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#2765]
For example, this https://github.com/dotnet/perf-autofiling-issues/issues/10092 is missing correct HTML/link for i.e. _LinearAxisServo - Duration of single invocation_. The link there `https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/8.0_x64_ubuntu%2018.04_RunKind=bepuphysics/DemoBenchmarks.TwoBodyConstraintBenchmarks.LinearAxisServo.html` is currently 404.

/cc @kunalspathak

**Comment by sblom** [comment]
@cincuranet, Drew knows exactly how to fix. Please have him show you.

**Comment by kunalspathak** [comment]
Also, in the same issue, the historical graphs are missing that we should fix. @cincuranet  - how often are real world benchmarks run? I know that they are not run as frequently as microbenchmarks (which run on every few commits).

**Comment by cincuranet** [comment]
@kunalspathak These run every 12 hours.

**Comment by cincuranet** [comment]
This is now fixed. I'll wait for next run to confirm and close then.

**Comment by kunalspathak** [comment]
> This is now fixed. I'll wait for next run to double confirm and close then.

I believe https://github.com/dotnet/perf-autofiling-issues/issues/10512 was before your fix?

**Comment by cincuranet** [comment]
Correct, that was before the fix was deployed. 

Now, for example, https://github.com/dotnet/perf-autofiling-issues/issues/10562 is fresh. Both the graph and all test history is properly generated (links in previously created issues will start working as well).
