### ISSUE TITLE
Benchmarks fail to run on Arm64 with unavailable .Net 8.0 SDK error

### ISSUE THREAD

**Issue by SwapnilGaikwad** [dotnet/performance#2766]
Execution of benchmarks using the latest main (commit: `320528e6016f4c175ae4b6ad89431d3db3bf18da` ) of dotnet/runtime fails. Error states it cannot find .Net 8.0 SDK even when specified to use .Net 7.0.

**Prerequisite**:
Release build of dotnet/runtime, built with `./build.sh -lc Release -rc Release`

**Command to execute benchmark**
```
cd ~/dotnet/performance/src/benchmarks/micro
/home/dotnet/runtime/.dotnet/dotnet run -c Release -f net7.0 --filter System.Memory.Span*.Reverse --corerun /home/dotnet/runtime/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun --statisticalTest 2%
```

**Error**
```
/home/dotnet/runtime/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [/home/dotnet/performance/src/benchmarks/micro/MicroBenchmarks.csproj::TargetFramework=net8.0]
```

The commit `64447d616208422e669e35b1e8ae0bd1b74ce194` is the last successful commit with which benchmarks build and execute successfully.

Kindly let me know if there is any other information you need to debug this issue further.

**Comment by LoopedBard3** [comment]
Hello! When running with older SDKs, the newer net_.0 targets need to be removed from the <TargetFrameworks> in src/benchmarks/micro/MicroBenchmarks.csproj file, or set the environment variable 'PERFLAB_TARGET_FRAMEWORKS' to the target framework version (ex. net7.0). Let me know if there are still issues after trying this.

**Comment by SwapnilGaikwad** [comment]
Thanks @LoopedBard3 , both the options your suggested worked.
1. PERFLAB_TARGET_FRAMEWORKS=net7.0
or 
2. Just changed for the for non-Windows_NT targets.
```diff
--- a/src/benchmarks/micro/MicroBenchmarks.csproj
+++ b/src/benchmarks/micro/MicroBenchmarks.csproj
@@ -5,7 +5,7 @@
     <TargetFrameworks>$(PERFLAB_TARGET_FRAMEWORKS)</TargetFrameworks>
     <!-- Supported target frameworks -->
     <TargetFrameworks Condition="'$(TargetFrameworks)' == '' AND '$(OS)' == 'Windows_NT'">net462;netcoreapp3.1;net6.0;net7.0;net8.0</TargetFrameworks>
-    <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">netcoreapp3.1;net6.0;net7.0;net8.0</TargetFrameworks>
+    <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">netcoreapp3.1;net6.0;net7.0</TargetFrameworks>
```

However, the [main branch ](https://github.com/dotnet/runtime/blob/main/global.json#L3)of `dotnet/runtime` installs SDK 7.0 ( version 7.0.100 in `59d56cc05b791bfb477ffc44cbef362287bd1054`). 
Are you going to update the SDK version for the runtime repo as well? Otherwise, we can incorporate this workaround in our CI.
