### ISSUE TITLE
Why is LangVersion limited to 9.0?

### ISSUE THREAD

**Issue by stephentoub** [dotnet/performance#2776]
https://github.com/dotnet/performance/blob/def4ce245230bb9c71eb5832e7750d3f6eff6759/src/benchmarks/micro/MicroBenchmarks.csproj#L18

This prohibits testing features that require newer language versions.  Can this be increased to 11, or even to Preview?

(And it was only increased to 9.0 very recently.)

**Comment by cincuranet** [comment]
@adamsitnik are you maybe aware of some limitation of BDN that would require this? And if so, is it still valid?
