### ISSUE TITLE
Wasm AOT runs not autofiled

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2824]
It appears that the following check has not been auto-filing correctly: 
```
Specific Check: Tuesday Check
Run Labels: refs/heads/main, x64, Ubuntu1804, RunKind=micro, CompliationMode=wasm, AOT=true, WASM
and
Specific Check: Tuesday Check
Run Labels: refs/heads/main, x64, Ubuntu1804, RunKind=micro, CompliationMode=wasm, WASM
```

The run results are showing up in the tables. Investigating the autofile runs to see if they directly failed or if something else is going on.

**Comment by radical** [comment]
cc @lewing

**Comment by lewing** [comment]
I think this is because dotnet/performance is targeting net7.0 still and the workaround we used to make it use the net8 runtimes for wasm was disabled so the tests have just been targeting a stable build of the runtime

**Comment by lewing** [comment]
This without manual work this is going to leave us with a month long hole in the net8 runtime data for wasm across some fairly important changes.

**Comment by DrewScoggins** [comment]
I am doing testing on these changes as we speak. If everything works I will check in the change in the performance repo.



> I think this is because dotnet/performance is targeting net7.0 still and the workaround we used to make it use the net8 runtimes for wasm was disabled so the tests have just been targeting a stable build of the runtime

How many big changes and when did they go in? We could go back and run some builds around the major changes that happened so that we can go back and fill in with the correct data going forward.

**Comment by lewing** [comment]
@kg which jiterperter commits are most important to have data on?

**Comment by kg** [comment]
Before and after https://github.com/dotnet/runtime/pull/78493 would be a valuable diff to have.
https://github.com/dotnet/runtime/pull/79239 and https://github.com/dotnet/runtime/pull/80197 are also worth measuring the impact of

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/79302 would be nice

**Comment by lewing** [comment]
where is the `compliationmode" typo coming from in the labels now?

**Comment by DrewScoggins** [comment]
This came from a typo that I had about 4 years ago when I was first putting the lab together. Since then, we have never been able to fully purge it from the system, and because of the way that trends are correlated it is challenging to go back and fix old labels.

**Comment by LoopedBard3** [comment]
Fixed by: https://github.com/dotnet/performance/pull/2816
