### ISSUE TITLE
Single vs Multithreaded benchmarks 

### ISSUE THREAD

**Issue by shivanirmishra** [dotnet/performance#2826]
@adamsitnik Is there any way using which we can filter out multi-threaded benchmarks directly?

**Comment by adamsitnik** [comment]
@shivanirmishra the closest we can get is running all benchmarks except of the benchmarks that belong to `NoWASM` category. This category contains all benchmarks that are not supported on WASM, which are mostly multi-threaded benchmarks.

```cmd
--filter * --category-exclusion-filter NoWASM
```

**Comment by shivanirmishra** [comment]
Thank you @adamsitnik. Also "--filter *" is not working to run all the benchmarks.
It's giving errors like:
Please remember that the filter is applied to the full benchmark name: `namespace.typeName.methodName`.
	BilinearTest.Interpol_Scalar
	BilinearTest.Interpol_Vector
	Burgers.Test3
	Burgers.Test0
	Burgers.Test1
	Burgers.Test2
	ByteMark.BenchEmFloat
	ByteMark.BenchNumericSortJagged
	ByteMark.BenchNumericSortRectangular
	ByteMark.BenchStringSort
	ByteMark.BenchBitOps
	ByteMark.BenchEmFloatClass
	ByteMark.BenchFourier
	ByteMark.BenchAssignJagged
	ByteMark.BenchAssignRectangular
	ByteMark.BenchIDEAEncryption
	ByteMark.BenchNeuralJagged
	ByteMark.BenchNeural
	ByteMark.BenchLUDecomp
	CscBench.CompileTest
	CscBench.DatflowTest
	LinqBenchmarks.Where00LinqQueryX
	LinqBenchmarks.Where00LinqMethodX
	LinqBenchmarks.Where00ForX
	LinqBenchmarks.Where01LinqQueryX
	LinqBenchmarks.Where01LinqMethodX
	LinqBenchmarks.Where01LinqMethodNestedX
	LinqBenchmarks.Where01ForX
	LinqBenchmarks.Count00LinqMethodX
	LinqBenchmarks.Count00ForX
	LinqBenchmarks.Order00LinqQueryX
	LinqBenchmarks.Order00LinqMethodX
	LinqBenchmarks.Order00ManualX
	SeekUnroll.Test(boxedIndex: 1)
	SeekUnroll.Test(boxedIndex: 3)
	SeekUnroll.Test(boxedIndex: 11)
	SeekUnroll.Test(boxedIndex: 19)
	SeekUnroll.Test(boxedIndex: 27)
	Benchmark.GetChildKeysTests.AddChainedConfigurationNoDelimiter
	Benchmark.GetChildKeysTests.AddChainedConfigurationEmpty
To print all available benchmarks use `--list flat` or `--list tree`.
To learn more about filtering use `--help`.

**Comment by adamsitnik** [comment]
It works fine on my machine:

![image](https://user-images.githubusercontent.com/6011991/211799188-4d078e7d-f755-4e3d-9563-a954984b67de.png)

If you are using a Unix machine you need to escape the asterisk, otherwise every Unix shell will replace it with the list of files in current folder.

```cmd
--filter '*' --category-exclusion-filter NoWASM
```

**Comment by shivanirmishra** [comment]
Thank you @adamsitnik, It's working for me as well.
