### ISSUE TITLE
Pipeline has server errors near end of runs

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2830]
The send to Helix console logs are showing the following error near the end of the runs: 
```
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:63c5562f-601e-0068-7860-24bcb4000000
Time:2023-01-09T19:27:10.9865100Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:Signed expiry time [Sat, 07 Jan 2023 21:57:18 GMT] must be after signed start time [Mon, 09 Jan 2023 19:27:10 GMT]
```

This does not appear to be affecting the performance data uploads but needs to be fixed.

**Comment by cincuranet** [comment]
Based on `Signed expiry time [Sat, 07 Jan 2023 21:57:18 GMT] must be after signed start time [Mon, 09 Jan 2023 19:27:10 GMT]` is looks like SAS token is expired.

**Comment by LoopedBard3** [comment]
Fixed by https://github.com/dotnet/arcade/issues/12192

**Comment by LoopedBard3** [comment]
This appears to be fixed by the rollout.
