### ISSUE TITLE
Scenario `Device Startup - Desktop Maui Blazor Default` missing `PerfLabGenericEventSource` `Startup` event

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#2850]

**Comment by LoopedBard3** [comment]
When running on our public performance-ci for PR's, the Maui Blazor Default startup scenario fails with the startup event we inject not being found. Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=144992&view=logs&j=050b7e9c-7ebd-5fe4-f8cf-c328d6fe2e2d&t=3054d192-6043-59b5-d784-ba1cf9867b56. This is only impacting the runs for the public PR's and does not repro locally on the setups we have. @TanayParikh or @jonathanpeppers, are there potential aspects of Blazor Maui that would cause it to not send the events while normal Maui works properly?

**Comment by cincuranet** [comment]
I can confirm that the binary used in public CI, when run locally, produces the event. It's also not some kind of flushing issue, because running multiple iterations does not help either.

Also other custom events, like `Frame/Start` are produced fine.

Maybe @brianrob can point some stuff to check, from etw/etl perspective.

**Comment by jonathanpeppers** [comment]
So a plain MAUI app on Windows works, but MAUI+Blazor doesn't?

@TanayParikh is probably the best to know how that is setup. I think we added something so the web view's loading is included in the time?

**Comment by cincuranet** [comment]
Only MAUI+Blazor and only on public CI. Internal runs fine. And locally (with the binaries from public CI) it runs fine for me too.

**Comment by MackinnonBuck** [comment]
Hi all, @TanayParikh is in the process of handing off the Blazor perf work to me.

Do we know if the MAUI Blazor app is starting in CI at all? If the MAUI test is working but MAUI+Blazor isn't, maybe WebView2 isn't getting installed correctly on the CI machines? This might explain why it works locally.

Perhaps the logs for [/src/scenarios/mauiblazordesktop/pre.py](https://github.com/dotnet/performance/blob/main/src/scenarios/mauiblazordesktop/pre.py) would indicate whether the WebView2 setup is an issue, but I wasn't able to find the CI output for that log.

**Comment by cincuranet** [comment]
It says `WebView Found; pvvalue(version) 109.0.1518.61`. Full log [here](https://dev.azure.com/dnceng-public/public/_build/results?buildId=145994&view=logs&j=050b7e9c-7ebd-5fe4-f8cf-c328d6fe2e2d&t=efd5421e-5382-5c90-aabe-79f8479cea0a&l=435).

**Comment by cincuranet** [comment]
Ahh, I probably know what it is. The WebView is installed during build, not when the ap is executed. Fingers crossed.
