### ISSUE TITLE
Question: Is there an official publish location

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [dotnet/performance#2869]
Do you have a web-page for all benchmark resutls especially microbenchmarks for different dotnet versions?

**Comment by cincuranet** [comment]
There's [this](https://aka.ms/HistoryIndex), but that's numbers from, basically, `main`. We do collect data from, at the moment, `net6.0`, `net7.0` and `main`/`net8.0`, but AFAIK we don't have these as webpages.

**Comment by zahirtezcan-bugs** [comment]
Thank you, that is huge. Though looks like a page built for the developers, I mean effect of a commit on the performance of a scenario or a function. I guess this repository's whole purpose is for dotnet runtime developers.

I was looking for a page with multiple benchmarks, lets say on `System.Collections` namespace benchmarks all in one place; so that it will be easier to compare functionalities with each other.

**Comment by cincuranet** [comment]
The [_.NET 7.0 GA Microbenchmarks Performance Study Report_](https://github.com/dotnet/runtime/issues/79245) (and other editions of this report) might be something valuable for you. But nothing exactly like you described exists at the moment.
