### ISSUE TITLE
Question: How to run the benchmark with mono runtime on x86?

### ISSUE THREAD

**Issue by shivanirmishra** [dotnet/performance#2872]
We have built mono runtime on x86 using [https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md].
After the build completes, product binaries will be dropped in the artifacts\bin\mono\<OS>.<arch>.<flavor> folder so we got "linux.x64.Release" in "/runtime/artifacts/bin/mono/".
Also we found "dotnet" in "/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/dotnet" folder. 
But not sure how to use this **dotnet with mono runtime** to run this benchmark.

Also, building mono with WASM is mandatory or it can use the mono build without WASM?

**Comment by LoopedBard3** [comment]
Hello! The exact steps will depend on what kind of execution configuration you want to run the mono tests under, options include AOT, JIT, and Interpreter. For AOT, the steps to follow are available in the Expand Repro section of this issue: https://github.com/DrewScoggins/performance-2/issues/8427.
For JIT, the steps to follow are available in the Expand Repro section of this issue: https://github.com/DrewScoggins/performance-2/issues/8429.
For interpreter, follow the JIT instructions but add the environment variable MONO_ENV_OPTIONS="--interpreter" before running benchmarks_ci.py. `export MONO_ENV_OPTIONS="--interpreter"` on Linux.

The benchmark run instructions are semi-specific to running the Microbenchmarks located in this repository, but if you have a different project setup to use BenchmarkDotNet, the individual command instructions should act as a good starting point.

Please tag me if you have any other questions!
