### ISSUE TITLE
Fix job title in jenkins jobs

### ISSUE THREAD

**Issue by adiaaida** [dotnet/performance#289]
I don't know how much of a priority this is, as we are enabling the SAS token in the AzDO jobs, but, at the moment, Jenkins is uploading to benchview with titles such as "${benchviewCommitNamePrefix} %GIT_BRANCH% %GIT_COMMIT%" so if we want jenkins to work properly, we should probably fix that

@jorive

**Comment by jorive** [comment]
Yes, I've noticed the string interpolation in the groovy file is not working.

**Comment by adiaaida** [comment]
Instead, I've opened an issue to disable the Jenkins jobs since the AzDO jobs are now uploading to benchview (#304).

**Comment by adamsitnik** [comment]
@adiaaida can we close this issue now?

**Comment by adiaaida** [comment]
Works for me.
