### ISSUE TITLE
[dotnet-dump] pstacks command fails with a nullref

### ISSUE THREAD

**Issue by En3Tho** [dotnet/performance#2890]
Reproduceable 6.0.351802 and also on dev. For now I will share few screenshots but feel free to ask more information

![image](https://user-images.githubusercontent.com/37334640/217542486-44d84b89-a8a9-4b3f-bfb5-29ec2e67353d.png)
![image](https://user-images.githubusercontent.com/37334640/217543262-88357f91-c09a-4f5d-a9ca-b6f897b5ee4b.png)

**Comment by chrisnas** [comment]
> Reproduceable 6.0.351802 and also on dev. For now I will share few screenshots but feel free to ask more information

Thank [En3Tho](https://github.com/En3Tho)
Do you have more details about the content of the **Method** property of the faulty frame?

**Comment by En3Tho** [comment]
Dump is taken from 7.0.0-preview.7.22375.6 runtime version
The smallest dump I have is 2.7gb. Couldn't make a smaller faulty dump so far

![image](https://user-images.githubusercontent.com/37334640/218501646-62f34a7f-5d72-451f-a671-2f448d4c966c.png)

Interesting moment is the Type property:

![image](https://user-images.githubusercontent.com/37334640/218501785-54411c1e-7d48-45df-93c4-338ce0277fab.png)

And it's module:

![image](https://user-images.githubusercontent.com/37334640/218501935-e22f2587-771e-4d94-b11c-a82d60c33329.png)

If you know better how to share this info (not screenshots :D) then please tell. is there a good way to serialize these types?

**Comment by En3Tho** [comment]
I've prepared a pr as mean of apology :D

**Comment by chrisnas** [comment]
Thanks for the investigation and PR @En3Tho  :^)

**Comment by danmoseley** [comment]
@tommcdon I wonder whether we can broaden who has write access to the diagnostics repo, as that would allow folks on the team to move issues like this there like we do to other repos. maybe there's a github 'team' that needs adjustment
