### ISSUE TITLE
Missing .NET Microbenchmark results - not sure if reporting or benchmarks not running

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/performance#2891]
Looking for a daily comparison for some benchmarks I see many of them are missing in past couple days for all those lanes, across both runtimes

https://pvscmdupload.blob.core.windows.net/index/index/index.html#

![image](https://user-images.githubusercontent.com/46026722/217572710-e668efd0-c7cd-4d01-b3cd-f4072b1a5a73.png)

**Comment by SamMonoRT** [comment]
cc @sblom @DrewScoggins @LoopedBard3

**Comment by LoopedBard3** [comment]
After looking at the pipelines and the report generator, it appears to be an issue with the report generation as nearly all the microbenchmark testing is coming back as green in the pipelines and the uploads are successful.

**Comment by LoopedBard3** [comment]
The index page appears to be working properly now with only 2 runs missing (below) and all reports aside from fsharp and mlnet daily are up to date.

Missing runs: 
Reason: Monthly,dotnetruntime,refs-heads-main,x64,Windows1018362,CompliationMode:tiered,RunKind:micro -> PGOType:fullpgo RunKind:micro Libraries is missing
Reason: 6.0 -&gt; main,dotnetruntime,refs-heads-release-6.0 -&gt; refs-heads-main,ARM64,Ubuntu2004,CompliationMode:tiered,RunKind:micro Micro - All Tests is missing
