### ISSUE TITLE
Perf test for Random.GetItems

### ISSUE THREAD

**Issue by sakno** [dotnet/performance#2913]
The issue is very similar to #415. I'm trying to write a benchmark for `Random.GetItems<T>` method introduced in .NET 8 (as a part of my work in /dotnet/runtime#82286 ), but the method cannot be resolved at compile time.
```
/workspaces/dotnet-perf/src/benchmarks/micro/libraries/System.Runtime.Extensions/Perf.Random.cs(88,33): error CS1061: 'Random' does not contain a definition for 'GetItems' and no accessible extension method 'GetItems' accepting a first argument of type 'Random' could be found (are you missing a using directive or an assembly reference?) [/workspaces/dotnet-perf/src/benchmarks/micro/MicroBenchmarks.csproj::TargetFramework=net8.0]
```

I'm using GH Codespaces with the container spec described in dotnet/runtime repo. Recommendations from [here](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md#benchmarking-new-api) don't work. Full rebuild of Runtime with `./build.sh clr+libs+libs.tests -rc Release -lc Release` doesn't work as well.

**Comment by sakno** [comment]
Build command:
```bash
dotnet run -c Release -f net8.0 --corerun /workspaces/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/shared/Microsoft.NETCore.App/8.0.0/corerun
```

**Comment by cincuranet** [comment]
Did you change the project file as described [here](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md#benchmarking-new-api)?

**Comment by sakno** [comment]
Yes , I tried, but the documentation is unclear when a new API is introduced in `System.Private.CoreLib`.

The following doesn't help:
```xml
<ItemGroup>
    <Reference Include="System.Runtime">
      <HintPath>/workspaces/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/shared/Microsoft.NETCore.App/8.0.0/System.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
```

Any attempt to specify `System.Private.CoreLib` leads to multiple compilation errors, becase Roslyn cannot resolve basic types such as `System.String`:
```xml
<ItemGroup>
    <Reference Include="System.Private.CoreLib">
      <HintPath>/workspaces/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/shared/Microsoft.NETCore.App/8.0.0/System.Private.CoreLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
```

**Comment by cincuranet** [comment]
@adamsitnik @jkotas maybe you have some idea (before I start trying myself)?

**Comment by jkotas** [comment]
>  <HintPath>/workspaces/runtime/artifacts/bin/testhost/net8.0-linux-Release-x64/shared/Microsoft.NETCore.App/8.0.0/System.Runtime.dll</HintPath>

This HintPath is wrong. It is referencing implementation assemblies.

Instead, it needs to reference ref assemblies, like the documentation says: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md#benchmarking-new-api .  ie, it needs to be `...\bin\ref\...` path.
