### ISSUE TITLE
Report not generated for Microsoft.ML.Benchmarks.PredictionEngineBench.MakeBreastCancerPredictions

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#2915]
[This issue](https://github.com/dotnet/perf-autofiling-issues/issues/13340) is missing the graph and link to report is 404.

**Comment by LoopedBard3** [comment]
This appears to be fixed now based on the "Test Report" and Test name links both worked. New issues for it going forward should have the graph.
