### ISSUE TITLE
Duplicated autofilling issues reported in the dotnet/perf-autofiling-issues repository

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#2967]
## Description

There are several duplicated autofilling issues reported in the `dotnet/perf-autofiling-issues` repository. Specifically, issues https://github.com/dotnet/perf-autofiling-issues/issues/15630 and https://github.com/dotnet/perf-autofiling-issues/issues/15728 seem to have the same reported improvements, as well as issues https://github.com/dotnet/perf-autofiling-issues/issues/15769 and https://github.com/dotnet/perf-autofiling-issues/issues/15694.

Filtering out the duplicated autofilling issues could increase the efficiency of the triaging process.

**Comment by cincuranet** [comment]
We're already aware of the issue and working on fixing it.

**Comment by kotlarmilos** [comment]
Thanks! if there is already a tracking issue, feel free to reference it and close this one.

**Comment by cincuranet** [comment]
I believe this has been resolved. Closing. If you (or anybody) still see the problem, let me know.
