### ISSUE TITLE
[mono] HelloiOS SOD and startup measurements failed

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#2990]
## Description

The jobs for SOD and startup measurements of the HelloiOS sample app have failed on `dotnet-runtime-perf` rolling build.

The following is an error log from https://dev.azure.com/dnceng/internal/_build/results?buildId=2168383&view=logs&j=19d72a28-14f6-58c6-0082-3d0b6880df6b&t=8f651a30-faad-5885-6ad2-01cde7f52777.
```
Sending Job to OSX.1015.Amd64.Iphone.Perf...
  Sent Helix Job; see work items at https://helix.dot.net/api/jobs/a180f7ef-f032-46a3-a80d-8ad66b9d524c/workitems?api-version=2019-06-17&access_token={Get this from helix.dot.net}
  Waiting for completion of job a180f7ef-f032-46a3-a80d-8ad66b9d524c on OSX.1015.Amd64.Iphone.Perf
##[error]The operation was canceled.
```

The `OSX.1015.Amd64.Iphone.Perf` queue may be deprecated since no response was received from the Helix.

**Comment by LoopedBard3** [comment]
Thank you for bringing this up! It looks like this may have been a transient failure as the results appear to be working properly now. Let me know if this does not appear to be the case and I will dig deeper, otherwise I will shortly close the issue. Thanks, Parker

**Comment by kotlarmilos** [comment]
Thank you, if it occurs again, we will reopen this issue.
