### ISSUE TITLE
Maui Android builds failing due to missing self-contained specifier

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3045]
Maui Android dotnet-performance runs appear to be failing due to not having the self-contained specifier with the runtime id (either self-contained or not). 
```
D:\a\1\s\CorrelationStaging\dotnet\sdk\8.0.100-preview.5.23271.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(212,5): error NETSDK1191: A runtime identifier for the property 'SelfContained' couldn't be inferred. Specify a rid explicitly. [D:\a\1\s\src\scenarios\mauiandroid\app\MauiAndroidDefault.csproj::TargetFramework=net8.0-android]
```

**Comment by jonathanpeppers** [comment]
I think we had to react to some changes in the .NET SDK here: https://github.com/xamarin/xamarin-android/commit/964746e83a85926b93057559dac70844b2ab3055

So, I wonder if the versions of the .NET SDK and Android workload aren't lined up somehow?
