### ISSUE TITLE
Startup measurements failing for HelloiOS app

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#3054]
## Description

The startup measurements of the HelloiOS app on a device are failing due to the error message `Didn't get the right amount of watchdog events`.
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    Runner(traits).run()
  File "/tmp/helix/working/9F18094D/w/B5CC09FF/u/shared/runner.py", line 687, in run
    raise Exception("Didn't get the right amount of watchdog events, this could mean the app crashed or the device clock is not in sync with the host.")
Exception: Didn't get the right amount of watchdog events, this could mean the app crashed or the device clock is not in sync with the host.
```

/cc: @LoopedBard3

**Comment by LoopedBard3** [comment]
@kotlarmilos Are you still seeing this? The latest run (https://dev.azure.com/dnceng/internal/_build/results?buildId=2198893&view=results) appears to show that this is no longer being hit for iOSMono runs, but we should watch a few more runs to make sure. If the error is gone after a few more runs we should close this issue.

**Comment by kotlarmilos** [comment]
Thanks, it has been fixed according to the last few runs.
