### ISSUE TITLE
Only one PerfLab.cs across repository

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#3155]

**Comment by DrewScoggins** [comment]
I am a little confused. I only see one copy of Perflab.cs checked in?

**Comment by cincuranet** [comment]
The content, though, is in multiple files. Difficult to maintain. I want to have one source of truth.

**Comment by DrewScoggins** [comment]
Ok, so removing the definition of this type from each individual parser and moving it to this one location?

**Comment by cincuranet** [comment]
Not parser(s), but scenario files.
