### ISSUE TITLE
Make it possible to run with Mono

### ISSUE THREAD

**Issue by luhenry** [dotnet/performance#32]
It would be amazing for this benchmarking suite to run on top of Mono. This would allow us to more easily compare performance across the different runtimes, as well as help the Mono team identify where we should focus our performance work.

What should we do on our end to make it easier for you?

Thank you!

**Comment by EgorBo** [comment]
btw, I personally use "InProcess" toolchain (but I launch each benchmark in a separate process) - this is how I managed to run them in aot-llvm mode ;-)

**Comment by adamsitnik** [comment]
@alexanderkyte @EgorBo I left some comments at https://github.com/dotnet/BenchmarkDotNet/pull/940 PTAL at those. As soon as we have it I am going to be more than happy to merge it!

**Comment by billwert** [comment]
This is now possible!
