### ISSUE TITLE
GC heap initialization failed with error 0x8013200B BEGIN: coreclr_initialize failed - Error: 0x8013200b END: coreclr_initialize failed - Error: 0x8013200b

### ISSUE THREAD

**Issue by mayadav1** [dotnet/performance#3234]
I am getting below errors while running gc benchmarks for across cpu groups .

09:42:57 Running defgcperfsim__a__only_config__0gb__0
E:\performance_gc_8.0\src\benchmarks\gc\src\dependencies\PerfView.exe start -NoV2Rundown -NoNGENRundown -NoRundown -AcceptEULA -NoGUI -Merge:true -SessionName:CoreGCBench -zip:false -GCCollectOnly -LogFile:E:\performance_gc_8.0\src\benchmarks\gc\bench\suite-default\normal_server.yaml.out\defgcperfsim__a__only_config__0gb__0.perfview-log.txt -CircularMB:1024 -BufferSizeMB:1024 -DataFile:E:\performance_gc_8.0\src\benchmarks\gc\bench\suite-default\normal_server.yaml.out\defgcperfsim__a__only_config__0gb__0.etl
E:\runtime8\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\CoreRun.exe E:\performance_gc_8.0\artifacts\bin\GCPerfSim\release\net8.0\GCPerfSim.dll -tc 256 -tagb 300.0 -tlgb 0.0 -lohar 0 -pohar 0 -sohsi 0 -lohsi 0 -pohsi 0 -sohsr 100-4000 -lohsr 102400-204800 -pohsr 100-204800 -sohpi 0 -lohpi 0 -sohfi 0 -lohfi 0 -pohfi 0 -allocType reference -testKind time (cwd E:\performance_gc_8.0\src\benchmarks\gc\bench\suite-default\normal_server.yaml.out\defgcperfsim__a__only_config__0gb__0)
GC heap initialization failed with error 0x8013200B
BEGIN: coreclr_initialize failed - Error: 0x8013200b
END: coreclr_initialize failed - Error: 0x8013200b

normal_server.yaml configurations are as follows :

vary: coreclr
test_executables:
  defgcperfsim: E:\performance_gc_8.0\artifacts\bin\GCPerfSim\release\net8.0\GCPerfSim.dll
coreclrs:
  a:
    core_root: E:\runtime8\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root
options:
  default_iteration_count: 2
  default_max_seconds: 300
common_config:
  complus_gcserver: true
  complus_gcconcurrent: false
  complus_gcheapcount: 256
  complus_gccpugroup : true
  complus_thread_useallcpugroups : true
  complus_gcheapaffinitizeranges : 0:1-64,1:1-64
benchmarks:
  0gb:
    arguments:
      tc: 256
      tagb: 300
      tlgb: 0
      lohar: 0
      pohar: 0
      sohsr: 100-4000
      lohsr: 102400-204800
      pohsr: 100-204800
      sohsi: 0
      lohsi: 0
      pohsi: 0
      sohpi: 0
      lohpi: 0
      sohfi: 0
      lohfi: 0
      pohfi: 0
      allocType: reference
      testKind: time
    min_seconds: 10
  2gb:
    arguments:
      tc: 256
      tagb: 300
      tlgb: 2
      lohar: 0
      pohar: 0
      sohsr: 100-4000
      lohsr: 102400-204800
      pohsr: 100-204800
      sohsi: 50
      lohsi: 0
      pohsi: 0
      sohpi: 0
      lohpi: 0
      sohfi: 0
      lohfi: 0
      pohfi: 0
      allocType: reference
      testKind: time
  2gb_pinning:
    arguments:
      tc: 256
      tagb: 100
      tlgb: 2
      lohar: 0
      pohar: 0
      sohsr: 100-4000
      lohsr: 102400-204800
      pohsr: 100-204800
      sohsi: 50
      lohsi: 0
      pohsi: 0
      sohpi: 50
      lohpi: 0
      sohfi: 0
      lohfi: 0
      pohfi: 0
      allocType: reference
      testKind: time
  10gb:
    arguments:
      tc: 254
      tagb: 600
      tlgb: 10
      lohar: 0
      pohar: 0
      sohsr: 100-4000
      lohsr: 102400-204800
      pohsr: 100-204800
      sohsi: 50
      lohsi: 0
      pohsi: 0
      sohpi: 0
      lohpi: 0
      sohfi: 0
      lohfi: 0
      pohfi: 0
      allocType: simple
      testKind: time
scores:
  speed:
    FirstToLastGCSeconds:
      weight: 1
    PauseDurationMSec_95P:
      weight: 1

Please help me . your help will be appreciated.

Thanks .

**Comment by markples** [comment]
Discussed over in https://github.com/dotnet/runtime/issues/90715
