### ISSUE TITLE
Autofilling issues not reporting issues for Mono AOT

### ISSUE THREAD

**Issue by LeVladIonescu** [dotnet/performance#3242]
Over the last week there were no reported issues for mono-aot(https://github.com/dotnet/perf-autofiling-issues/issues?q=is%3Aissue+label%3Amono-aot+is%3Aopen).
I know there were some issues with a batch pool which was `blocklisted`. Are these fixed?

**Comment by LeVladIonescu** [comment]
cc @kotlarmilos @DrewScoggins

**Comment by LoopedBard3** [comment]
@DrewScoggins and I are looking into this.

**Comment by LoopedBard3** [comment]
We took a look and verified that everything is working. This included running the autofile check locally for the same and another date range to make sure no regressions or improvements were found. We also upgraded the queues around the lookback time for last weeks run, so this week will have the autofiling for the new queues. Keeping this issue open to track and check autofiling for this week.

**Comment by LoopedBard3** [comment]
Created an issue to track adding the dummy issue. https://github.com/dotnet/performance/issues/3290

**Comment by LoopedBard3** [comment]
mono-aot issues were filed successfully this week, closed issue.

**Comment by LeVladIonescu** [comment]
Thanks :)
