### ISSUE TITLE
[perf] Add support for SOD autofilling issues targeting apple mobile platforms

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#3332]
## Description

Add Mono and Native AOT iOS autofilling issues for early detection of improvements and regressions, including:
 - HelloWorld app
 - Xamarin iOS template
 - Maui iOS template
 - Maui Blazor iOS template

**Comment by LoopedBard3** [comment]
This should be setup now, so we will need to watch to make sure the updates worked to autofile these.
