### ISSUE TITLE
Enable LongPaths support for Windows queues

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#334]
So far we were always sending to Helix those two directories:

https://github.com/dotnet/performance/blob/8d086bd6ae34424af63d9491faff158f5ccb43be/eng/performance/benchmark_jobs.yml#L89

https://github.com/dotnet/performance/blob/8d086bd6ae34424af63d9491faff158f5ccb43be/eng/performance/benchmark_jobs.yml#L91

And they were restored to something like this on the actual machine:

```log
C:\dotnetbuild\work\82ac7b90-beba-445c-96a0-c3ed279fccb2\Work\e11567ec-0440-4e29-b6c0-e1f673b64baf\Exec - WorkItemDirectory
C:\dotnetbuild\work\82ac7b90-beba-445c-96a0-c3ed279fccb2\Payload\ - CorrelationPayloadDirectory
```

We want to add new benchmarks (ML.NET etc) and we can't just send `\src\benchmarks\micro` o Helix, we want to be able to send entire repo and when we do it on Windows we get PathTooLongException because the file names are longer that 260.

@adiaaida could you please talk to the right people to enable Long Paths support on the machines from following queues:

Windows.Amd64.ClientRS4.DevEx.15.8.Perf
Windows.10.Amd64.ClientRS1.Perf

**Comment by jorive** [comment]
@adamsitnik This issue should be opened in https://github.com/dotnet/core-eng instead.

**Comment by adiaaida** [comment]
Issue moved to [dotnet/core-eng #5365](https://github.com/dotnet/core-eng/issues/5365) via [**ZenHub**](https://www.zenhub.com/)

**Comment by adiaaida** [comment]
Issue moved to [dotnet/core-eng #5366](https://github.com/dotnet/core-eng/issues/5366) via [**ZenHub**](https://www.zenhub.com/)
