### ISSUE TITLE
[perf] Mono performance jobs are failing to install prerequisites 

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#3364]
The Mono AOT performance jobs are failing to install prerequisites.

```
+ echo ** Installing prerequistes **
** Installing prerequistes **
+ python3 -m pip install --user -U pip
Requirement already satisfied: pip in /home/helixbot/.local/lib/python3.10/site-packages (23.2.1)
+ sudo apt-get -y install python3-venv
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
+ export PERF_PREREQS_INSTALL_FAILED=1
+ test x1 = x1
+ echo ** Error: Failed to install prerequites **
** Error: Failed to install prerequites **
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2274079&view=logs&j=3ad9afb5-5506-517e-402a-ab4e139d0d70&t=051311be-2b3a-501d-5897-2c63fc6d775f

/cc: @LoopedBard3 @cincuranet

**Comment by LoopedBard3** [comment]
This is the same error we hit here: https://github.com/dotnet/runtime/issues/91959. Let me see if this is a single machine issue or multi-machine issue.

**Comment by LoopedBard3** [comment]
Looks like it is just PERFTIGER174 causing the error, I will go on an run the command to fix the error.

**Comment by kotlarmilos** [comment]
Thanks for swift response!

**Comment by LoopedBard3** [comment]
Workitem to add the machine back into the queue: https://github.com/dotnet/dnceng/issues/857

**Comment by LoopedBard3** [comment]
PerfTiger174 should be fixed up now so I am having it added back into the queue. If we don't see any more issues within a day or so we should be good to close this issue. I will watch for any issues but if they are spotted please still comment here.

**Comment by LoopedBard3** [comment]
The machine has been added back and does not appear to be having any problems. Closing issue.
