### ISSUE TITLE
Enable ML.NET benchmarks runs as part of the CI

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#338]
- [x] add support for ML.NET project file to `benchmarks_ci.py` (@jorive,  done in #325)
- [x] define a new CI leg for ML.NET benchmarks (@adamsitnik, done in #352)
- [x] add BenchView SAS token (@DrewScoggins, done)
- [x] add ML.NET runs to BenchView web page (@adiaaida)

/cc @najeeb-kazmi @danmosemsft

**Comment by jorive** [comment]
I think I have already removed repo specific "BenchView-related settings", and made them uniform for anything .NET in the repo. Could you please expand what does third point means and what is left to do?

**Comment by adamsitnik** [comment]
I meant configuring the Blob storage, SAS token for Azure DevOps and the BenchView web page

**Comment by jorive** [comment]
@DrewScoggins @adiaaida Could you please help creating the blob storage and provide the SAS token for ML.NET runs?

**Comment by DrewScoggins** [comment]
Yes, I will get the container and SAS tokens for the uploader in place.

**Comment by DrewScoggins** [comment]
The container is made, it is called mldotnet. If the runs are being triggered through AzDO then we already have the SAS tokens setup properly for upload to the container. I will make sure that the DB uploader has it's config updated to look in this new location.

**Comment by adamsitnik** [comment]
The CI legs which are going to run the ML.NET benchmarks and upload the results to the container configured by @DrewScoggins go just merged in #352 

@adiaaida could you please add the ML.NET benchmarks to BenchView page? I expect that the first results are going to appear there in a few hours

**Comment by adiaaida** [comment]
I don't think we can add it until results have been uploaded to Benchview. @DrewScoggins would know better.

**Comment by DrewScoggins** [comment]
What is the title of the runs? I searched for jobs with ML in the name, but didn't find any recent ones.

**Comment by adiaaida** [comment]
ML runs were merged in with the corefx/coreclr tests. They all have the same group name. We'll probably want to split ML results out.

**Comment by DrewScoggins** [comment]
I went ahead and updated the home page. I dropped the individual .Net Performance groups and added the new combined one.

**Comment by adamsitnik** [comment]
The results are now available at https://benchview/trendline?build_selector=latest&count=200&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[1713]&archids=[9]&mpids=[1292]&cfgids=[3394,3391,3392,3393]&testids=[160661,160665,160670,160671,160669,160672,160682,160667,160683,160668,160679,160662,160680,160666,160681,160664,160676,160675,160674,160673,160678,160677]&jobid=156962&

thanks to everyone who has helped!
