### ISSUE TITLE
Improvement request for the local testing script for microbenchmarks

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/performance#3385]
To summarize the suggestion listed in https://github.com/dotnet/performance/pull/3338. I would like to propose several enhancements for consideration to be incorporated into the local testing script for microbenchmarks:

- [x] Remove `Killing any running dotnet, vstest, or msbuild processes`, when running on developer's local machine (https://github.com/dotnet/performance/pull/3431)
- [ ] The script will have an option to build a docker container. Run the microbenchmarks there and report back the results.
- [ ] When running with admin privileges, it would be nice that only the microbenchmarks are run with higher privileges and building of runtime is done with standard user privileges.
- [x] Add the profiling option, specifically, I would like an option to use EventPipeProfiler. The document for it could be found [here](https://github.com/dotnet/BenchmarkDotNet/blob/dd7a9b7cd132e522951eeb6916a3aa27a24ebf59/docs/articles/features/event-pipe-profiler.md) This will help use trace down c# code path change, when investigating a regression. (Answer: https://github.com/dotnet/performance/issues/3385#issuecomment-1749496883)
- [x] Add a proper README for the script. https://github.com/dotnet/performance/pull/3468
- [x] Add filter aliases or similar for microbenchmark sets that are often problematic. (per below) (Initial non-integrated location in the README: https://github.com/dotnet/performance/pull/3468) (Feel free to add your own!)

**Comment by LoopedBard3** [comment]
For the profiling option, adding `--bdn-arguments "-p EP"` will enable that specific profiler. Any BDN specific arguments can also be passed this way, such as --buildTimeout. Since this is not documented great, I will make sure to add a section on it to a proper README (I also added creating a README to the list of items).

**Comment by matouskozak** [comment]
I was testing the local benchmark script on DevBox x64 WSL Ubuntu and it takes quite a while to run all microbenchmarks (10-13h depending on the configuration). I was thinking, if for local testing, we might disable some long running microbenchmarks or try to select a set of microbenchmarks that usually are the problematic ones (on Mono side those are vectors, strings, span, collections) and create an alias for the `--filter` argument to run just those.

**Comment by LoopedBard3** [comment]
I have a PR out for an initial README: https://github.com/dotnet/performance/pull/3468. All feedback is welcome. Right now, there is a placeholder section for useful filters that could also use some suggestions.

**Comment by LoopedBard3** [comment]
With the merging of https://github.com/dotnet/performance/pull/3934, which removes the default of terminating all dotnet processes during runs, a major reason for having containers to run the script in is fixed.

For the building of the runtime as non-admin, I was not able to find any clear path to achieve this cleanly for both windows and linux in python. A manual alternative to this is to initially only build the runtime with `--build-only` and `--allow-non-admin-execution` arguments set, and then run again without them set. Unfortunately, this would require two calls to the program. If a clear path is found that enables this work, then it can be revisited. 

With all of this, I am closing this issue. Please leave any additional comments/feedback either here or in a new issue.
