### ISSUE TITLE
mono-jit autofile for 10/03 missing

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3389]
The mono-jit autofile for 10/03 seems to be missing. Working on investigating it.

There are multiple errors, including `UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 62: character maps to <undefined>` and `{"message":"Validation Failed","errors":[{"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}],"documentation_url":"https://docs.github.com/rest/issues/comments#create-an-issue-comment"}`

**Comment by DrewScoggins** [comment]
The decode error is unlikely to be the culprit. The second one is probably happening because we have enough to put in a single test that we are getting over the 65K character limit for a comment.

You will want to look at L212 in AutoFiler.cs, that is where we will likely need to make a change.

**Comment by LoopedBard3** [comment]
Fix is in the autofiler, rerunning autofile for 10/03 for the missing issues. Will close once complete.

**Comment by LoopedBard3** [comment]
The run finished: https://github.com/dotnet/perf-autofiling-issues/issues/23531. Closing issue.
