### ISSUE TITLE
Wasm warning 'unknown flag --experimental-wasm-eh'

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3399]
It appears that the `--experimental-wasm-eh` flag we are passing to v8 is not being recognized. This is affecting both the wasm aot and wasm wasm microbenchmarks. I have not looked back to see how far back this is affecting yet. The version of v8 that was used in the run I found this is 11.7.439. I tried searching the help for this flag on version 12.0.* of v8 and am not finding it as an option so it may have been removed.

@radical, do you know if this is the proper use of the --experimental-wasm-eh flag and if the flag still exists?

**Comment by LoopedBard3** [comment]
After some digging it looks like the --experimental-wasm-eh flag may only be needed by older node versions and can be removed from our runs: https://github.com/dotnet/runtime/issues/91318

**Comment by radical** [comment]
Yeah, the versions of v8 being used in perf pipeline, and library tests were not the same earlier. But they are controlled, and in sync now to be the latest stable which shouldn't be needed now.

**Comment by LoopedBard3** [comment]
This appears to be working as expected.
