### ISSUE TITLE
Port newly added benchmarks from CoreFX/CoreCLR to perf repo

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#344]
The current snapshot of benchmarks has lagged behind the repos. Need to catch up.

**Comment by jorive** [comment]
@billwert Could you please provide a list?

**Comment by adamsitnik** [comment]
I did go through all CoreFX benchmarks today and created the issues to keep track of it.

#357 #358 #359 #360 #362

**Comment by jorive** [comment]
What about CoreClr?

**Comment by adamsitnik** [comment]
> What about CoreClr?

My manager did not tell me to port the CoreCLR benchmarks.

Just kidding. They are on my todo list once I am done with CoreFX I will scan CoreCLR

**Comment by adamsitnik** [comment]
The only missing CoreCLR benchmark was #113 which I have ported in #382

**Comment by adamsitnik** [comment]
All benchmarks have been ported and merged!
