### ISSUE TITLE
ComWrappersTests.ParallelRCWLookUp long op time in specific queue

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3448]
The ComWrappersTests.ParallelRCWLookUp test is taking 10+ minutes per op when run in the Windows.Server.Arm64.Perf machine queue. This is much greater than the ~9s per op when running on other queues. This long op is also causing many of the Partition10 jobs to fail due to timing out, failing the jobs and taking out one of the few machines for a long period of time.  

Test added in: https://github.com/dotnet/performance/commit/36ab046503c47ea9a9f1abc62e61093456f9468e

FYI @AaronRobinsonMSFT, about the massive time difference.

**Comment by LoopedBard3** [comment]
Run with the error can be found in the pipeline https://dev.azure.com/dnceng/internal/_build/results?buildId=2301502&view=logs&j=86ff836e-79c0-5c2b-d692-74a6138ae50d&t=67773ac8-bb27-54c6-5c6e-b22882c3b62f, under the job for windows arm64, perfampere. There is only one partition failure (Partition10), the partition this test is in.

**Comment by AaronRobinsonMSFT** [comment]
@LoopedBard3 How can I view the other runs? I looked at Partition 10 for the other runs and didn't see `ParallelRCWLookUp`. Is there some algorithm for looking at this data?

/cc @dotnet/interop-contrib @jkotas

**Comment by LoopedBard3** [comment]
It should be available in the windows arm64 perfsurf job above the failing perfampere one.

**Comment by LoopedBard3** [comment]
Here is a link to the test itself: https://github.com/dotnet/performance/blob/4bfa9d4974654c9e04fc68914e925aacf8aaf69e/src/benchmarks/micro/runtime/Interop/ComWrappers.cs#L43-L56

**Comment by jkotas** [comment]
cc @mangod9 @JulieLeeMSFT Microbenchmark takes 10+ minutes on Windows Arm64 server vs. 9 seconds in other queues.

**Comment by AaronRobinsonMSFT** [comment]
I don't have a lot of bandwidth to investigate this now, but I am dubious this has anything to do with `ComWrappers` or is specific to the API. I say that because there is nothing that is architecture specific in `ComWrappers` - either in managed or unmanaged code.

**Comment by mangod9** [comment]
Is this a regression or a new benchmark and/or config?

**Comment by jkotas** [comment]
It is a new microbenchmark added two months ago in #3298. This microbenchmark is a regression test for a customer reported performance issue that we have fixed.

**Comment by mangod9** [comment]
hi @LoopedBard3,  I tried reproing the issue on an Azure arm64 windows VM with two cores but I am not observing the same behavior. I notice that the parallelism is driven by ProcessorCount -- so is it the same across different OS queues?

**Comment by LoopedBard3** [comment]
@mangod9 This issue is most prominent on specifically the Windows OS on the arm64 server, which has 80 cores I believe (it is a high core machine, I can get the exact core count if needed). I have sent you a DM with a query that will produce a chart making it easier to see the runtime differences between the platforms, but to summarize: All of the arm machines take longer than the x64 tests. The fastest arm setup is the Surface machines which are running windows at about 2x one of the Windows x64 setups (~5s -> 9s per run), the next slowest are the Linux arm server machines at ~8x slower (9s -> 80s), the slowest runs are the windows arm server runs at 10x slower than that (80s -> 800s). I have also shared some traces from one of the Windows arm machines in a DM.

**Comment by LoopedBard3** [comment]
FYI: @kunalspathak do you know if we already have any issues tracking perf issues with contention due to high core counts, or if this issue may already be known/tracked?

**Comment by mangod9** [comment]
will look through the traces, but we should determine right machine sizing to run such scenarios. Assume x64 is running with lower core counts?

**Comment by kunalspathak** [comment]
> FYI: @kunalspathak do you know if we already have any issues tracking perf issues with contention due to high core counts, or if this issue may already be known/tracked?

We had https://github.com/dotnet/runtime/issues/67845 in the past, but we fixed it. Not sure if there is something different that happens with the interaction of comwrappers on high core count. Please share the traces to me as well.

**Comment by LoopedBard3** [comment]
> will look through the traces, but we should determine right machine sizing to run such scenarios. Assume x64 is running with lower core counts?

That is correct, the x64 machines have either 6 or 8 cores depending on AMD or intel, and the Surf arm64 machine has 8 cores.

**Comment by mangod9** [comment]
From the traces looks like all time is spent in `coreclr!ManagedObjectWrapper::QueryInterface or Release` which I am guessing is expected.

**Comment by kunalspathak** [comment]
> From the traces looks like all time is spent in `coreclr!ManagedObjectWrapper::QueryInterface or Release` which I am guessing is expected.

I am seeing this. Is that the same thing?

<img width="561" alt="image" src="https://github.com/dotnet/performance/assets/12488060/46fe7104-d64c-4958-b19a-a3467fa9dc8b">

**Comment by mangod9** [comment]
yeah believe if you drill down into it you should see QI and Release

**Comment by AaronRobinsonMSFT** [comment]
> From the traces looks like all time is spent in `coreclr!ManagedObjectWrapper::QueryInterface or Release` which I am guessing is expected.

The `ManagedObjectWrapper::QueryInterface` does a fair bit of logic, but is identical on all platforms and for this test should be very short. The `Release()` operation has a hot path using atomics for increment.

**Comment by danmoseley** [comment]
Would it be interesting to measure on the 80 core machine but with it somehow limited to just a few cores?

**Comment by LoopedBard3** [comment]
I reran the test on the same machine setup that is having the issue and tried DOTNET_PROCESSOR_COUNT set to 1 and 2. With the processor count set, the test ran better and finished with a mean of 403.3 ms for 1 count, and 1.366 s for 2 count. I also tested both the processor count of 1, 2, and 80 with the for loop only going to 30. For these tests, the mean result was 14.15 us, 24.32 us, and 6.985 ms respectively.

**Comment by LoopedBard3** [comment]
Moving this to closed as there hasn't been any activity and the triggering issue has been resolved. Feel free to reopen or open a new issue if desired.
