### ISSUE TITLE
Experiment: Cross Block Local Assertion Prop

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#3482]
`DOTNET_JitEnableCrossBlockLocalAssertionProp=1`

cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Great... this will be very helpful.

**Comment by AndyAyersMS** [comment]
Awesome... can you remind me how I can pull this data via ADX?

**Comment by cincuranet** [comment]
I'll create dashboard/query for it and send it tomorrow.

**Comment by cincuranet** [comment]
Here's https://dataexplorer.azure.com/dashboards/2e73bc28-a06e-4f58-9f74-8b800205228f the link for the dashboard.

**Comment by AndyAyersMS** [comment]
I'm getting a permissions denied when I try and view the dashboard.

**Comment by cincuranet** [comment]
Fixed.
