### ISSUE TITLE
Inner Loop Test Time on Thread Diff occasionally negative

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3601]
The Inner Loop Test Time on Thread Diff values occasionally contain a negative value. This seems fairly rare with only 8 occurrences in the last 120d from today in the dotnet-performance pipeline runs. 

An example of this output is here: https://github.com/dotnet/performance/pull/3586#issuecomment-1847872747.

**Comment by cincuranet** [comment]
👀

**Comment by cincuranet** [comment]
Looks like this simply because of the fact that 2nd run spent more _Time on Thread_ than first one... We have occasionally same behavior with _Generic Startup Diff_. I would say nothing no worry about from measurement POV.
