### ISSUE TITLE
Change the app to benchmark for memory consumption

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/performance#3603]
Change the app to benchmark for memory consumption. Currently, it is benchmarking lols app. I would like to switch it to the maui template app. The app could be created by `dotnet new maui`.

**Comment by LoopedBard3** [comment]
We should currently be testing the default maui new app based on the configuration setup here: https://github.com/dotnet/performance/blob/main/eng/performance/maui_scenarios_android.proj. Let me know if that is not what you are seeing and the reports and I can continue looking to figure out what may be wrong.
