### ISSUE TITLE
Navigating the repo is difficult since benchmarks/micro collides with tests/benchmarks/micro

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/performance#361]
Under [/src/](https://github.com/dotnet/performance/tree/master/src), we have [benchmarks/micro](https://github.com/dotnet/performance/tree/master/src/benchmarks/micro) and [tests/benchmarks/micro](https://github.com/dotnet/performance/tree/master/src/tests/benchmarks/micro). These two collide a bit, making navigation difficult.

We should consider moving/renaming the files under `/src/tests/`

cc @jorive, @adamsitnik

**Comment by adamsitnik** [comment]
good point, I am going to do that.
