### ISSUE TITLE
results?

### ISSUE THREAD

**Issue by JanEggers** [dotnet/performance#365]
what is the correct way to view the results of these benchmarks?

are there any plans to build a dashboard like: 

https://aka.ms/aspnet/benchmarks

**Comment by adamsitnik** [comment]
hello @JanEggers 

> what is the correct way to view the results of these benchmarks?

as of today you can run them on your hardware, the benchmarks have doc page describing how to do that

> are there any plans to build a dashboard like

yes, @DrewScoggins is working on that.
