### ISSUE TITLE
Performance 8.0 runs failing due to dotnet install and build failures

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3655]
Performance 8.0 runs failing due to dotnet install and build failures. The dotnet install failures are outlined here: https://github.com/dotnet/performance/issues/3576. The build failures due to this failure when trying to build our tooling: 
```
MSBuild version 17.9.0-preview-23614-01+b0e2b7923 for .NET
  Determining projects to restore...
  Restored /home/vsts/work/1/s/src/tools/Reporting/Reporting/Reporting.csproj (in 3.68 sec).
  Restored /home/vsts/work/1/s/src/tools/ScenarioMeasurement/Util/Util.csproj (in 6.44 sec).
  Restored /home/vsts/work/1/s/src/tools/ScenarioMeasurement/Startup/Startup.csproj (in 3.43 sec).
/home/vsts/.nuget/packages/microsoft.dotnet.xlifftasks/9.0.0-beta.23615.2/build/Microsoft.DotNet.XliffTasks.targets(85,5): error MSB4062: The "UpdateXlf" task could not be loaded from the assembly /home/vsts/.nuget/packages/microsoft.dotnet.xlifftasks/9.0.0-beta.23615.2/build/../tools/net9.0/Microsoft.DotNet.XliffTasks.dll. Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/home/vsts/work/1/s/src/tools/ScenarioMeasurement/Startup/Startup.csproj]
/home/vsts/.nuget/packages/microsoft.dotnet.xlifftasks/9.0.0-beta.23615.2/build/Microsoft.DotNet.XliffTasks.targets(85,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/home/vsts/work/1/s/src/tools/ScenarioMeasurement/Startup/Startup.csproj]

##[error]Bash exited with code '1'.
```
Disabling the 8.0 tests until these are fixed. 

The affected tests for the dotnet-install failure are all of the microbenchmark-esque tests like ML.NET or ImageSharp, basically the tests that use BDN; and the build failures are affecting the scenario tests that use the scenario tools such as the SOD and startup testing. Each group of tests can be enabled once their respective issue is fixed.

**Comment by LoopedBard3** [comment]
For the UpdateXLF/XliffTasks failure that the scenarios are hitting on 8.0, using a 9.0 sdk and targetting TFM 8.0 succeeds. The specific change that started the issue was an update to the Arcade SDK version: https://github.com/dotnet/performance/pull/3635, where the Arcade SDK also upgraded to net9.0 (likely specifically https://github.com/dotnet/arcade/pull/14279). This means we either need to make an 8.0 branch for the performance repo, find a way to build our tools with a different sdk than we want to test (build 8.0 tools with 9.0 sdk while still using 8.0 for scenario build + testing), or find a way to use different global.json or arcade sdk versions depending on if we are targetting main or 8.0. Any other solutions or thoughts are appreciated!

**Comment by cincuranet** [comment]
The SDK is backwards compatible, so it shouldn't be a problem to build with 9.0 SDK and build 8.0 apps. But we should discuss whether we want to do this, just in case there's something different.

**Comment by LoopedBard3** [comment]
I agree. The main thing I want to ensure is that the 8.0 runs test the 8.0 runtime bits we expect.

**Comment by LoopedBard3** [comment]
This has been fixed by: https://github.com/dotnet/performance/pull/3853 and https://github.com/dotnet/performance/pull/3873

**Comment by fanyang-mono** [comment]
Was the AndroidBDN test re-enabled?

**Comment by LoopedBard3** [comment]
I had some test runs that were failing. Just ran another and hit what I am pretty sure is a new failure. Working on investigating the error:
```
/Users/runner/work/1/s/sdk/9.0.100-preview.1.24101.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.NETCore.App.Runtime.AOT.Cross.net8.ios-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net8.iossimulator-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net8.iossimulator-x64 [/Users/runner/work/1/s/maui/src/Graphics/src/Graphics/Graphics.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/sdk/9.0.100-preview.1.24101.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK. [/Users/runner/work/1/s/maui/src/Graphics/src/Graphics/Graphics.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/sdk/9.0.100-preview.1.24101.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: The project depends on the following workload packs that do not exist in any of the workloads available in this installation: Microsoft.NETCore.App.Runtime.AOT.Cross.net8.ios-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net8.iossimulator-arm64 Microsoft.NETCore.App.Runtime.AOT.Cross.net8.iossimulator-x64 [/Users/runner/work/1/s/maui/src/Essentials/src/Essentials.csproj::TargetFramework=net8.0-ios]
/Users/runner/work/1/s/sdk/9.0.100-preview.1.24101.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: You may need to build the project on another operating system or architecture, or update the .NET SDK. [/Users/runner/work/1/s/maui/src/Essentials/src/Essentials.csproj::TargetFramework=net8.0-ios]
```
