### ISSUE TITLE
Implement decimal benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#379]
Today I was porting some of the Utf8Formatter benchmarks and I have realized that we have only one Decimal benchmark

https://github.com/dotnet/corefx/blob/79ef29bcc1b9e5f2d7ef595e136771c89eb1bce8/src/System.Runtime/tests/Performance/Perf.Decimal.cs

which I have ported to https://github.com/dotnet/performance/blob/5c02f92b039321274c841eb4d3fd9b64524d0975/src/benchmarks/micro/corefx/System.Runtime/Perf.Double.cs#L46 some time  ago

We should definitely have more ;)

/cc @danmosemsft @tannergooding

**Comment by tannergooding** [comment]
CC. @pentp who has done much of the existing work on `decimal`.

**Comment by adamsitnik** [comment]
@stephentoub have implemented some benchmarks for decimal math operations in #478, I think that we can close this issue now.
