### ISSUE TITLE
Add new System.IO.Pipelines benchmark from recent CoreFX PR

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/performance#380]
`PipeReader.AsStream()` was improved recently: https://github.com/dotnet/corefx/pull/35874

We should consider adding benchmarks for it. An example benchmark is available in the PR itself.

We also may want to expand on the sets of perf tests for pipelines, in general:
https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/corefx/System.IO.Pipelines/Perf.Pipe.cs

cc @pakrym, @adamsitnik, @stephentoub, @davidfowl

**Comment by davidfowl** [comment]
Also these https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/perf/Kestrel.Performance/PipeThroughputBenchmark.cs
