### ISSUE TITLE
Add device version to PowerBI chart

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/performance#3805]
It would be nice to list the version of the devices that we are using for testing. For example, it would be nice to list which version of Pixel and Galaxy phones were used here. Same goes for iOS devices.
<img width="937" alt="Screenshot 2024-01-23 at 1 41 30 PM" src="https://github.com/dotnet/performance/assets/52458914/cacb5346-4587-472a-8127-adef42d05c1f">

**Comment by LoopedBard3** [comment]
Added device version to the MauiScenarios. For reference, here are the current devices we have:


![Image](https://github.com/dotnet/performance/assets/15679138/e3239a22-ffd6-45d3-8080-d4ccbcb21511)
