### ISSUE TITLE
Update the link on BenchView page

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#386]
In #354 `framework` has been added to the uploaded BenchView options and we need to update the link at `benchview/` again. 

@DrewScoggins could you please do that? I think that the link should now be following:

https://benchview/trendline?build_selector=latest&count=20&aggregate=arithmeticMean&filterTail=one&filterVal=100&interval=INTERVAL_MIN_MAX&rtids=[1713]&archids=[9]&mpids=[1292]&cfgids=[3394,3391,3392,3393]&jobid=156962&

@jorive please correct me if the link is wrong

**Comment by jorive** [comment]
I believe that only the `BranchId` will need to be updated in the `HomeLinks` table.

**Comment by jorive** [comment]
Link was updated. Closing this.
