### ISSUE TITLE
Output directory is confusing

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#390]
Due to dotnet/cli#10990, if you run the microbenchmarks project without passing -c Release the results end up under a Debug directory, which is confusing.

Worse, if you run a lot of benchmarks the only indication this happened has scrolled far off the terminal window by the time the run is done.

Until that is fixed (if it is ever) I think we should remove the <Optimize> tag from the csproj, so we force a reasonable state.

**Comment by adamsitnik** [comment]
@billwert do I understand correctly that https://github.com/dotnet/performance/pull/391 has solved this issue and we can close it?

**Comment by billwert** [comment]
yup! (I guess I didn't put 'fixes #390' in the right place in the PR, I thought it could be in a comment.)
