### ISSUE TITLE
Wasm runs failing with empty WasmAssembliesToBundle

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3984]
Starting on [02/19](https://dev.azure.com/dnceng/internal/_build/results?buildId=2383193&view=results), Wasm runs switched from hitting one failure (now seemingly fixed: https://github.com/dotnet/runtime/issues/98334) to hitting a new failure: `WasmApp.Common.targets(350,5): error : WasmAssembliesToBundle item is empty. No assemblies to process [/home/helixbot/work/9CCA0950/w/B41609A7/e/performance/artifacts/bin/for-running/MicroBenchmarks/Job-HFTUUL/BenchmarkDotNet.Autogenerated.csproj]` when building the BenchmarkDotNet.Autogenerated.csproj (WasmNestedPublishApp) -> PrepareInputsForWasmBuild Target.

This failure seems to correspond with when we [updated our BDN version](https://github.com/dotnet/performance/pull/3940) from '0.13.11-nightly.20231126.107' -> '0.13.13-nightly.20240213.132'. Digging into a binlog from a previous working run and a recent failing run, the TargetDir property now has /AppBundle at the end and the configuration in the path, the TargetDir is being set to the same path for all of the projects, and the Target PrepareForWasmBuild is not adding any items (.dlls). The path TargetDir path update seems to be from https://github.com/dotnet/BenchmarkDotNet/commit/e6fdc6b3c4d540983641f5aeca9c93308dc0da7a. Was able to repro with updated perf repo using command line: `sudo python3 ./scripths/benchmarks_local.py --commits cc95b08e0060d388c5a48268f85d454fbe8e64fe --run-types WasmInterpreter --filter *Span.IndexerBench.CoveredIndex2* *WriteReadAsync* --wasm-engine-path /<path>/.jsvu/engines/v8/v8 --rebuild-artifacts --reinstall-dotnet`

FYI: @adamsitnik, @ilonatommy

**Comment by LoopedBard3** [comment]
@caaavik-msft and I found that path used by the PrepareForWasmBuild task and the path the files are being put do not match, /AppBundle/publish/ and /AppBundlepublish/ respectively. This seems to stem from the update here: https://github.com/dotnet/BenchmarkDotNet/commit/e6fdc6b3c4d540983641f5aeca9c93308dc0da7a#diff-77e0d627a9d7c20f6d24179d3ca8dbe29aba70b95b5f464786ee93386e63412aR262-R268 missing trailing slashes, at least for OutDir: https://learn.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170

**Comment by adamsitnik** [comment]
cc @radical @timcassell

**Comment by timcassell** [comment]
> missing trailing slashes, at least for OutDir: https://learn.microsoft.com/en-us/cpp/build/reference/common-macros-for-build-commands-and-properties?view=msvc-170

Interesting, when I implemented that change, I followed https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022 which doesn't mention trailing slash (only for `IntermediateOutputPath`). It doesn't appear to be necessary for CoreCLR builds. Do we need to conditionally add it depending on the runtime, or it would be fine to include it always?

**Comment by radical** [comment]
cc @lewing @akoeplinger

**Comment by timcassell** [comment]
> With the trailing slashes, this file is being put in one folder too deep, specifically into ./AppBundle/AppBundle/test-main.js instead of ./AppBundle/test-main.js, so there is a duplication to track down somewhere.

Does the wasm build auto append AppBundle to the output path? If so, that would explain it, as previously BDN was only reading the path to get the executable, and now it's passing it to the cli which it wasn't doing before. If that's how it works, we may need to pass a different path to the cli with AppBundle removed.

**Comment by LoopedBard3** [comment]
> Does the wasm build auto append AppBundle to the output path? If so, that would explain it, as previously BDN was only reading the path to get the executable, and now it's passing it to the cli which it wasn't doing before. If that's how it works, we may need to pass a different path to the cli with AppBundle removed.

I don't know for sure, but that is definitely a possibility and would make sense as to why the additional AppBundle is occuring.

**Comment by LoopedBard3** [comment]
> > Does the wasm build auto append AppBundle to the output path? If so, that would explain it, as previously BDN was only reading the path to get the executable, and now it's passing it to the cli which it wasn't doing before. If that's how it works, we may need to pass a different path to the cli with AppBundle removed.
> 
> I don't know for sure, but that is definitely a possibility and would make sense as to why the additional AppBundle is occuring.

Likely found it. In the _InitializeCommonProperties from _WasmBuildAppCore, the WasmAppDir which is used later for where to copy test-main.js to is being set with: `<WasmAppDir Condition="'$(WasmAppDir)' == ''">$([MSBuild]::NormalizeDirectory($(OutputPath), 'AppBundle'))</WasmAppDir>`

**Comment by timcassell** [comment]
> Likely found it. In the _InitializeCommonProperties from _WasmBuildAppCore, the WasmAppDir which is used later for where to copy test-main.js to is being set with: `<WasmAppDir Condition="'$(WasmAppDir)' == ''">$([MSBuild]::NormalizeDirectory($(OutputPath), 'AppBundle'))</WasmAppDir>`.

So what's the best fix? Do we pass output paths without `AppBundle`? Do we pass `WasmAppDir`? Something else?

**Comment by LoopedBard3** [comment]
This was been fixed by dotnet/BenchmarkDotNet#2531.
