### ISSUE TITLE
Align description of Repo with readme.md

### ISSUE THREAD

**Issue by JarnoNijboer** [dotnet/performance#406]
The description of the repo on GitHub is:
"This repo contains benchmarks used for testing the performance of .NET Frameworks."

Almost the same sentence can also found in the readme.md
"This repo contains benchmarks used for testing the performance of all .NET Runtimes"

The latter should also be used for the description

**Comment by adamsitnik** [comment]
@JarnoNijboer thanks!

#done 

![obraz](https://user-images.githubusercontent.com/6011991/55080510-92d50680-509e-11e9-9378-b1b4cd209085.png)
