### ISSUE TITLE
Investigate bimodal SpectralNorm_3

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#41]
The SpectralNorm_3 is a bimodal benchmark.

Example histograms from BenchmarkDotNet:

```log
-------------------- Histogram --------------------
[0.786 ms ; 1.033 ms) | @
[1.033 ms ; 1.466 ms) | @@@@@@@@@@@@@@@@@@
[1.466 ms ; 1.807 ms) | @@@
[1.807 ms ; 2.240 ms) | @@@@@@@
[2.240 ms ; 2.875 ms) | @@@@@
[2.875 ms ; 3.288 ms) |
[3.288 ms ; 3.721 ms) | @@@@@@
---------------------------------------------------
```

```log
-------------------- Histogram --------------------
[0.942 ms ; 1.237 ms) | @@@
[1.237 ms ; 1.614 ms) | @@@@@@@@@@
[1.614 ms ; 1.892 ms) | @
[1.892 ms ; 2.269 ms) | @@@@@@@
[2.269 ms ; 2.563 ms) | @@@
[2.563 ms ; 2.940 ms) | @@@@@@@@@
[2.940 ms ; 3.354 ms) | @@@@
[3.354 ms ; 3.731 ms) | @@@
---------------------------------------------------
```

Sample results from xunit-performance (please look at the Min and Max value):

 DotNetBenchmark-spectralnorm-3.dll     | Metric   | Unit | Iterations |  Average | STDEV.S |      Min |      Max
:-------------------------------------- |:-------- |:----:|:----------:| --------:| -------:| --------:| --------:
 BenchmarksGame.SpectralNorm_3.RunBench | Duration | msec |     6      | 1848.838 | 380.029 | 1517.790 | 2584.247

 DotNetBenchmark-spectralnorm-3.dll     | Metric   | Unit | Iterations |  Average | STDEV.S |      Min |      Max
:-------------------------------------- |:-------- |:----:|:----------:| --------:| -------:| --------:| --------:
 BenchmarksGame.SpectralNorm_3.RunBench | Duration | msec |     6      | 1928.860 | 173.474 | 1831.114 | 2272.792

We can get the diasm with BDN, but we need #40 to be implemented first to get profiles

**Comment by billwert** [comment]
Closing old issues like this as we have better techniques for finding these things now.
