### ISSUE TITLE
Make ResultsComparer into a stand-alone global tool

### ISSUE THREAD

**Issue by Kosat** [dotnet/performance#412]
Hello @adamsitnik,

I'm working on adding BenchmarkDotNet performance tests to the [dotnet/command-line-api](https://github.com/dotnet/command-line-api/issues/469) project.
For starters, there will be no integration with CI. So, we would just ask developers to run those tests locally and manually check for regressions in their code. The same way as described in [dotnet/performance/#Preventing Regressions](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md#preventing-regressions).

I see that you've already put some effort into writing a simplistic diff tool for that meter ([ResultsComparer](https://github.com/dotnet/performance/blob/master/src/tools/ResultsComparer/README.md)).
**Would it be possible to extract this little tool into a separate repository and publish it on nuget.org as a dotnet global tool to make it accessible outside of [dotnet/performance](https://github.com/dotnet/performance/tree/1eeb4115827694f3d05af8a868cf6dfb99f0bb03/src/tools/ResultsComparer)?** There's not much code in it, but still, it would be a good thing to do, I believe.

**Comment by billwert** [comment]
Hi @Kosat! thanks for making me aware of dotnet/command-line-api#469. I think we should host those benchmarks in this repo as we host the [ml.net](https://github.com/dotnet/performance/tree/master/src/benchmarks/real-world/Microsoft.ML.Benchmarks) benchmarks. I'll jump over to the other issue and see what they think.

**Comment by billwert** [comment]
Hi @Kosat! If you'd like to use the ResultsComparer code in the command like repo, you can just copy it. It doesn't make sense right now to ship it separately as its own package.

Thanks for your contributions!

**Comment by adamsitnik** [comment]
Hello @Kosat !

Thanks for using Results Comparer. @billwert is right, the simplest way for now it to copy paste it.

We plan to add similar feature to BenchmarkDotNet global tool. You can follow this issue for updates; https://github.com/dotnet/BenchmarkDotNet/issues/973
