### ISSUE TITLE
[android] adb error: failed to stat remote object ...

### ISSUE THREAD

**Issue by matouskozak** [dotnet/performance#4477]
Some of the recent rolling buildsbuilds of `Performance windows x64 release AndroidMono JIT android_scenarios perfpixel4a NoJS False False False ...` job are failing with:
```
adb: error: failed to stat remote object '/sdcard/Android/data/com.microsoft.maui.benchmarks/files/': No such file or directory
```

Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2544601&view=logs&j=793c6d4e-58f5-590b-5a6e-d187dc684998&t=b3f1561f-7a45-552d-4614-820dbf74f8a3

cc: @LoopedBard3, @jkurdek

**Comment by LoopedBard3** [comment]
I think I have found a solution to this, will hopefully have a PR up by EOD.

**Comment by LoopedBard3** [comment]
This will be fixed once the linked PR goes and the updates are flowed to the maui net9.0 branch (main is merged into net9.0 weekly). I will watch to make sure this occurs in a timely manner.
