### ISSUE TITLE
Tool builds failing on net9.0 runs due to NU1102

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#4524]
We are hitting `error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 8.0.11)` (soon to fail to find reference (= 9.0.0) once https://github.com/dotnet/performance/pull/4523 is merged). This seems similar to https://github.com/dotnet/sdk/issues/42379 where we have to add new feeds to make the latest packages available. This is affecting main branch performance-ci runs.

**Comment by LoopedBard3** [comment]
Found that this dependency was updated in this PR: https://github.com/dotnet/sdk/pull/44257. We plan on taking the added feed `<add key="darc-pub-dotnet-runtime-d398172" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-d3981726/nuget/v3/index.json" />` and using it ourselves for now.

**Comment by DrewScoggins** [comment]
To solve this issue we have to options:

1. We can setup darc to automatically push the version and Nuget.config updates as they are created.
2. During release time we can just make sure that we update our Nuget.config manually when we move from stable version to stable version.
