### ISSUE TITLE
[Discussion] How can we detect regressions in CoreFX libs that are not part of the shared sdk?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#462]
This is a follow up to https://github.com/dotnet/performance/pull/438 and to my today's conversation with @stephentoub 

As of today, the [MicroBenchmarks.csproj](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/MicroBenchmarks.csproj) references following CoreFX packages:

https://github.com/dotnet/performance/blob/3b75c755a25dc11ae405351c7b9b476760e98755/src/benchmarks/micro/MicroBenchmarks.csproj#L21-L31

For those packages which are part of the shared sdk we are detecting regressions using our existing infrastracture. The script used by CI: [benchmarks_ci.py](https://github.com/dotnet/performance/blob/master/scripts/benchmarks_ci.py) downloads the latest dotnet cli with latest sdk and runs the benchmarks using it. If `MicroBenchmarks.csproj` references and older version of a library present in the latest shared sdk, the latest version from shared folder is loaded and used. This is the most common scenario.

The problem are libraries that are not part of the shared sdk:
- System.Drawing.Common
- System.IO.Pipelines
- System.Threading.Channels

As of today, we don't catch the regressions for these libraries because we are referencing a single, hardcoded version. This is my fault, I did miss this scenario when working on the performance repo.

# Proposal

I have few ideas how we could solve this issue:

## Maestro

Use Maestro for dependency flow (the performance repo is already using it for Arcade updates) to update those 3 packages. 

The side effect is that we would trigger the benchmark runs every time new versions are released. 

@ViktorHofer how many times a day we can expect those packages to be updated?
@billwert do you think that this is desired and our infra is ready for more runs?

## Asterisk

The alternative to Maestro is to use an asterisk in version numbers and let the NuGet client restore the latest package.

```xml
<PackageReference Include="System.Drawing.Common" Version="4.*" />
<PackageReference Include="System.IO.Pipelines" Version="4.*" />
<PackageReference Include="System.Threading.Channels" Version="4.*" />
```
It's a very simple change, however it makes it hard to find out which version is currently used. I personally don't like it and would prefer the explicit approach.

# Remaining Issues

The problem is that both solutions work only for the explicitly configured packages. When we add new benchmarks that require a new dependency, somebody can forget about the proper configuration and introduce a new dependency to a hardcoded version.

I have been chatting with @ViktorHofer about it and he mentioned that there was an idea to introduce a `CoreFx.Private.OOB` package that would reference all packages that are not part of the shared sdk. IMHO this combined with Maestro dependency flow would solve the problem for good. 

@ericstj @ViktorHofer @billwert  what do you think?

**Comment by billwert** [comment]
Thanks @adamsitnik! @adiaaida has been working on how we're going to wire up runs for CoreCLR / CoreFX. I'd like to propose we make sure the solution to the overall problem takes this into account. (We need something similar for ML.Net and other out of band packages.)

**Comment by billwert** [comment]
@adamsitnik @ViktorHofer one useful piece of information: what repo do those packages come out of? Are they in their own, or are they built out of CoreFX but not included in the shared runtime for whatever reason?

**Comment by adamsitnik** [comment]
An update from @ViktorHofer https://github.com/dotnet/corefx/issues/34957#issuecomment-494178211 :

> https://github.com/dotnet/corefx/pull/37784 adds Microsoft.Private.CoreFx.OOB, a meta-package which references all OOB packages. You probably want to use that package instead of manually referencing all OOB packages and setup a darc subscription to it to always stay on the newest version.

So the fix would be to reference the new package and use darc for auto-updates.

@billwert @adiaaida what do you think? it would be nice to fix this problem as we are not testing the latest bits for some parts of the CoreFX

**Comment by billwert** [comment]
This is super useful! This will go a good bit of the way to solving this problem.

Will this produce builds independent of CoreFX? Put differently, what circumstances would a darc update for this trigger where a corefx update wouldn't or vice versa? Is this OOB a thing that itself needs to be independently tested? (I would assume no.)

We are also exploring other ways to do corefx/coreclr/other runs that don't involve darc, so while it will probably be correct to use this package we may not want to trigger runs on it directly in any case.

**Comment by ViktorHofer** [comment]
> Will this produce builds independent of CoreFX? Put differently, what circumstances would a darc update for this trigger where a corefx update wouldn't or vice versa? Is this OOB a thing that itself needs to be independently tested? (I would assume no.)

No, the version is exactly the same and we publish it together with other corefx packages.

> Is this OOB a thing that itself needs to be independently tested? (I would assume no.)

No, just threat the package reference with the additional assemblies as part of the BCL.

> We are also exploring other ways to do corefx/coreclr/other runs that don't involve darc, so while it will probably be correct to use this package we may not want to trigger runs on it directly in any case.

Why is that? Darc is the preferred way to flow dependencies between repositories.

**Comment by billwert** [comment]
> Why is that? Darc is the preferred way to flow dependencies between repositories.

We are exploring options to start runs that happen in the context of the individual repos instead.

**Comment by ViktorHofer** [comment]
> We are exploring options to start runs that happen in the context of the individual repos instead.

That would be great. In CoreFx we ideally don't want to clone the performance repo at all but just run BenchmarkDotNet with the assemblies produced here (and probably published to Darc).

**Comment by billwert** [comment]
> In CoreFx we ideally don't want to clone the performance repo at all

Can you talk more about that?

**Comment by ViktorHofer** [comment]
> Can you talk more about that?

Sure. I talked with @adamsitnik offline about this. In CoreFx we as a dev ideally don't want to clone the performance repository at all just to run its tests on our build. This would be possible by packaging up the produced test assemblies from this repository and publish it to the dotnet-core feed and update darc to let consumers know about it. In CoreFx we would take a dependency on that package via darc subscription and restore it so that we can run the tests via a simple target / command.

**Comment by billwert** [comment]
> This would be possible by packaging up the produced test assemblies from this repository and publish it to the dotnet-core feed and update darc to let consumers know about it

Here's another vote for the build and run separation we talked about for BDN, @adamsitnik ..

**Comment by NickCraver** [comment]
I'm curious, has the thinking on this has changed any? I have a current scenario of wanting to submit some improvements for `Microsoft.Extensions.Caching.Memory`, but I can't figure out how to benchmark them aside from manually creating the NuGet packages and reference swapping them locally. Though these are in `dotnet/runtime`, it doesn't seem like there's a friendly way to profile them _as far as I can find_. Am I missing a path here, or are libraries still an unknown gap?

**Comment by ericstj** [comment]
Cc @maryamariyan

**Comment by adamsitnik** [comment]
> Am I missing a path here

**Comment by adamsitnik** [comment]
> I can't figure out how to benchmark them aside from manually creating the NuGet packages and reference swapping them locally

@NickCraver The alternative is to reference the source files directly in the project with benchmarks, but this would work only locally and for simple things.

@DrewScoggins @billwert I think that we should re-discuss this problem and solve it.

**Comment by adamsitnik** [comment]
@NickCraver It was hard for me to accept the fact that it does not work as it should so I just tested it with CoreRun and it looks like it works the way we need it to work.

You can see the commit here: https://github.com/adamsitnik/performance/commit/463591cd9539b67f43879973c6d930671e8e373f

```cs
using BenchmarkDotNet.Attributes;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Diagnostics;

namespace MicroBenchmarks
{
    [BenchmarkCategory(Categories.Libraries)]
    public class CachingMemory
    {
        [GlobalSetup]
        public void PrintVersionAndPath()
        {
            Console.WriteLine("---------------");
            Console.WriteLine(typeof(MemoryCache).Assembly.Location);
            Console.WriteLine(FileVersionInfo.GetVersionInfo(typeof(MemoryCache).Assembly.Location));
            Console.WriteLine("---------------");
        }

        [Benchmark]
        public MemoryCache Some()
        {
            var cache = new MemoryCache(new MemoryCacheOptions());

            cache.CreateEntry("key").SetValue("value");

            cache.Dispose();

            return cache;
        }
    }
}
```

When running the benchmark using default SDK from PATH:

```cmd
dotnet run -c Release -f netcoreapp5.0 --filter CachingMemory
```

It prints:

```log
---------------
C:\Projects\performance\artifacts\bin\MicroBenchmarks\Release\netcoreapp5.0\03a923ea-4370-450d-8955-60b62cdc0813\bin\Release\netcoreapp5.0\Microsoft.Extensions.Caching.Memory.dll
File:             C:\Projects\performance\artifacts\bin\MicroBenchmarks\Release\netcoreapp5.0\03a923ea-4370-450d-8955-60b62cdc0813\bin\Release\netcoreapp5.0\Microsoft.Extensions.Caching.Memory.dll
InternalName:     Microsoft.Extensions.Caching.Memory.dll
OriginalFilename: Microsoft.Extensions.Caching.Memory.dll
FileVersion:      5.0.20.25106
FileDescription:  Microsoft.Extensions.Caching.Memory
Product:          MicrosoftR .NET
ProductVersion:   5.0.0-preview.4.20251.6+47ec733ba79b196e4e09d0c89bad245155002353
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         Language Neutral

---------------
```

While running it with CoreRun from my local build of dotnet/runtime repo:

```cmd
dotnet run -c Release -f netcoreapp5.0 --filter CachingMemory \\
--corerun C:\Projects\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\5.0.0\CoreRun.exe
```

CoreRun loads and uses `microsoft.extensions.caching.memory.dll` from it's folder:

```log
---------------
C:\Projects\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\d90e0d2d-d5e3-4dd7-a5ac-47497f728916\microsoft.extensions.caching.memory.dll
File:             C:\Projects\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\d90e0d2d-d5e3-4dd7-a5ac-47497f728916\microsoft.extensions.caching.memory.dll
InternalName:     Microsoft.Extensions.Caching.Memory.dll
OriginalFilename: Microsoft.Extensions.Caching.Memory.dll
FileVersion:      42.42.42.42424
FileDescription:  Microsoft.Extensions.Caching.Memory
Product:          MicrosoftR .NET
ProductVersion:   5.0.0-dev
Debug:            False
Patched:          False
PreRelease:       False
PrivateBuild:     False
SpecialBuild:     False
Language:         Language Neutral

---------------
```

It looks that the simplicity of CoreRun combine with [this BDN logic](https://github.com/dotnet/BenchmarkDotNet/blob/9a34695c8395e2d39b7dae2e25a10aa7121ae74e/src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunPublisher.cs#L34-L64) has saved me again ;)

**Comment by NickCraver** [comment]
@adamsitnik I have no idea what I was doing last night (and fell back to DLL refs) but it's indeed working now! Awesome. I was wondering if there was magic for this and if so where it was - thank you!

**Comment by DrewScoggins** [comment]
Yeah, @adamsitnik. Let's setup some time to discuss this and see if we can get a plan together on what the best way forward is to solve this.
