### ISSUE TITLE
Run "regression detector" on microbenchmarks on 2.2 and 3.0

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/performance#557]
We need to do a run using @adamsitnik 's script to find any regressions between 2.2 and 3.0 so we can investigate and fix before the platform closes down to changes for 3.0.

Is anyone planning to do this and if so, on what timeframe? I would prefer get a first read now. @billwert is this your team?

@billwert @RussKeldorph @adamsitnik

**Comment by danmosemsft** [comment]
cc @karelz

**Comment by billwert** [comment]
Probably. @adiaaida how can we run 2.2 in the new system so we have the results in the DB and can use the new tool?

**Comment by adiaaida** [comment]
I can get 2.2 running in the lab pretty easily. I don't know anything about the regression detector, but if there is data in benchview/the new database, is that enough?

**Comment by adamsitnik** [comment]
>  I don't know anything about the regression detector

I think that Dan meant the [ResultsComparer](https://github.com/dotnet/performance/tree/master/src/tools/ResultsComparer) but if I remember correctly the "new tool" (btw do you have some name for it?) is based on it so it should work in the same way.

If you want to use the ResultsComparer:

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
py .\scripts\benchmarks_ci.py -f netcoreapp2.2 --filter * --bdn-artifacts "netcoreapp2.2"
py .\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter * --bdn-artifacts "netcoreapp3.0"
dotnet run -p .\src\tools\ResultsComparer\ResultsComparer.csproj --base .\netcoreapp2.2 --diff .\netcoreapp3.0 --threshold 2%
```

**Comment by danmosemsft** [comment]
Yeah I guess I meant the ResultsComparer -- or whatever the "using proper statistical methods" way is to automatically detect significant regressions between two large test runs without the slow and painful manual comparison we previously had to do. 😄

**Comment by billwert** [comment]
Yes. We got this.

**Comment by danmosemsft** [comment]
How is it looking? No pressure, I'm just scheduling work now we are closing down and wondering when we'll have a first idea of the scale of the regressions if any. 😃

**Comment by billwert** [comment]
It's my afternoon. :) (We had a misconfiguration in the lab and all the data didn't make it properly, so we had to re-run last night.) expect news by Monday. Sorry for the delay.

**Comment by danmosemsft** [comment]
No problem, thanks for the update. Just glad you guys are doing this.

**Comment by billwert** [comment]
I think between our efforts and @adamsitnik stepping in to help finish it out this is done.

**Comment by danmosemsft** [comment]
Thank you everybody.
