### ISSUE TITLE
" Method not found" Error Building Master against sdk dotnet sd 3.0.100-preview6 

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#612]
Platform: MacOS Mojave 10.14.5
Version: A clone of master (dotnet/performance) from last week.

I tried building micro against the latest 3.0 preview, and got this error (below). It looks like it is looking for something that doesnt' exist in the SDK? Any ideas how to reo

~/workspace/perf-mono/performance/src/benchmarks/micro [master ↓·10|…1]> sudo msbuild /p:Configuration=Release MicroBenchmarks.sln 
Microsoft (R) Build Engine version 16.0.459+g5b35a69a2e for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 7/3/2019 3:23:38 PM.
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.sln" (1) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) on node 1 (default targets).
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2:2) on node 1 (UpdateXlf target(s)).
_UpdateXlf:
Skipping target "_UpdateXlf" because all output files are up-to-date with respect to the input files.
Done Building Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (UpdateXlf target(s)).
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2:3) on node 1 (UpdateXlf target(s)).
_UpdateXlf:
Skipping target "_UpdateXlf" because all output files are up-to-date with respect to the input files.
Done Building Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (UpdateXlf target(s)).
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2:4) on node 1 (UpdateXlf target(s)).
_UpdateXlf:
Skipping target "_UpdateXlf" because all output files are up-to-date with respect to the input files.
Done Building Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (UpdateXlf target(s)).
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2:5) on node 1 (Build target(s)).
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: System.MissingMethodException: Method not found: System.Collections.Generic.IList`1<string> NuGet.ProjectModel.LockFileTargetLibrary.get_FrameworkReferences() [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteItemGroup (System.Action writeItems) [0x0000e] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteItemGroups () [0x0005a] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.Write () [0x00006] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteToCacheFile () [0x00040] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash) [0x00049] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00015] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups () [0x00000] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore () [0x00018] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <eb5d17e1070643339362a343d0987998>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <eb5d17e1070643339362a343d0987998>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
Done Building Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (Build target(s)) -- FAILED.
Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2) is building "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (2:6) on node 1 (Build target(s)).
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: System.MissingMethodException: Method not found: System.Collections.Generic.IList`1<string> NuGet.ProjectModel.LockFileTargetLibrary.get_FrameworkReferences() [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteItemGroup (System.Action writeItems) [0x0000e] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteItemGroups () [0x0005a] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.Write () [0x00006] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.WriteToCacheFile () [0x00040] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash) [0x00049] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00015] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups () [0x00000] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore () [0x00018] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <465433aecc4e4125ae090de9fa6902e7>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <eb5d17e1070643339362a343d0987998>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
/usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <eb5d17e1070643339362a343d0987998>:0  [/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
Done Building Project "/Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/MicroBenchmarks.csproj" (Build target(s)) -- FAILED.

**Comment by adamsitnik** [comment]
Hi @naricc 

In this repository, we are using the latest builds of .NET Core 3.0 which you can download from https://github.com/dotnet/core-setup/.

> A clone of master (dotnet/performance) from last week.

Please make sure that you have pulled changes from https://github.com/dotnet/performance/pull/594

**Comment by naricc** [comment]
Using the latest .Net Core 3.0 got it to build, thanks.
