### ISSUE TITLE
Fix ubench guidelines to observe best practices

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/performance#668]
The samples in the https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md sometimes fail to return a result.

Document should be updated to observe best practice.

For instance
```C#
[Benchmark]
public void Reverse()
{
    int[] array = Enumerable.Range(0, 1_000).ToArray();

    Array.Reverse(array);
}
```

**Comment by adamsitnik** [comment]
thanks! fixed in #670
