### ISSUE TITLE
Implement more EH benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#684]
From @AndyAyersMS in https://github.com/dotnet/performance/pull/679#issuecomment-513277069

> Performance of some construct S (a simple int array summation loop, say)

    at top-level in an EH-free method, versus
    inside the try of a try / catch where no exception is raised
    inside the try of a try / finally where the finally is empty
    inside the finally of a try / finally where the try is empty
    inside the try of a try / finally where the loop control variable is referenced in the finally
    inside the try of a try /catch where the loop control variable is referenced in the catch
    inside the try of a try / when / catch where the loop control variable is referenced in the when
    inside the finally of a try / finally where the loop control variable is initialized in the try
    split into two equal loops at top-level in an EH-free method
    split into two equal loops with half in inside the try and half inside the finally of at try / finally
    inside a using block where the array is pinned and the method return is outside the using
    (perhaps) inside an async method that is immediately awaited

**Comment by billwert** [comment]
Closing old issues. If there's still work to be done, please re-open.
