### ISSUE TITLE
GC Server Not Working for Mono Runtime

### ISSUE THREAD

**Issue by t-takhan** [dotnet/performance#690]
I modified `src/benchmarks/micro/coreclr/Roslyn/CscBench.cs` file as following to run it with concurrent server GC.
```
@@ -15,6 +15,7 @@ using BenchmarkDotNet.Attributes;
 using MicroBenchmarks;

 [BenchmarkCategory(Categories.CoreCLR)]
+[GcServer(true)]
 public class CscBench
 {
     public const int CompileIterations = 1500;
```
Now, if I run this benchmark with dotnet (`dotnet run -c Release -f netcoreapp2.2 --filter CscBench.CompileTest`), the used GC is concurrent server GC. However, if I run the same benchmark with mono runtime (` msbuild /p:Configuration=Release src/benchmarks/micro/MicroBenchmark
s.csproj &&  mono artifacts/bin/MicroBenchmarks/Release/net461/MicroBenchmarks.exe --filter CscBench.CompileTest`), the used GC is concurrent workstation.

I have tried modifying `artifacts/bin/MicroBenchmarks/Release/net461/MicroBenchmarks.exe.config` file to include --
```
<runtime>
+    <gcServer enabled="true"/>
```
-- as well as `src/benchmarks/micro/MicroBenchmarks.csproj` file to include --
```
<PropertyGroup>
+     <ServerGarbageCollection>true</ServerGarbageCollection>
```

Unfortunately, none of them ensures that mono uses server GC. 

How can I ensure mono uses server GC instead of workstation GC?

**Comment by adamsitnik** [comment]
I am not sure if Mono implements Server GC. AFAIK it has [SGen](https://www.mono-project.com/docs/advanced/garbage-collector/sgen/) which is a little different.

@EgorBo @marek-safar does Mono implement Server GC?

**Comment by marek-safar** [comment]
The term ServerGC is quite misleading, it's just a set of GC settings which most of them Mono implements and could be set as GC startup parameters if needed.

**Comment by t-takhan** [comment]
Thank you @adamsitnik and @marek-safar 

@marek-safar Can you give me some pointers on which parameters should I set to have concurrent workstation or concurrent server mode GC on mono.

**Comment by kosomgua** [comment]
@t-takhan I think u could use concurrent-sweep flag

https://www.mono-project.com/docs/advanced/garbage-collector/sgen/working-with-sgen/
