### ISSUE TITLE
Trying to run benchmark on netcoreapp2.2 gives error saying 3.0 isn't supported

### ISSUE THREAD

**Issue by noahfalk** [dotnet/performance#726]
Repro steps: (Following the instructions at https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/README.md)

1) Create VM with Ubuntu 18.04 x64
2) Install .Net Core 2.2 SDK using directions at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
3) Run dotnet run -c Release -f netcoreapp2.2

Expected: Benchmarks run

Actual: Error message is printed:

```
/usr/share/dotnet/sdk/2.2.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFraemworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0. Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0 [/home/noah/performance/src/benchmarks/micro/MicroBenchmarks.csproj]

The build failed. Please fix the build errors and run again.
```

I worked around the issue by removing the netcoreapp3.0 entry from the TargetFrameworks property in the msbuild project, but I am not sure why that was necessary.

**Comment by adamsitnik** [comment]
Hi @noahfalk 

This is expected, it's the default MSBuild behavior. When a project targets few TFMs you need a dotnet cli that supports all of them.

The good news is that we have a python3 script that can download the right cli and run the benchmarks for you:

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
cd scripts
python3 benchmarks_ci.py -f netcoreapp2.2 netcoreapp3.0 --filter '*'
```

**Comment by noahfalk** [comment]
Interesting, the design choice seems surprising to me but fair enough, it is what it is : ) Thanks!

**Comment by billwert** [comment]
> the design choice seems surprising to me but fair enough, it is what it is

Because we use these in automation, we've made some choices that make that easier for the long term. This choice makes it really easy to run different runtimes as baselines without having some rewriting or having Microbenchmarks.22.csproj, etc. We try (as with the python scripts) to wrap it up so it's easy to use outside of automation also.

**Comment by noahfalk** [comment]
Oh I was actually referring to the SDK design choice that you can't have an msbuild project reference a netcoreapp target higher than what the SDK supports. I'm not surprised you guys would want to multi-target your projects : )
