### ISSUE TITLE
Compilation error with latest Roslyn

### ISSUE THREAD

**Issue by filipnavara** [dotnet/performance#865]
The following code no longer compiles:

https://github.com/dotnet/performance/blob/97d49cfc30502b835122d360ca4b93f29215d4cc/src/benchmarks/micro/corefx/System.Buffers/ArrayPoolTests.cs#L39-L47

Compiler reports the following error:

```
corefx/System.Buffers/ArrayPoolTests.cs(44,21): error CS0019: Operator '==' cannot be applied to operands of type 'T' and 'default' [/Users/filipnavara/agent/_work/1/s/work/performance/src/benchmarks/micro/MicroBenchmarks.csproj]
```

This is caused by breaking change in the compiler (https://github.com/dotnet/roslyn/issues/36492) that was previously leading to miscompiled code. Originally reported as https://github.com/dotnet/roslyn/issues/38568, moving here.

**Comment by billwert** [comment]
Thanks for the report! Will take care of this ASAP.
