### ISSUE TITLE
Implement more realistic string benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#885]
The benchmarks that we have as of today for methods like `IndexOf`, `StartsWith` etc use not very realistic test cases and moreover typically test a single culture.

/cc @jkotas

**Comment by danmosemsft** [comment]
Do we rename the benchmark (eg suffix 2 on the name) when making a change that will affect the numbers - so we don't see any step in the graph later?

**Comment by adamsitnik** [comment]
It depends on how big the changes are going to be. It might be just a matter of adding new tests cases, replacing the existing ones or introducing new ones with new names.

**Comment by jkotas** [comment]
For completeness, "do nothing" is also an option to consider. It would mean that we would see one time step in the graph, but the benchmarks would be simpler in the long run.
