### ISSUE TITLE
don't create temp folder when running with Private CoreCLR.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/performance#905]
I am running the benchmarks like:
`dotnet run --framework netcoreapp5.0 -c Release -- --filter * --coreRun F:\git\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\CoreRun.exe`
and it creates a copy of Core_Root near the original one, like `E:\git\coreclr\bin\tests\Windows_NT.x64.Release\Tests\24a3faeb-3410-46c2-ac4e-27debab53a12`,
my primary scenario is to run the benchmarks in PerfView and then analyze the hot methods, because the actual run is done using the temp folder PerfView is looking for files there, but at this moment the temp folder is already deleted so PerfView can't show symbols.
The workaround for it is to pass `--keepFiles` to the `dotnet run`, it will prevent the temp folder deletion, but now when you open ".etl" file you will see many dialogs like:
`E:\git\coreclr\bin\obj\Windows_NT.x64.Release\src\coreclr\hosts\corerun\Release\CoreRun.pdb in a location that may not be trustworthy, do you trust this file?` and have to click yes and for each.

Is it possible not to create a temp folder and use the original pass?

**Comment by adamsitnik** [comment]
If BDN detects that you have some older version of dependencies required to run the benchmarks in CoreRun folder (for example an old version of Newtonsoft.JSON referenced by some CoreCLR unit tests), it's going to overwrite them with newer versions from the published app. It's going to do that in a shadow copy of the folder with CoreRun, so your configuration remains untouched.

> Is it possible not to create a temp folder and use the original pass?

Yes, but you would need to modify the source code of `RecommendedConfig` (it's not possible from command line arguments level):

https://github.com/dotnet/performance/blob/8be66dbe4b42b3b6fb41017e9c62b1eae9cf1b81/src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs#L23-L24

```cs
Job.Default
   .With(new CoreRunToolchain(new FileInfo(@"pathToCoreRun"), createCopy: false, targetFrameworkMoniker: "netcoreapp5.0"))
```

**Comment by adamsitnik** [comment]
@sandreenko I am closing, please feel free to reopen if the suggested change does not help.

**Comment by sandreenko** [comment]
The suggested change helped me to get rid of temp files and still have symbols (note: add `using BenchmarkDotNet.Toolchains.CoreRun;` and don't pass `--coreRun` to the run).

It has not helped with 
"E:\git\coreclr\bin\obj\Windows_NT.x64.Release\src\coreclr\hosts\corerun\Release\CoreRun.pdb in a location that may not be trustworthy, do you trust this file?", but I think we can live with clicking that dialog window.

**Comment by adamsitnik** [comment]
> It has not helped with
"E:\git\coreclr\bin\obj\Windows_NT.x64.Release\src\coreclr\hosts\corerun\Release\CoreRun.pdb in a location that may not be trustworthy, do you trust this file?

It's possible to disable this warning. I've not done it in a while, but as far as I remember you should just pass "TrustPdbs" when starting PerfView

```cmd
PerfView.exe /TrustPdbs
```
