### ISSUE TITLE
Performance issues in System.Collection exposed by new benchmarks

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#93]
With the new benchmarks we can compare "apples to apples" which exposed a lot of interesting differences.

This issue is an aggregation of many issues, I will report them in CoreFX once I make the CoreFX dev experience very good.

**Comment by danmosemsft** [comment]
What to do here -- seems to me each of these findings could become an issue in CoreFX perhaps for community interest, then we coud close this?

**Comment by adamsitnik** [comment]
@danmosemsft I created the issues in CoreFX:

https://github.com/dotnet/corefx/issues/36405
https://github.com/dotnet/corefx/issues/36406
https://github.com/dotnet/corefx/issues/36407
https://github.com/dotnet/corefx/issues/36412
https://github.com/dotnet/corefx/issues/36413
https://github.com/dotnet/corefx/issues/36414
https://github.com/dotnet/corefx/issues/36415
https://github.com/dotnet/corefx/issues/36416

We have officially switched to the performance repo in CoreFX so next time I find a performance issue in CoreFX using performance repo I am going to create an issue in CoreFX
