### ISSUE TITLE
Opening the project in VS results in files that are not gitignored

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/performance#937]
Freshly forked & opened the `MicroBenchmarks` solution on VS2019, and I'm suddenly seeing 26 new files which appears to be some sort of CMake output files. Are they supposed to be tracked?
![image](https://user-images.githubusercontent.com/42944058/66770198-efd8c280-eef1-11e9-83d7-218f1c16039b.png)

**Comment by Gnbrkm41** [comment]
Looks like we may be able to just ignore the whole `src/benchmarks/gc/src/exec/env/out` folder?

**Comment by adamsitnik** [comment]
The MicroBenchmarks solution has no native dependencies, I have no idea why you are seeing anything related to CMake. Which version of VS are you using?

**Comment by Gnbrkm41** [comment]
It appears that the VS automatically generates CMake files when I load the whole `performance` repo folder, actually. The CMake section of VS Output window shows:
```
1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\gotos\Source\Repos\performance\src\benchmarks\gc\src\exec\env\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\gotos\Source\Repos\performance\src\benchmarks\gc\src\exec\env" 2>&1"
1> Working directory: C:\Users\gotos\Source\Repos\performance\src\benchmarks\gc\src\exec\env\out\build\x64-Debug
1> [CMake] -- The C compiler identification is MSVC 19.24.28117.0
1> [CMake] -- The CXX compiler identification is MSVC 19.24.28117.0
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.24.28117/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/Users/gotos/source/repos/performance/src/benchmarks/gc/src/exec/env/out/build/x64-Debug
1> [CMake] 
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> CMake generation finished.
```

It's VS2019 / 16.4.0 P1.

**Comment by billwert** [comment]
Wild. This is coming out of the new GC stuff we checked in. That isn't in the sln at all, so there's something weird going on. We'll figure it out. Sorry!

@andy-ms can you take a look at this?

**Comment by andy-ms** [comment]
Latest commit to https://github.com/dotnet/performance/pull/931 should fix this.

**Comment by billwert** [comment]
I'm curious why this is happening at all in the context of the microbenchmarks.csproj project, though. I'll look at that a bit before I merge the fix. (Gonna be a few hours.)

**Comment by andy-ms** [comment]
@billwert I think it was due to opening the root `performance` directory instead.

**Comment by billwert** [comment]
Ah, okay. @Gnbrkm41 did you build the new GC stuff (using build.cmd) and then open Microbenchmarks.sln?

VS is just showing all the files in the workspace that are edited. The right fix there is as it is in #931. I just wanted to make sure somehow the Microbenchmarks project wasn't somehow doing something magic.

**Comment by Gnbrkm41** [comment]
I did not build anything before opening the solution.

> I think it was due to opening the root performance directory instead.

I think this is the case; I experimented around, and by deleting the `.vs` folder then opening the `performance` folder (not the microbench solution) in VS, I was able to see the files generated along with the messages on the CMake output window.

**Comment by billwert** [comment]
ah, weird. I didn't know it would automatically run those. I wonder if there is a way to suppress that.

Generally we don't expect folks to open the folder directly, but to use the .sln under Microbenchmarks. That's part of the confusion for me.
